### ISSUE TITLE
[Mobile] Dark Mode Shows as Black Text on Dark background 

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [CollaboraOnline/online#7233] opened 2023-09-11 02:50 UTC
### Describe the Bug

When the app is in dark mode the text still shows in the original color selection. That makes it pretty impossible to use as its unreadable.

### Steps to Reproduce
Downloaded newest version from F-Droid repository https://www.collaboraoffice.com/downloads/fdroid/repo/
  
Open app 

(Appears to be in Dark mode by default, I'm uncertain if that's app design, or if that's basef on some other setting on my phone, I do usually prefer dark model )

Select Folder icon

Choose previously existing .odt file.

### Expected Behavior
In dark mode black text would show as l
white  text on black background 

### Actual Behavior

Shows as black text on dark background.

### Screenshots

https://libranet.de/photo/403310564164fe7c3d4c20a776255341-0.png

.

https://libranet.de/photo/936047438164fe7c3f6dc9b133018950-0.png

### Smartphone

(Please complete the following information)
 - **Device:** Samsung Galaxy A51
 - **OS:** 13
 - **Browser:** DuckDuckGo (default)
 - **Version:** 5.162.2 (latests from F-Droid)

### Additional Context
This was my first time ever using the app after seeing mention on my local Linux User Group mail-list.

https://libranet.de/photo/139871031564fe7f02c3fad709253744-0.png

**Comment by timur-g** [comment] 2023-09-11 07:55
If prevoius text is Black color, this is not a bug, ypu need to change it to Automatic color.

**Comment by Tex2002ans** [comment] 2023-09-12 20:52
Yes, like timur-g said, your specific document probably has text that's:

- FORCED "Black" color instead of "Automatic".

This leads to the black-on-black text.

- - -

For a little more info on this, see my comment last month in:

- [/r/LibreOffice: "Dark theme bug?"](https://www.reddit.com/r/libreoffice/comments/15cvoeh/dark_theme_bug/ju0pixx/)

A similar situation would happen if the person who created the document:

- Forced a background color too.

For example, a background/highlight that is marked as:

- Yellow
- White
- Red

will not change colors, even if you flip on "Dark Mode".

You'd have to change the document to use "Automatic" background color instead.

**Closed** 2023-09-12 21:19 UTC
Labels: info needed, dark-mode, 23.05
