### ISSUE TITLE
CODE 6.4.10: Major Performance Regression Again When Closing Calc Sheet

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#3015] opened 2021-08-01 10:11 UTC
**Describe the bug**
CODE again takes about 30 seconds to just close a calc sheet with comments.

I reported bug #2745 for the original 6.4.10, which was fixed meanwhile, and now a very similar bug is back in the current CODE release, again related to closing a Calc document with cell comments.

LOOLWSD
6.4.10 (git hash: b4fa48ef)
Angeboten von: 4c9508ca
LOKit
Collabora Office 6.4-45 (git hash: a21347f)
"Ubuntu 18.04.5 LTS"

You really should add some basic automated regression testing - I think this could help a lot to identify such massive performance issues as soon as they are introduced.
Especially, as the whole "cell comments" thing in CODE Calc seems to be quite challenging to get right, given the number of performance and malfunction bugs I already had reported, which rendered the comments practically unusable in many previous versions of CODE.
You surely don't want to slip something like this into a future commercial COOL release, I guess...

**To Reproduce**
1. Open a Calc sheet with several comments (not quite sure how many it was in my case, but not *that* many actually.
2. Close the sheet.

**Expected behavior**
The document closes quickly.

**Actual behavior**
The document freezes for about 30 seconds, eating 100% CPU and the browser reports that the page blocks the browser.

Opening the document also seems to be a bit slower than in intermediate CODE 6.4.10 versions, but - different from Bug #2745 - it's currently nowhere as bad as closing the document.

**Screenshots**
![image](https://user-images.githubusercontent.com/26199042/127767077-9f1f2566-7ea1-421e-ad1b-d68997d4c51f.png)

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 (KDE neon)
 - Browser:
Chromium
Version 91.0.4472.101 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Additional context**
LOOLWSD
6.4.10 (git hash: b4fa48ef)
Angeboten von: 4c9508ca
LOKit
Collabora Office 6.4-45 (git hash: a21347f)
"Ubuntu 18.04.5 LTS"

**Comment by thebearon** [comment] 2021-08-02 15:53
Thanks for the report! I couldn't reproduce considerable slowness when using the sample from https://github.com/CollaboraOnline/online/issues/2745#issuecomment-873732467 , I get perhaps a very slight, 1 sec delay. Please be aware that we don't have access to the same files as you, and thus may not get the same results.

I went fishing again, and found another bugdoc that indeed exhibits significant slowdown when closing:
https://bugs.documentfoundation.org/attachment.cgi?id=122489 (from https://bugs.documentfoundation.org/show_bug.cgi?id=97698 )

Still only around 6 seconds, but that is a lead we can follow. @gokaysatir, this may be interesting to you.

**Comment by mmeeks** [comment] 2021-08-03 14:45
Thanks for reporting: this should fix it - https://github.com/CollaboraOnline/online/pull/3024 =)

**Comment by gohrner** [comment] 2021-08-03 15:27
> Thanks for reporting: this should fix it - #3024 =)

Great, thanks! :)

Curiously waiting for a CODE release which includes this fix to try it out.

**Comment by mmeeks** [comment] 2021-08-03 15:43
Neato - we should have one reasonably soon; thanks for testing! [ now I need to merge to master so you can try on staging - do you have an account there to test with ? ]

**Comment by thebearon** [comment] 2021-08-06 04:37
The fix is available in CODE 6.4.10-9.

**Closed by thebearon** 2021-08-06 04:37 UTC
Labels: bug

**Comment by gohrner** [comment] 2021-08-06 11:16
@mmeeks:

> Neato - we should have one reasonably soon; thanks for testing! [ now I need to merge to master so you can try on staging - do you have an account there to test with ? ]

Not sure what "staging" is in the context of CODE, so I probably don't have an account.

**Comment by gohrner** [comment] 2021-08-10 17:03
I can confirm that this issue is fixed in

LOOLWSD
6.4.10 (git hash: 7151e02)
Angeboten von: 5a0f0788
LOKit
Collabora Office 6.4-45 (git hash: a21347f)
"Ubuntu 18.04.5 LTS"
