### ISSUE TITLE
Glow & Soft Edge effect in slides doesn't seem to render correctly in higher zoom factors

### ISSUE THREAD

**Issue by SustReal** [CollaboraOnline/online#4029] opened 2022-01-19 14:40 UTC
**Describe the bug**
The glow & soft edge effects that can be applied to shapes don't seem to render correctly if the zoom factor of a slide is increased 100%. The original shape behaves unexpectedly.

**To Reproduce**
1. Apply Glow & Soft Edge effects to a shape
2. Increase zoom level
3. See wrongly rendered effect

**Expected behavior**
I'd expect the effect to look the same on all zoom factors

**Actual behavior**
In other zoom factors the effects looks diferrently. 

**Screenshots**
Glow & Soft edge Effect on zoom factor 100%
![grafik](https://user-images.githubusercontent.com/51329893/150151664-77fe6c4e-5840-49c1-a4b0-4f0b1fe55ae8.png)

Glow & Soft edge Effect on zoom factor 120%
![grafik](https://user-images.githubusercontent.com/51329893/150151747-7d84ea20-1876-437c-ade4-96615da1c67a.png)

Glow & Soft edge Effect on zoom factor 150%
![grafik](https://user-images.githubusercontent.com/51329893/150151845-3438aee5-5670-40fe-9d15-2501d3ced140.png)

**Desktop (please complete the following information)**
 - OS: [Ubuntu 20.04]
 - Browser: [firefox]
 - Version: [95.0.1]

**Smartphone (please complete the following information)**
 - 

**Additional context**
-

**Comment by thebearon** [comment] 2022-01-20 04:51
Confirmed, and here's a sample:
[triangle.odp](https://github.com/CollaboraOnline/online/files/7902371/triangle.odp)

It can also be reproduced with the `gtktiledviewer` tool in core.

Something else that's unrelated, but I want to note somewhere (because it isn't worth bothering with further) that in a core build, if you have the sidebar open and click into the triangle, the size of the glow effect increases a lot. This one's already fixed in 7.3: https://bugs.documentfoundation.org/show_bug.cgi?id=140250

**Comment by Ezinnem** [comment] 2022-07-22 15:02
Fixed with the commit: https://gerrit.libreoffice.org/c/core/+/137339

 Fine on:

COOLWSD version:
21.11.5.3 git hash: [391a917d](https://github.com/CollaboraOnline/online/commits/391a917d)
LOKit version:
Collabora OfficeDev 21.06.31.1 git hash: [7d74030](https://git.libreoffice.org/core/+log/7d74030)

**Closed by Ezinnem** 2022-07-22 15:02 UTC
Labels: bug, core, 21.11.X
