### ISSUE TITLE
Spell checking (dictionaries) for some languages not working

### ISSUE THREAD

**Issue by brknkfr** [CollaboraOnline/online#6477] opened 2023-05-30 13:38 UTC
**Describe the bug**
Spell checking doesn't work in several languages (for example German, Swiss German, French, Swiss French, Ukrainian, Russian). Funny though, that Italian and Spanish spell checking is working

**To Reproduce**
Steps to reproduce the behavior for German and Swiss German:
1. Install and configure code-brand (the Debian way: https://www.collaboraoffice.com/code/linux-packages/)
2. Adapt /etc/coolwsd/coolwsd.xml and add `de_CH`, `de_DE` and `it_CH` and `it_IT` (or more other languages) to the `allowed_languages` parameter.
3. Install packages for German: `apt install collaboraoffice-dict-de` (and/or `hunspell-de-de`/`hunspell-de-ch`/`hunspell-de-de-frami`/`hunspell-de-ch-frami`)
4. Install packages for Italian: `apt install collaboraoffice-dict-it` (and/or `hunspell-it`)
5. Write something in German a new document (code connected over Nextcloud)
6. Spellchecking is not done (No dictionaries recognized, see attached image.)
![image](https://github.com/CollaboraOnline/online/assets/4104421/2d45fd14-215f-4691-ae63-5c533ad1b1b4)

**Expected behavior**
All the installed dictionaries should be recognized and should be working.

**Actual behavior**
Some dictionaries (for instance I tested only German, Swiss German, French, Swiss French, Ukrainian and Russian)

**Desktop (please complete the following information)**
 - OS: Up to date Debian system
 - Browser: Chrome, Firefox, etc.
 - Version: 22.05.15.2-1 (coolwsd) / 25.0.7 (Nextcloud) / 7.1.4 (Nextcloud Office/richdocuments)

**Comment by gitgt** [comment] 2023-07-19 08:31
I do not reproduce. 
![image](https://github.com/CollaboraOnline/online/assets/7240617/533a35c5-beeb-455d-a1af-81edd2449b7c)
Please check if hunspell are really installed. 
You may also test 23.05, soon there will be 23.05.2 with many fixes, including for setting language..

**Comment by timur-g** [comment] 2023-08-02 14:33
Did you maybe enable languagetool?

**Comment by brknkfr** [comment] 2023-08-09 11:35
Yes, languagetool is enabled. As soon I disable languagetool, the german dictionaries appear and this is what I do for the moment.

So is there a conflict between languagetool and the "dictionary method"?

Unfortunately, the selfhosted instance of languagetool is not working, see https://github.com/CollaboraOnline/online/issues/5016

**Comment by timur-g** [comment] 2023-08-09 12:23
No, languagetool has a few issues, like not working in mixed languages paragraph, but it is working in general.
So still not clear where your problem comes fom.
You should report all the details, how do you use languagetool, of course if selt-hosted this is a duplicate.

**Comment by timur-g** [comment] 2024-03-20 10:48
Since there was no folloup and explanation if self-hosted, not potential motions to correct, let me close this.

**Closed by timur-g** 2024-03-20 10:48 UTC
Labels: bug, unconfirmed, info needed, 22.05.x

**Comment by brknkfr** [comment] 2024-03-20 10:55
It is working now and I think, it was related to https://github.com/CollaboraOnline/online/issues/5016
