### ISSUE TITLE
Calc: Comment box appears behind Sheet toolbar.

### ISSUE THREAD

**Issue by rpear** [CollaboraOnline/online#2959] opened 2021-07-27 08:09 UTC
The Comment box appears behind the Sheet toolbar instead of above it, see picture.
To reproduce hover over or add a comment to a cell that is slightly above the Sheet toolbar.
This was on a Chromebook accessing CODE on 6.4.10snapshot (git hash: 25b2adb) Commits on Jul 20, 2021  Served by: 557df1a3
![Screenshot 2021-07-27 6 04 20 PM](https://user-images.githubusercontent.com/80790599/127119610-106abed9-f472-4f71-ae0e-6ba592bff655.png)

**Comment by rpear** [comment] 2021-07-29 01:41
This is now working properly on My Chromebook against the newer LOOLWSD 6.4.10snapshot (git hash: b4fa48ef) Served by: 73881885. I don't know which commit fixed it. @Ezinnem please will you close this issue for me.

**Comment by Ezinnem** [comment] 2021-07-29 06:40
Since the behavior is no longer reproducible, it is best to close the issue.

**Closed by Ezinnem** 2021-07-29 06:40 UTC
Labels: bug, unconfirmed
