### ISSUE TITLE
"Ordered List" Sidebar Button Does Not Work 2nd Time

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7248] opened 2023-09-12 23:26 UTC
### Describe the Bug

The "Ordered List" sidebar button does not work correctly after first list type change.

### Steps to Reproduce

0. Open ["Broken.Ordered.List.Sidebar.odt"](https://github.com/CollaboraOnline/online/files/12591547/Broken.Ordered.List.Sidebar.odt)
1. **View > Sidebar**
2. In document:
   - Left-Click in "1. One".
3. In the sidebar, in the "Ordered List" icon:
   - Press the little dropdown arrow.
4. Choose one of the other list types.
   - For example, choose `a)` or `i.` instead.
      - (I chose `a)` every time.)
5. Repeat Step 4, except choose the original.
   - I chose `1.`.

Get this error:

     warn:sw.core:25757:25369:sw/source/core/doc/docfmt.cxx:1621: Found unknown auto SwNumRule during reset!

### Actual Behavior

Ordered List gets stuck at:

- `1.` -> `a)`

Never makes it back to `1.`.

### Expected Behavior

Ordered List should change back:

- `1.` -> `a)` -> `1.`

### Desktop

- **OS:** Linux Mint 21.1
- **Browser:** Firefox
- **Version:** 117.0 (64-bit)

> COOLWSD version: 23.05.4.1 (git hash: 938b8e31)
> LOKit version: Collabora Office 23.05.4.1 (git hash: 88afeef)
> Served by: Linux Mint 21.1
> Server ID: 13d1685e

Steps (+ sidebar button) work perfect in:

> Version: 7.6.0.3 (X86_64) / LibreOffice Community
> Build ID: 69edd8b8ebc41d00b4de3915dc82f8f0fc3b6265
> CPU threads: 8; OS: Windows 10.0 Build 19045; UI render: Skia/Raster; VCL: win
> Locale: en-US (en_US); UI: en-US
> Calc: CL threaded

### Additional Context

While testing this, I also got a random crash:

     warn:legacy.tools:25757:25369:sfx2/source/control/bindings.cxx:1775: No cache for OfficeDispatch!
     warn:legacy.osl:25757:25369:sfx2/source/sidebar/ResourceManager.cxx:515: expecting three or four values per ContextList entry, separated by comma
	 kit-25847-25369 2023-09-12 18:50:09.705362 -0400 [ kit_spare_003 ] SIG  frk-25369-25369 2023-09-12 18:50:09.705362 -0400 [ forkit ] SIG   Shutdown signal received:  Shutdown signal received: SIGINTSIGINT

I was not able to reproduce, but it was various mixes of:

- After Step 4:
   - Choosing an Ordered List.
   - \+ `Ctrl+Z`, trying to reset the list back to its original form.

This "Ordered List" button in the sidebar *definitely* acts very glitchy:

- Sometimes the button/dropdown became "not clickable" or acted like "one solid button".
   - I suspect that might disappear if this initial `unknown auto SwNumRule` issue gets fixed?
- Sometimes the ordered list preview images "went off the screen".

<img src="https://github.com/CollaboraOnline/online/assets/5774324/d73ecbc3-a709-45e5-a00a-8a1dfc6b9f1a" alt="Collabora 23.05.4.1 - Sidebar Ordered List" width="30%" >
<img src="https://github.com/CollaboraOnline/online/assets/5774324/55f0872f-5d0d-4e96-819b-f9d94172a585" alt="Collabora 23.05.4.1 - Sidebar Ordered List Cropped" width="30%" >

I could not figure out a rhyme or reason behind when it was cropped vs. when it wasn't.

**Comment by timur-g** [comment] 2023-09-19 11:45
Seen already in 23.05.0.5.

**Comment by eszkadev** [comment] 2023-09-25 08:31
Sorry, I don't understand this bug report. Can you provide a video showing the bug?
I don't understand
```
Ordered List gets stuck at:

    1. -> a)

Never makes it back to 1..```

It means that sometimes selected "Style" of numbering is not applied? (I cannot reproduce that)

**Comment by timur-g** [comment] 2023-09-25 09:58
Here is a video.
https://github.com/CollaboraOnline/online/assets/7240617/1e310c86-1e16-4746-a1d1-9ba4d9e25e62

**Comment by Darshan-upadhyay1110** [comment] 2024-07-15 13:08
> Here is a video. https://github.com/CollaboraOnline/online/assets/7240617/1e310c86-1e16-4746-a1d1-9ba4d9e25e62

hii @timur-g i am not able to reproduce this issue can you confirm so i can close this with latest version hash.
Thanks

**Comment by Darshan-upadhyay1110** [comment] 2024-07-22 12:48
COOLWSD version: 24.04.5.2 (git hash: df56d78c)
LOKit version: Collabora OfficeDev 24.04.5.2 (git hash: b57fd97)
Served by: Ubuntu 23.10
Server ID: f3983cff

**Closed by Darshan-upadhyay1110** 2024-07-22 12:48 UTC
Labels: bug, regression, sidebar, 23.05

**Comment by timur-g** [comment] 2024-07-23 11:03
I am not sure about this one, seems like working, but sometimes needs more clicks. Not sure.
