### ISSUE TITLE
Option to access admin console without password

### ISSUE THREAD

**Issue by schklom** [CollaboraOnline/online#6752] opened 2023-06-27 12:43 UTC
**Is your feature request related to a problem? Please describe.**
I would like to access the admin console (e.g. https://collabora.mydomain/browser/dist/admin/admin.html) without requiring a password.
I prefer 2FA securing https://collabora.mydomain/browser/dist/admin/... behind a dedicated service like Authelia / Authentik.

**Describe the solution you'd like**
An Docker environment variable like `DONT_REQUIRE_CREDENTIALS_ADMIN: true` or a CLI flag like `--no-credentials`.

**Comment by timur-g** [comment] 2024-01-25 09:55
Duplicate of #5051.

**Closed by timur-g** 2024-01-25 09:55 UTC
Labels: enhancement, unconfirmed
