### ISSUE TITLE
build with Poco 1.13.0 throws fatal exception

### ISSUE THREAD

**Issue by timar** [CollaboraOnline/online#8065] opened 2024-01-19 22:29 UTC
Latest Poco version is 1.13.0. Building with it resulted in error:
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
NULL pointer: strategy [in file "src/FileChannel.cpp", line 283]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Failed to initialize COOLWSD: Null pointer: strategy in file "src/FileChannel.cpp", line 283
wsd-16951-16951 2024-01-19 21:57:00.272728 +0000 [ coolwsd ] FTL  Failed to initialize COOLWSD: Null pointer: strategy in file "src/FileChannel.cpp", line 283| wsd/COOLWSD.hpp:532
Null pointer: strategy in file "src/FileChannel.cpp", line 283
```
This error does not occur with Poco 1.12.4.

**Comment by timar** [comment] 2024-01-19 22:30
@Ashod FYI

**Comment by thebearon** [comment] 2024-01-22 10:56
I think the problem is that POCO after https://github.com/pocoproject/poco/commit/66e93f98cc3530c9ea5a748cf2248d2592b61853 doesn't handle rotation strategy `never` properly.

See:
`setRotationStrategy(createRotationStrategy(rotation, _times));`
https://github.com/pocoproject/poco/blob/6d7a4ffd7b996359ef9d10ddcc940c0d9099ad6b/Foundation/src/FileChannel.cpp#L292

Here `createRotationStrategy(...)` results in a nullptr strategy, because the function doesn't create a strategy for never, but then `setRotationStrategy(...)` starts by checking whether it's a valid pointer.

**Comment by thebearon** [comment] 2024-01-23 05:32
PR in Poco: https://github.com/pocoproject/poco/pull/4412

**Comment by thebearon** [comment] 2024-01-24 11:34
The fix is now merged, and is part of the 1.13.1 milestone.

**Closed by thebearon** 2024-01-24 11:34 UTC
Labels: bug, unconfirmed

**Comment by kolAflash** [comment] 2025-06-18 20:17
FYI @ Debian users building COOL:  
At the moment it looks like Debian-13 _(Trixie, currently testing, hard-freeze)_ will unfortunately ship with exactly `poco-1.13.0`.  
https://packages.debian.org/source/trixie/poco  
And Debian's current `1.13.0-6` also doesn't patch this.

**Comment by timar** [comment] 2025-06-18 21:46
@kolAflash FYI:
I recommend building Poco from source. In production we use Poco 1.12.5p2, and we had bad experience with newer versions, such as performance issues. 

1. Download Poco from tarball. The latest known good release is 1.12.5p2

- https://pocoproject.org/releases/poco-1.12.5p2/poco-1.12.5p2-all.tar.gz

2. Build static Poco
```
./configure --static --no-tests --no-samples --no-sharedlibs --cflags="-fPIC" --omit=Zip,Data,Data/SQLite,Data/ODBC,Data/MySQL,MongoDB,PDF,CppParser,PageCompiler,Redis,Encodings,ActiveRecord,Prometheus,JWT
make -j"$(nproc)" && sudo make install
```
