### ISSUE TITLE
cp: cannot create regular file '/opt/cool/systemplate/etc/resolv.conf': Permission denied

### ISSUE THREAD

**Issue by peterge1998** [CollaboraOnline/online#6645] opened 2023-06-19 09:24 UTC
**Describe the bug**
code is not starting

**To Reproduce**
1. Update with watchtower
2. View docker logs -f

**Expected behavior**
Just start normally as a few days before

**Actual behavior**
Code does not start and produces the log below.

**docker logs -f**
```
cp: cannot create regular file '/opt/cool/systemplate/etc/resolv.conf': Permission denied                                                               cp: cannot create regular file '/opt/cool/systemplate/etc/hosts': Permission denied
Permission denied at /start-collabora-online.pl line 97.                    cp: cannot create regular file '/opt/cool/systemplate/etc/resolv.conf': Permission denied                                                               cp: cannot create regular file '/opt/cool/systemplate/etc/hosts': Permission denied
Permission denied at /start-collabora-online.pl line 97.                    cp: cannot create regular file '/opt/cool/systemplate/etc/resolv.conf': Permission denied                                                               cp: cannot create regular file '/opt/cool/systemplate/etc/hosts': Permission denied
Permission denied at /start-collabora-online.pl line 97.                    cp: cannot create regular file '/opt/cool/systemplate/etc/resolv.conf': Permission denied                                                               cp: cannot create regular file '/opt/cool/systemplate/etc/hosts': Permission denied
Permission denied at /start-collabora-online.pl line 97.                    cp: cannot create regular file '/opt/cool/systemplate/etc/resolv.conf': Permission denied                                                               cp: cannot create regular file '/opt/cool/systemplate/etc/hosts': Permission denied
Permission denied at /start-collabora-online.pl line 97.
```

**Desktop (please complete the following information)**
 - OS: ubuntu 23

**Additional context**
I am using watchtower.
My docker-compose.yml:
```
collabora-code:
    image: collabora/code                                                       container_name: collabora-code
    restart: unless-stopped
environment:
      - username=admin
      - password=...
      - ...
```

**Comment by term1n4l** [comment] 2023-06-22 00:26
I am getting a similar problem also with the docker image 23.05.0.5.1:

Permission denied at /start-collabora-online.pl line 97.

although I don't see what is causing the 'permission denied' when I look at the container logs

**Comment by peterge1998** [comment] 2023-06-22 06:50
https://forum.collaboraonline.com/t/cp-cannot-create-regular-file-opt-cool-systemplate-etc-resolv-conf-permission-denied/1906

**Comment by peterge1998** [comment] 2023-06-22 17:08
The controller is in the restarting status after running docker compose up -d, thats why i can not exec it to view the files:
`914aadf1cc56   collabora/code                  "/start-collabora-on…"   3 days ago       Restarting (1) 20 seconds ago`
My only option is to use docker logs

**Comment by vitorsemeano** [comment] 2023-06-23 00:07
I can confirm that this is also happening to me since 23.05rc1 and latest version.

Using the latest 22.05 the problem disappears and the container is stable.

Something happened in these latest versions that gives these permission errors with resolv.conf and perhaps other files.

When i was troubleshooting, i found that 2 files (one of them is resolv.conf) had different owner/group in the filesystem of the container, in comparison with other files.

**Comment by lxsang** [comment] 2023-07-04 12:33
I also have the same problem with  23.05rc1 and up

**Comment by schklom** [comment] 2023-07-10 23:21
# SOLUTION FOR AN ISSUE WITH A VERY SIMILAR LOG
I had a very similar issue for a few weeks, and had to use a past version `collabora/code:22.05.14.3.1` because all newer ones failed. On the newer images, my logs were
```
Permission denied at /start-collabora-online.pl line 97.
```

In my Collabora docker-compose service, I only mount
```yaml
    volumes:
      - ./collabora/coolwsd.xml:/etc/coolwsd/coolwsd.xml
```
It turns out that for some reason, the IDs of the user and group `cool` have been changed.
Before, `cool:cool` mapped to the IDs `104:106`.
In the recent Collabora images, `cool:cool` maps to the IDs `100:102`.

So, a simple 
```bash
docker exec -u 0 collabora chown 100:102 /etc/coolwsd/coolwsd.xml
docker compose restart collabora
```
made the new image work for me.

PS: Yes, I can change the permissions outside the container, but I use Rootless Docker which uses namespaces so the IDs outside the containers are a pain to figure out so I prefer to modify inside the container :P

**Comment by lxsang** [comment] 2023-07-17 15:51
Changing owner works for me.

However i need to do it outside the container (i.e. on the host system) as the container failed to start due to the error.

In my docker compose i have:

```yaml
volumes:
      - cool-config-volume:/etc/coolwsd
```

The following files shall be chowned:

```sh
# cd to the volume folder
chown 100:102 coolwsd.xml
chown 100:102 proof_key
chown 100:102 proof_key.pub
```

**Comment by term1n4l** [comment] 2023-07-19 03:27
so I was copying my coolwsd.xml file into the container with the old permissions which was causing my problem, after chowning the file with the new UID/GID, I can launch the latest code containers

**Comment by nonofr91** [comment] 2023-07-31 19:59
Good morning,
I have a similar problem and looking in the bash portainer console I realize that in /opt/cool/ the two directories do not have the same owner (cool and root)?
drwxr-xr-x 3 cool cool 4096 Jul 31 21:48 child-roots
drwxr-xr-x 11 root root 4096 Jul 25 18:13 systemplate

Is it possible that your problem comes from there?

**Comment by frankgrimy** [comment] 2023-08-27 19:08
> Key to resolve the issue was changing the user for the container from 104 (old version) to 100.

Can confirm. Changed it inside Portainer at the Deploy tab.

**Comment by timur-g** [comment] 2023-08-28 11:01
Seems we can close this one.

**Closed by timur-g** 2023-08-28 11:01 UTC
Labels: bug, docker, 23.05
