### ISSUE TITLE
Document title overlaps menu on 1280×1024 monitor

### ISSUE THREAD

**Issue by kkofler** [CollaboraOnline/online#4806] opened 2022-05-23 17:19 UTC
**Describe the bug**
On my 1280×1024 LCD, the centered document title overlaps the menu. I have to zoom smaller in the browser (leading to really tiny text) to have it not overlap.

**To Reproduce**
1. Open an ODT document in Nextcloud with CODE integration.

**Expected behavior**
No overlapping text. The document title is either displayed to the right of the menu, or above, or not at all.

**Actual behavior**
The document title overlaps the Help menu and part of the "Last saved: …" text. As a result, Help is not clickable.

**Screenshots**
Normal size (showing the bug):
![Screenshot_20220523_190439](https://user-images.githubusercontent.com/5055817/169871729-9e9c1ab6-b515-4012-a964-6a76ea3a2705.png)
Zoomed out 3 times (no bug, but tiny text):
![Screenshot_20220523_191125](https://user-images.githubusercontent.com/5055817/169872620-841a88c8-c169-47b9-99c7-c307880b29c4.png)

**Server**
 - COOLWSD Version: 21.11.4.2 (git hash: 3eff190)
 - LOKit Version: Collabora Office 21.06.28.1 (git hash: f63c415)
 - Nextcloud 24.0.1
 - Ubuntu 20.04.4 LTS

**Desktop**
 - OS: Fedora
 - Browser: Falkon
 - Version: Falkon 3.1.0, QtWebEngine 5.15.2 (Chromium 83)

**Additional context**
The width looks decisive for the overlapping. Zooming out 3 times works around it.

**Comment by sebastiaanveld** [comment] 2022-05-26 10:31
Same issue as #4613

**Comment by kkofler** [comment] 2022-05-26 12:07
Thanks for the pointer. I guess we can close this bug as a duplicate then, can't we?

**Comment by sebastiaanveld** [comment] 2022-06-08 19:03
Looks fixed in Staging.
COOLWSD versie: 22.05.0.1 git hash: [d11a23be]
LOKit versie:
Collabora Office 22.05.2.1 git hash: [8d1627f]

**Comment by thebearon** [comment] 2022-06-15 21:30
Yes, let's close as duplicate of #4613. Thanks!

**Closed by thebearon** 2022-06-15 21:30 UTC
Labels: bug, unconfirmed
