### ISSUE TITLE
Missing/Broken functionality of Dictionary buttons

### ISSUE THREAD

**Issue by hmeeks-dot** [CollaboraOnline/online#5727] opened 2023-01-18 19:30 UTC
**Description of bug**
In Calc in Review>Spelling>Options the side buttons for new, edit do not seem to work

**To Reproduce**
1. Calc online -> Review Panel -> Spelling -> Options
2. Try clicking on the buttons for new/edit ...
3. See error -  nothing happens!

**Expected behavior**
The buttons should pop up other dialogues with the correct functionality - add new dictionaries, edit existing ones to include certain words etc.

**Actual behavior**
Nothing happens when clicked

**Desktop**
 - OS: Linux
 - Browser: chrome
 - Version:  96.0.4664.45

**Comment by hmeeks-dot** [comment] 2023-02-10 10:21
This is also the same in writer - the buttons should be hidden for now...

**Comment by Ezinnem** [comment] 2023-02-20 19:31
The button seems to work on my need. I have to first enable the spellchecker with the language set

See my recording:

https://user-images.githubusercontent.com/54344301/220185810-61f27bdd-ae7b-413a-b687-0a3267261381.mp4

**Comment by Ezinnem** [comment] 2023-08-21 12:53
Closing this issue because it does not seem reproducible on my end and the author has not responded.

**Closed by Ezinnem** 2023-08-21 12:53 UTC
Labels: bug, unconfirmed, 22.05.x
