### ISSUE TITLE
Horizontal scroll is allowed on touch screen

### ISSUE THREAD

**Issue by tintou** [CollaboraOnline/online#4189] opened 2022-02-14 09:24 UTC
**Describe the bug**
On my computer I'm able to scroll horizontally using the touch screen in a point where the document is not visible anymore, note that it is not possible to scroll using the touchpad

**To Reproduce**
1. Go to a text document
2. Unzoom to make sure that the document left and right margin are inside the viewport
3. Use the touch screen to scroll left or right
4. See that it's even possible to scroll so that the document is out of the viewport

**Expected behavior**
It shouldn't be possible to scroll out of the viewport

**Screenshots**

https://user-images.githubusercontent.com/745535/153836101-db0cc935-5e9a-44a4-bce1-e96fdce6c5f7.mp4

**Comment by Ezinnem** [comment] 2022-02-14 12:29
This issue does not seem reproducible on my end using the COOLWSD version: 21.11.2.0 git hash: [e179126
](https://github.com/CollaboraOnline/online/commits/e179126)
@tintou, Please can you share the Collabora Online version you are using?

**Comment by tintou** [comment] 2022-02-14 13:53
I'm using Loolwsd 6.4.14 (git hash: fdc7ddf7)

**Comment by Ezinnem** [comment] 2022-02-21 13:48
This seems to have been fixed on #4014  

I cannot reproduce it on COOLWSD version: 6.4.20 git hash: [ef7e80e1](https://github.com/CollaboraOnline/online/commits/ef7e80e1)

**Comment by Ezinnem** [comment] 2022-04-21 13:55
Still not reproducible on  COOLWSD version: 6.4.24 git hash: [7aa1cd2](https://github.com/CollaboraOnline/online/commits/7aa1cd2)

**Closed by Ezinnem** 2022-04-21 13:55 UTC
Labels: bug, unconfirmed
