### ISSUE TITLE
coolwsd.x86_64 24.04.7.1-1 update on rhel clones timeout and restart in loop

### ISSUE THREAD

**Issue by unnilennium** [CollaboraOnline/online#9949] opened 2024-08-31 18:28 UTC
### Describe the Bug
tonight I got collwsd and related rpm updated from 24.04.6.2-1 to 24.04.7.1-1.
Since then I am not able to edit any document. calling collabora from nextcloud hit multiple timeout, test page to see if service is up timeout too 
restart or service does not help

### Steps to Reproduce
1. upgrade
2. try to open a document : timeout

### Expected Behavior
still working after upgrade

add requirement for /usr/bin/coolforkit-caps or coolwsd-deprecated in spec files as it is needed

### Actual Behavior
service does not work after upgrade
upgrade process has introduced a breaking change which is not expected in a linux enterprise distribution
without lookin at the whole log the recurrent error do not point to the actual issue:

Aug 31 13:58:44 atlas coolwsd: wsd-07940-07940 2024-08-31 13:58:44.956173 -0400 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
Aug 31 13:58:49 atlas coolwsd: wsd-07940-07952 2024-08-31 13:57:44.956883 -0400 [ prisoner_poll ] TRC  PollSocket container size has changed from 0 to 1| net/Socket.cpp:521
Aug 31 13:58:49 atlas coolwsd: wsd-07940-07952 2024-08-31 13:57:44.956906 -0400 [ prisoner_poll ] TRC  #15: setupPollFds getPollEvents: 0x1| net/Socket.hpp:880
Aug 31 13:58:49 atlas coolwsd: wsd-07940-07952 2024-08-31 13:57:44.956921 -0400 [ prisoner_poll ] TRC  ppoll start, timeoutMicroS: 64000000 size 1| net/Socket.cpp:430
Aug 31 13:58:49 atlas coolwsd: wsd-07940-07952 2024-08-31 13:58:49.020367 -0400 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (64000000us)(timedout)| net/Socket.cpp:448

### Screenshots
logs:
Aug 31 14:04:49 atlas coolwsd: coolforkit-caps does not exist, install coolwsd-deprecated package
Aug 31 14:04:49 atlas coolwsd: wsd-09486-09496 2024-08-31 14:04:49.842885 -0400 [ prisoner_poll ] TRC  PrisonerPoll - wakes up with 0 new children and 0 brokers and 0 kits forking| wsd/COOLWSD.cpp:3488
Aug 31 14:04:49 atlas coolwsd: wsd-09486-09496 2024-08-31 14:04:49.842912 -0400 [ prisoner_poll ] INF  Creating new forkit process.| wsd/COOLWSD.cpp:3511
Aug 31 14:04:49 atlas coolwsd: wsd-09486-09496 2024-08-31 14:04:49.843054 -0400 [ prisoner_poll ] FTL  coolforkit-caps does not exist, install coolwsd-deprecated package| wsd/COOLWSD.cpp:3603
Aug 31 14:04:49 atlas coolwsd: wsd-09486-09496 2024-08-31 14:04:49.843075 -0400 [ prisoner_poll ] INF  Launching forkit process: /usr/bin/coolforkit-caps --systemplate=/opt/cool/systemplate --lotemplate=/opt/collaboraoffice --childroot=/opt/cool/child-roots/9486-79399bcd/ --clientport=9980 --masterport=coolwsd-morlJOh8 --rlimits=limit_virt_mem_mb:0;limit_stack_mem_kb:8000;limit_file_size_mb:0;limit_num_open_files:0 --version --ui=classic| wsd/COOLWSD.cpp:3625
Aug 31 14:04:49 atlas coolwsd: wsd-09486-09496 2024-08-31 14:04:49.843193 -0400 [ prisoner_poll ] INF  Forkit process launched: 9497| wsd/COOLWSD.cpp:3631
Aug 31 14:04:49 atlas coolwsd: coolforkit-caps does not exist, install coolwsd-deprecated package

**Comment by nursoda** [comment] 2024-09-01 16:16
I see the same thing I described it in [issue 9318](https://github.com/CollaboraOnline/online/issues/9318#issuecomment-2323335575) (probably would have been better off here than in a closed bug that I cannot reopen…). But even this [issue 9949](https://github.com/CollaboraOnline/online/issues/9949) seems to be a duplicate of [issue 9948](https://github.com/CollaboraOnline/online/issues/9948), so let's (only) continue there (and someone please close this one).

**Comment by ErikDW1** [comment] 2024-09-02 08:16
Same error on CentOS installation......
Tried to do a downgrade with "yum undo" but it failed. Do you have any tip on how to do it?
Thanks.

**Comment by timar** [comment] 2024-09-02 13:19
Some background info: https://caolanm.blogspot.com/2024/08/linux-namespaces-and-collabora-online.html
@unnilennium What is your RHEL version?

**Comment by stormenergy91** [comment] 2024-09-05 11:08
Same on Ubuntu 24.04. After do an `apt dist-upgrade` the system was updated to `24.04.1` and coolwsd to `24.04.7.1-1` but now the coolwsd service failed to start. Running the command manually i get  this error (using the command with params as in the systemd config file):
```
wsd-64132-64132 2024-09-05 11:02:01.361948 +0000 [ coolwsd ] ERR  #-1: Failed setsockopt SO_REUSEADDR: Bad file descriptor (EBADF: Bad file descriptor)| net/Socket.cpp:1011
wsd-64132-64132 2024-09-05 11:02:01.361954 +0000 [ coolwsd ] ERR  #-1: Failed to bind to: IPv4 port: 9980 (EBADF: Bad file descriptor)| net/Socket.cpp:1048
```
I don't know if can be useful.

**Comment by unnilennium** [comment] 2024-09-09 21:57
yum install coolwsd-deprecated 

will workaround it for those already experiencing the issue. but it should have been automatic on update.

**Comment by stormenergy91** [comment] 2024-09-12 08:32
> yum install coolwsd-deprecated
> 
> will workaround it for those already experiencing the issue. but it should have been automatic on update.

On Ubuntu (24.04.1) also installing that package the problem remain.

**Comment by timur-g** [comment] 2024-09-13 14:13
Apart fom workaround, it would be good to confirm if this is still seen with 24.04.7.2.1.

**Comment by stormenergy91** [comment] 2024-09-14 19:14
Updated `coolwsd` to `24.04.7.2-1` but the problem is still there (Ubuntu 24.04.1)

**Comment by timar** [comment] 2024-09-15 06:51
@stormenergy91 I think you get these messages, because coolwsd started by systemd is still running. You cannot start a second coolwsd manually, because the port is taken.

**Comment by stormenergy91** [comment] 2024-09-15 15:58
@timar I stopped the `coolwsd` system service before running the command manually. There are other cool services that I need to stop?

**Comment by timur-g** [comment] 2024-09-16 06:27
@stormenergy91  That issue seems different from the originally reported. You have port busy, should see what keeps it.

**Comment by stormenergy91** [comment] 2024-09-16 08:16
@timur-g I make a new test on a fresh install machine:

Here what I do:
- Installed Ubuntu Server 24.04.1 and do all updates with `sudo apt dust-upgrade`
Then this steps:
```
$ cd /usr/share/keyrings
$ sudo wget https://collaboraoffice.com/downloads/gpg/collaboraonline-release-keyring.gpg	

$ sudo nano /etc/apt/sources.list.d/collaboraonline.sources	

# Add those lines
Types: deb
URIs: https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-deb
Suites: ./
Signed-By: /usr/share/keyrings/collaboraonline-release-keyring.gpg	

$ sudo apt update
$ sudo apt install coolwsd code-brand	-y
``` 
After install simply do `sudo service coolwsd status` i get:
```
× coolwsd.service - Collabora Online WebSocket Daemon
     Loaded: loaded (/usr/lib/systemd/system/coolwsd.service; enabled; preset: enabled)
     Active: failed (Result: core-dump) since Mon 2024-09-16 08:10:07 UTC; 18s ago
   Duration: 1.236s
    Process: 456 ExecStart=/usr/bin/coolwsd --version --o:sys_template_path=/opt/cool/systemplate --o:child_root_path=/opt/cool/child-roots --o:file_server_root_path=/usr/share/coolwsd (code=dumped, signal=ABRT)
   Main PID: 456 (code=dumped, signal=ABRT)
        CPU: 1.046s

Sep 16 08:10:07 UbuntuCool systemd[1]: coolwsd.service: Scheduled restart job, restart counter is at 5.
Sep 16 08:10:07 UbuntuCool systemd[1]: coolwsd.service: Start request repeated too quickly.
Sep 16 08:10:07 UbuntuCool systemd[1]: coolwsd.service: Failed with result 'core-dump'.
Sep 16 08:10:07 UbuntuCool systemd[1]: Failed to start coolwsd.service - Collabora Online WebSocket Daemon.
Sep 16 08:10:07 UbuntuCool systemd[1]: coolwsd.service: Consumed 1.046s CPU time.
```

If i try to restart the service it start for a couple of seconds than go in failed mode.

**Comment by timur-g** [comment] 2024-09-16 08:22
That does not seem at all like the original issue which I assume was resolved and so close the issue. 
And that does not seem like a bug either, needs to be configured..

**Closed by timur-g** 2024-09-16 08:22 UTC
Labels: bug, unconfirmed

**Comment by stormenergy91** [comment] 2024-09-16 08:26
> That does not seem at all like the original issue which I assume was resolved and so close the issue. And that does not seem like a bug either, needs to be configured..

Before the update to `24.04.7.1-1` all work. So with the new version what i need to configure to make it work again?

**Comment by chillriver** [comment] 2024-12-30 07:46
@stormenergy91 

Hey stormernergy91,

did you solve your problem or still exists? I have the same problem. Perhaps you created a new issue for that.
