### ISSUE TITLE
23.05: links in dark mode don't have the same color but seem to have the same color in normal mode

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#6698] opened 2023-06-22 10:22 UTC
**Describe the bug**

During the weekly sync I saw the following difference in dark/normal mode where the links and some text have different colors depending on the mode used.

Normal mode:
![image](https://github.com/CollaboraOnline/online/assets/1211300/7fa30cec-ede4-4661-9584-36599d0785c2)

Dark mode:
![image](https://github.com/CollaboraOnline/online/assets/1211300/fcfd87d3-3990-4774-850b-1d703eb34ef8)

This is the document:
https://staging.eu.collaboraonline.com/nextcloud/index.php/s/9jcNL9Xs5Z6ZcCq

Not sure if it's a bug or not but it looks strange that the colors are so different.

Any ideas what triggers this?

**Comment by Ezinnem** [comment] 2023-06-27 13:02
@pedropintosilva @Darshan-upadhyay1110

**Comment by gitgt** [comment] 2023-06-30 15:52
Link below "25->23 - zero" on right click is not recognized as link. Seem blue with formatting, but did not have URL.
Both are fixed with typing simple space after, when they become links..
That would seem like a not a bug. If you do not mind, I will close. 
What puzzles me is that all links look NOK in LibreOffice, which is for their tracker.

**Closed** 2023-06-30 15:56 UTC
Labels: bug, dark-mode, 23.05
