### ISSUE TITLE
Editing corrupts hyperlinks that don't start with http:// or https://

### ISSUE THREAD

**Issue by mdoggydog** [CollaboraOnline/online#7917] opened 2024-01-02 21:33 UTC
### Describe the Bug
If an existing hyperlink's URL does not already start with `http://` or `https://`,  editing it will force `http://` to be prepended to the URL, regardless of whether that is desired or results in an invalid URL.  The hyperlink dialog wrongly assumes that (a) all URL's must start with `http://` or `https://`, and (b) the user _wants_ all URL's to start with `http://` or `https://`.  

### Steps to Reproduce
0. Load a document (e.g., created elsewhere with LibreOffice) that has a hyperlink with non-HTTP scheme in its URL (e.g., `mailto:`, `tel:`, `ftp:`, `gopher:`, `file:`, `data:`, `irc:`, etc, etc, etc).
1. Click on the hyperlink.
2. Click on edit button for the hyperlink.
3. Click OK in the edit dialog.

### Expected Behavior
No change is made to the hyperlink.

### Actual Behavior
`http://` is prepended to the original URL of the hyperlink.

### Desktop
 - **Collabora version:** Collabora Office 23.05.5.4
 - **OS and version:** Debian GNU/Linux 12 (bookworm) 
 - **Browser and version:** Firefox 115.6.0esr (64-bit)

### Additional Context
CollaboraOnline really should not even bother trying to validate the URL.  Do not bother trying to figure out when to prepend `http://`; just leave the user-provided URL alone.  Even if you checked for any syntactically valid scheme component (via a regexp, e.g., `[a-zA-Z][a-zA-Z0-9+.-]*:`), you cannot predict what the user is trying to accomplish with the link (perhaps a missing scheme is _intentional_).

**Comment by timur-g** [comment] 2024-01-04 15:42
Seems duplicate of #1371.

**Closed by timur-g** 2024-01-04 15:42 UTC
Labels: bug, unconfirmed
