### ISSUE TITLE
Possible values are not shown when editing a cell

### ISSUE THREAD

**Issue by cmorsoc** [CollaboraOnline/online#7384] opened 2023-10-08 21:31 UTC
### Describe the Bug

After creating a validity rule for a column, no message is shown when editing one of the cells of the column. Due to this, the users can not know the values available for this cell.

### Expected Behavior

A list of the possible values could be shown when editing the cell.

### Actual Behavior

No values are shown.

### Desktop

(Please complete the following information)
 - Zorin Linux
 - Firefox and Google Chrome. Same problem.

### Additional Context

It works properly on Google Drive

**Comment by timur-g** [comment] 2023-10-09 16:28
Please always write Collabora version when reporting. 
There are 2 validity bugs, this one seems duplicate of #6986.

**Closed by timur-g** 2023-10-09 16:28 UTC
Labels: bug, unconfirmed
