### ISSUE TITLE
Impossible to copy/spread formula to adjacent cells by dragging

### ISSUE THREAD

**Issue by Stooovie** [CollaboraOnline/online#7205] opened 2023-09-04 09:13 UTC
**Describe the bug**
It's impossible to spread a formula from one cell to the adjacent ones by dragging the corner. 

**To Reproduce**
1 apply a formula to one cell
2 drag the bottom right corner to apply the formula to the adjacent cell

**Expected behavior**
a formula is applied to adjacent cell

**Screenshots**
[Youtube video](https://youtu.be/Oh14sZwZWyY)

**Client details:**
 - OS: MacOS 13.5.1
 - Browser: all browsers. Tried in Safari, any Arc, Edge, Chrome
 - Device: desktop

**Nextcloud version:**

27.0.2 (AIO 7.0.0)

**Office version**
Nextcloud Office 8.1.1

**Comment by timur-g** [comment] 2023-09-04 16:14
Please add Collabora Online version, seen from help-About. 
Do you have HiDpi screen or scaling?  
This seems duplicate of #6738 please search before posting

**Closed** 2023-09-04 16:15 UTC
Labels: bug, unconfirmed, info needed
