### ISSUE TITLE
Collabora Online loses focus after closing Find and Replace dialog with the mouse

### ISSUE THREAD

**Issue by hmeeks-dot** [CollaboraOnline/online#5712] opened 2023-01-16 10:08 UTC
Browser shortcuts confused after a find and replace

**To Reproduce**
1. Open document
2. Open the find and replace dialogue
3. Close dialogue and then Ctrl+S
4. See error - tries to save in desktop and not in browser

**Expected behavior**
Expected to save in browser

**Actual behavior**
Creates an html file to save on computer

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: chrome
 - Version: 96.0.4664.45 (Official Build) (64-bit)

[UI-DialoguesSHORTCUTSBUG.ods](https://github.com/CollaboraOnline/online/files/10424695/UI-DialoguesSHORTCUTSBUG.ods)

**Comment by pedropintosilva** [comment] 2023-01-16 13:23
Thank you @hmeeks-dot for taking the time to test it and report back with such a detailed and clear instructions!

**Comment by thebearon** [comment] 2023-01-17 02:18
This is probably related to JS-based dialogs, perhaps @eszkadev has hints.

**Comment by GulsahKose** [comment] 2023-01-17 06:13
Yes, I inspect and see there are other dialogs has same problem. For example File->Properties. I'm on it. Thanks for the hint.

**Comment by hmeeks-dot** [comment] 2023-01-17 11:21
Hi yeah sorry it also happens when you are typing text into a cell and then
try to save!

This seems to happen pretty generally in calc online so you should be able
to replicate :)

**Comment by GulsahKose** [comment] 2023-01-17 13:47
Patch solves the JSDialog's closing bug: https://github.com/CollaboraOnline/online/pull/5718

**Comment by GulsahKose** [comment] 2023-01-17 14:08
>it also happens when you are typing text into a cell and then try to save!
@hmeeks-dot I couldn't reproduce that one.

**Comment by hmeeks-dot** [comment] 2023-01-17 17:51
Cool thanks,

Sorry I wasn't as clear for the other example:

Open the example document -> SEO-Dashboard.xlx

When you start typing into a new cell and then do a CTR+S ( when the cursor
is in the top panel not in the cell! ) you should get the same problem

I think it could just be another line of code...

**Comment by GulsahKose** [comment] 2023-01-19 11:40
Dialog part of the bug solved. I can reproduce that when we click the empty part of the notebook bar, similar focus problem occurs. I'll turn back here again. Then we can close the issue.

**Comment by pedropintosilva** [comment] 2023-01-19 11:46
Thanks @hmeeks-dot for re-testing and reporting back!

**Comment by GulsahKose** [comment] 2023-01-30 07:20
Fixed with https://github.com/CollaboraOnline/online/pull/5761#event-8373711102

**Closed by GulsahKose** 2023-01-30 07:20 UTC
Labels: bug
