### ISSUE TITLE
"Document cannot be saved due to expired or invalid access token" after some time

### ISSUE THREAD

**Issue by timodenissen** [CollaboraOnline/online#1530] opened 2021-02-25 07:07 UTC
**Describe the bug**
When opening a document, after some time the error message **Document cannot be saved due to expired or invalid access token** pops up and the document can neither be save nor saved as a new file. Copying the content into a new document works though. This does not happen all the time.

**To Reproduce**
1. Open a document
2. Start editing the document
3. Unforseeable the error message pops up, rendering saving impossible

**Expected behavior**
No error message popping up and blocking saving of documents.

**Actual behavior**
An error message pops up and blocks saving of the document

**Desktop (please complete the following information)**
 - OS: OS independant
 - Browser: browser independant

**Server**
Installed on UCS 4.4.7 from the UCS App Center:
```bash
sudo univention-app info
UCS: 4.4-7 errata901
Installed: collabora=6.4.3.1 owncloud=10.6.0
Upgradable: 

sudo docker ps          
CONTAINER ID        IMAGE                                                    COMMAND                  CREATED             STATUS              PORTS                     NAMES
e91ce8bcacfd        docker.software-univention.de/collabora:6.4.3.1          "/bin/sh -c 'bash st…"   2 weeks ago         Up 8 days           0.0.0.0:9980->9980/tcp    agitated_goldberg
e6dddba1997b        docker.software-univention.de/owncloud-owncloud:10.6.0   "/usr/bin/entrypoint…"   4 weeks ago         Up 8 days           0.0.0.0:40003->8080/tcp   owncloud_owncloud_1
202db6b0987b        docker.software-univention.de/owncloud-redis:10.6.0      "/usr/bin/entrypoint…"   4 weeks ago         Up 8 days           6379/tcp                  owncloud_redis_1
```

Installed is the Collabora Online Development Edition.

Since the error is not easily reproducable, in which container/file in the container do we need to get log files from for further analysis?

**Comment by thebearon** [comment] 2021-02-25 15:40
I believe the problem is in ownCloud richdocuments, and should be raised over at
https://github.com/owncloud/richdocuments/issues

There is a commit in the repository with a workaround (it is yet to be released in an update), applying it locally should get rid of the problem:
https://github.com/owncloud/richdocuments/commit/6ec90f4828621f4f61e91558d81f74d92f54fbde

**Closed by thebearon** 2021-02-25 15:40 UTC
Labels: bug, unconfirmed
