### ISSUE TITLE
iOS App: New Slide icon does not work until a new slide is added from the toolbar menu

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#5889] opened 2023-02-22 09:20 UTC
**Describe the bug**
The New Slide icon in the slide bar does not respond to clicks. After the user adds a new slide from the Toolbar, then the New slide icon starts t respond.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a presentation file in iOS app 22.-5.10 build
2. Click on the "New slide" icon
Notice that it does not respond/function as expected (Triggers the keyboard instead of adding a new slide)
4. Go to Slide menu option from the toolbar and add a new slide
5. Click again on the "New slide"; notice that the "New slide icon starts to work as expected

**Expected behavior**
The "New slide" icon adds a new slide

**Actual behavior**
The "New slide" icon does not add a new slide 

**Screenshots**

https://user-images.githubusercontent.com/54344301/220576344-8b9854af-94ee-45fc-a669-ad47117d761c.mp4

**Smartphone (please complete the following information)**
 - Device IOS 22.05.10 build

**Additional context**

**Comment by Ezinnem** [comment] 2023-02-22 09:21
@plubius

**Comment by plubius** [comment] 2023-02-22 15:14
I can also reproduce this bug. On my iPad, tapping the virtual keyboard's "hide" icon hides the keyboard, but then tapping anywhere in the slide list sidebar our the toolbar area shows the keyboard again. So it seems that when an object is in text edit mode, it seems to disable the sidebar and toolbar.

I will need to investigate this bug further. My current theory is that some event needs to be sent from the native code to the JavaScript when hiding the keyboard that indicates that text editing in the current object is done like tapping a different object.

**Comment by plubius** [comment] 2023-03-10 15:37
Using the patch in pull request #5988, the "new slide" and "delete slide" icons now work so it appears this bug is a duplicate of issue #5887 (the code marked the document as read-only).

**Closed by plubius** 2023-03-10 15:37 UTC
Labels: bug, duplicate, ios
