### ISSUE TITLE
File Properties button does not work if GUI language is in Dutch (Netherlands)

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#5814] opened 2023-02-06 06:53 UTC
**Describe the bug**
File Properties button does not work if GUI language is in Dutch (Netherlands). If the Nextcloud user preference is set to to Dutch and an document is opened for editing the COOL GUI is also in Dutch. Selecting the File Properties button does nothing. When the Nextcloud user preference is set to English or Germand and a document is opened for editing the COOL GUI will be either English/German pending the selected language but selecting the File Properties button will show up as expected.

**To Reproduce**
1. Go in Nextcloud to User> Settings > Language 
2. Set the Language to "Dutch" ("Nederlands").
3. Go to the Files section
4. Open an document (ODT) for editing with COOL
5. Go to (File>Properties) "Bestand" > "Eigenschappen", nothing happens
6. Go in Nextcloud to (User> Settings > Language) "Gebruiker" > "Instellingen"> "Taal" 
7. Set the Language to "English" (or German for testing)
8. Go to the Files section
9. Open an document (ODT) for editing with COOL
10. Go to File>Properties and the Properties Dialog shows up.

**Expected behavior**
File Properties dialog show show up.

**Actual behavior**
File Properties dialog does not show up.

**Screenshots**
Nothing hap[pens, when you click the menu option of the button in tabbed mode

**Desktop (please complete the following information)**
 - OS: Windows 11, latest patches
 - Browser1: Firefox 109.0.1, 64 bit, Dutch (Nederlands)
 - Browser2: Microsoft Edge Versie 109.0.1518.78,  64 bit, Dutch (Nederlands)

**Additional context**

**Comment by pedropintosilva** [comment] 2023-02-09 11:00
Thanks @sebastiaanveld , I can confirm the dialog is not localized (it also doesn't change for PT-BR etc) And the strings are also not available in the weblate https://hosted.weblate.org/search/collabora-online/ui/?offset=1&q=+source%3A%22Change+Password%22+&sort_by=-priority%2Cposition&checksum=

**Comment by timar** [comment] 2023-02-09 16:01
@pedropintosilva there's a misunderstanding here. The problem is not that the dialog is unlocalized. by the way it is localized to pt-BR, you just need to build or install language packs for core.
![image](https://user-images.githubusercontent.com/290614/217867044-60069e70-d63a-4e0b-8e36-cbaa0c5a781f.png)

The problem is: for some languages, the dialog does not appear at all. For example nl or da, these are two example that I found. It is very strange.

**Comment by eszkadev** [comment] 2023-02-10 07:21
I cannot reproduce. For me dialog always appears. Tested with current online master, NB and compact view, NL and DA language in Nextcloud and also with `lang=nl`. I used my local build.

What did you use for reproducing that?

**Comment by sebastiaanveld** [comment] 2023-02-10 10:41
@eszkadev For this test I used https://staging.eu.collaboraonline.com (which is the "smoke" reference environment), but I've the same issue with my own environment (running CODE as a container on an openSUSE VM and Nextcloud as a VM build by Hanson.IT https://github.com/nextcloud/vm/releases, both are behind an HAproxy). So if I can duplicate it with the Staging environment then the issues are tagged "smoke bug".

Issue is there with both notebook as well as in compact-view.

Client side I run Windows 11 x64 Dutch with Firefox and Edge x64, Dutch.

Inhttps://staging.eu.collaboraonline.com User language and Regional settings are "Nederlands" and "Dutch (Nederlands)"
![image](https://user-images.githubusercontent.com/37268999/218070047-9407f83f-5f43-468a-a38a-cc0a0f639475.png)

If I then open a document for editing the Properties button does not work. Just nothing visual happens clicking the button.

![image](https://user-images.githubusercontent.com/37268999/218071283-1beb9106-e5ee-4c26-b359-a9f136d9f2cc.png)


CODE inherits the language from Nextcloud here and my Firefox is currently in English (US), so browser language seems not relevant.

![image](https://user-images.githubusercontent.com/37268999/218070988-c6e3e18a-d6fe-461e-a23e-0bb70bf49882.png)

If I now switch my language in Nextcloud to English;

![image](https://user-images.githubusercontent.com/37268999/218071727-6b50ec89-e0f7-4364-a17f-419c99429226.png)

Reopen the document, the CODE UI is now in English, select Properties then the dialog pops up as expected.

![image](https://user-images.githubusercontent.com/37268999/218072008-1ae52bb4-368e-4705-84bf-4da5654d3770.png)

**Comment by eszkadev** [comment] 2023-02-10 13:25
Now I can reproduce. I had no `nl` language in core build.

**Comment by thebearon** [comment] 2023-02-13 17:29
Should be fixed by https://gerrit.libreoffice.org/c/core/+/146900 merged as https://github.com/LibreOffice/core/commit/ba2d21197affa5678143dd3cb3a2003d57bb6e22 .
Thanks, @eszkadev!

**Closed by thebearon** 2023-02-13 17:29 UTC
Labels: smoke bug
