### ISSUE TITLE
iOS app: not possible to copy content from one spreadsheet to an other

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#849] opened 2020-12-02 13:58 UTC
**Describe the bug**
It seems not to be possible to copy data between two separate spreadsheets using the iOS app. This is not about the multitasking feature, but just the case where a single instance of the app is being used.

**To Reproduce**
1. Open a spreadsheet using the iOS app
2. Select some content/cells
3. Tap on "copy" in the notebookbar
4. Close the document
5. Open an other spreadsheet
6. Switch to edit mode
7. Select a cell and make a "long tap" to show the context menu
8. Tap on paste

**Expected behavior**
The content that was copied in the previous spreadsheet should be pasted.

**Actual behavior**
Nothing gets pasted, but a selection is show that matches the size of the content that was copy & pasted.

**Screenshots**
![copy_paste_spreadsheets](https://user-images.githubusercontent.com/1211300/100881850-baed4d80-34ae-11eb-8aa7-9946fdd3fc47.gif)

**Tablet**
 - OS: iPad OS 14.2
 - Version: 6.4.2 (1)

**Comment by tml1024** [comment] 2020-12-03 11:19
On this now. Clipboard functionality is painful, not because accessing the system clipboard (actually called "pasteboard" in iOS and macOS) would be hard in iOS, but because the clipboard concept is hard in "normal" (web-based) Collabora Online and we need to make sure we don't do those overcomplicated things in the mobile app case.

**Comment by tml1024** [comment] 2020-12-03 11:20
It would seem logical to have a similar large friendly "Paste" button in the notebookbar as the "Copy" and "Paste" button, but it is not there exactly because of how this stuff works (or doesn't) in browser-based Collabora Online.

**Comment by tml1024** [comment] 2020-12-03 11:23
How did you manage to get the "Paste" to show up in the long-press menu in a spreadsheet? It doesn't for me.

**Comment by tml1024** [comment] 2020-12-03 11:29
Another clipboard problem I now notice is that if I on my Mac copy just plain text, and try to paste that in Collabora Office on my iPad (which I expect to work flawlessly, it does into other apps on iPad), none of the types in the system pasteboard on the  iPad get mapped to any suitable internal format that LO core accepts:

```
info:vcl.ios.clipboard:43719:6492989:vcl/ios/iOSTransferable.cxx:154: Types on clipboard: public.utf8-plain-text, public.text, com.apple.is-remote-clipboard
info:vcl.ios.clipboard:43719:6492989:vcl/ios/DataFlavorMapping.cxx:565: Was not able to map public.utf8-plain-text to an internal flavour
info:vcl.ios.clipboard:43719:6492989:vcl/ios/DataFlavorMapping.cxx:565: Was not able to map public.text to an internal flavour
info:vcl.ios.clipboard:43719:6492989:vcl/ios/DataFlavorMapping.cxx:565: Was not able to map com.apple.is-remote-clipboard to an internal flavour
```
Will have to fix that. The cross-platform LO core does not look for UTF-8 in the system clipboard, for some historic reason, so I will just have to convert such to UTF-16 in the iOS code. No big deal.

**Comment by tml1024** [comment] 2020-12-03 12:00
When you copy spreadsheet cells to the clipboard, the system pasteboard gets data in the following types:
```application/x-openoffice-dif;windows_formatname="DIF",
application/x-openoffice-emf;windows_formatname="Image EMF",
public.html,
application/x-openoffice-embed-source-xml;windows_formatname="Star Embed Source (XML)",
application/x-libreoffice-tsvc,
text/richtext,
application/x-openoffice-sylk;windows_formatname="Sylk",
application/x-openoffice-objectdescriptor-xml;windows_formatname="Star Object Descriptor (XML)",
application/x-openoffice-wmf;windows_formatname="Image WMF",
application/x-openoffice-gdimetafile;windows_formatname="GDIMetaFile",
public.png,
public.rtf,
public.plain-text,
application/x-openoffice-link;windows_formatname="Link",
application/x-openoffice-bitmap;windows_formatname="Bitmap"
```
But none of those is then good for pasting;) This swamp needs some draining. It is fairly pointless to pug legacy OpenOffice and Windows types on the iOS pasteboard. But we need to put at least one type there that we can then use ourselves... Wonder which one of those that would be.

**Comment by tml1024** [comment] 2020-12-03 12:37
The experts tell me that the proper format to use would be something called "calc8" which apparently also is known as MIMETYPE_OASIS_OPENDOCUMENT_SPREADSHEET_ASCII or application/vnd.oasis.opendocument.spreadsheet. Not sure why that format doesn't get put on the pasteboard.

**Comment by mmeeks** [comment] 2020-12-03 13:38
Rather odd, it should. However - -beware- simplification, I would at least offer all of the same types on the clipboard because some of the paste code-paths I fell over in the past have things like:

if (has_this_weird_mime_type() && has_sane_mime_type())
    use_sane_mime_type_only();

or whatever =) removing the exotic ones can cause grief. And I assume you're going straight to the clipboard and not via the LOK code here (?)

**Comment by tml1024** [comment] 2021-01-13 11:46
Note that a similar problem also exists in desktop LibreOffice on macOS: If you do Edit>Copy on a cell range, quit LibreOffice, and run it again, and open a spreadsheet and try to paste (even Paste Special), you will not get the cells as such. Either, by default, just an image (hah) or if you specifically select the HTML or RTF format, just the values (i.e. no formulae).

**Comment by tml1024** [comment] 2021-01-13 12:50
On Linux, if I have two separate LibreOffice instances running, it is possible to copy a cell range, formulas and all, from a spreadsheet in one process and paste it into a spreadsheet in the other process. The format used seems to be called "LibreOffice 7.0 Spreadsheet" at least in the Edit > Paste Special > Paste Special... dialog (but it surely has at least two internal names in the code, possibly this is the "calc8" that was mentioned earlier, or not).  And if such a format can be copied between two separate processes, there should be no reason why it would not be possible to store the format persistenly in the system clipboard (on macOS and iOS where there is a such).

I just need to figure out what is missing in the macOS (and iOS) clipboard code that prevents that format from being generated and stored.

**Comment by mmeeks** [comment] 2021-01-13 13:42
When I last debugged this - it was not sufficient to have calc8 (or some other component8) on the clipboard, you also needed some 'magic' clipboard mime-type (that no-one in their right mind would add) - and without that it would conclude that it was not the same office source and fallback to something worse. Calc is particularly problematic since if you cut - and then paste - this behaves -very- differently from copy/paste/delete - around moving references etc. so it is necessary to be -sure- it really is the same process & short-circuit.

Hope that helps as a hint.

**Comment by tml1024** [comment] 2021-01-13 21:06
I think I know what the problem is: I have been comparing the behaviour on macOS to that on Linux. On Linux when you have copied a cell range to the clipboard, the MIME Type for one of the formats stored in the clipboard is called something like:

`application/x-openoffice-objectdescriptor-xml;windows_formatname="Star Object Descriptor (XML)";classname="47BBB4CB-CE4C-4E80-a591-42d9ae74950f";typename="LibreOffice 7.2 Spreadsheet";displayname="file:///home/tml/Documents/u1.ods";viewaspect="1";width="2258";height="1807";posx="0";posy="0"`

(Yes, that whole thing is the _name_ ("MIME type") of a format of data on the clipboard...)

On macOS, the the terminology is a bit different (you have _types_ on the _pasteboard_, not formats on the clipboard), but anyway, the corresponding type name is only:

`application/x-openoffice-objectdescriptor-xml;windows_formatname="Star Object Descriptor (XML)"`

i.e. the extra parameters or whatever they should be called are missing. Specifically, the "typename" one, which it seems that the code actually looks for and needs. See ImplSetParameterString() in vcl/source/treelist/transfer.cxx which checks if there is a "typename" and in that case sets the rObjDesc.maTypeName, and then lcl_TestFormat() in sc/source/ui/view/cellsh.cxx which sets aStrVal = aDesc.maTypeName; and then behaves slightly differently if aStrVal is empty.

If I can figure out how to get the additional stuff added to the clipboard format (i.e. pasteboard type) name string also on macOS, and on iOS, hopefully things will work better.

**Comment by tml1024** [comment] 2021-01-14 01:15
Fixing this will be done with several freestanding commits in core, to keep them easy to review. The first one is at https://gerrit.libreoffice.org/c/core/+/109254 . More will follow later, mainly to vcl.

**Comment by tml1024** [comment] 2021-01-15 14:09
With https://gerrit.libreoffice.org/c/core/+/109368 the problem is now fixed for an app built from the master branches. Now back-porting to the cp-6.4 branch.

**Comment by tml1024** [comment] 2021-01-15 16:24
Back-port done, fix will be available in an app build next week.

**Closed** 2021-01-18 08:27 UTC
Labels: bug, ios-app
