### ISSUE TITLE
Selfhosted grammar check does not work

### ISSUE THREAD

**Issue by sedric** [CollaboraOnline/online#5016] opened 2022-07-14 10:40 UTC
**Describe the bug**
Since 22.05.03 it is [advertised](https://www.collaboraoffice.com/press-releases/code-22-05-released-with-powerful-new-features-like-grammar-checks-sparklines-and-jumbo-spreadsheets/) that CODE support grammar check with LanguageTool.

But it seem it doesn't work, at least with selfhost coolwsd and LT HTTP Server (I installed them on the same host).

No request at all is made to LT HTTP Server.

**To Reproduce**
1. Configure coolwsd to enable LT : 
```
  <enabled desc="Enable LanguageTool Remote Grammar Checker" type="bool" default="false">true</enabled>
  <base_url desc="Http endpoint for the LanguageTool API server, without /check or /languages postfix at the end.\
" type="string" default="https://sub.domain.tld/lt/"/>
```
2. Restart coolwsd
3. Start LT server : `java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8082 --allow-origin '*' --public`
4. Open a document from Nextcloud wich contain errors (checked via local LT from desktop install)

**Expected behavior**
LanguageTool indicate grammatical errors

**Actual behavior**
It does not.
There is no log on the proxy, LTHTTPServer and coolwsd (even with debug logs).

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Firefox ESR, Chromium
 - Version: 91 (FFESR) / 102 (Chromium)

**Server**
- OS: Devuan Chimaera (like Debian 11 Bullseye)
- CooL version: 22.05.3-1, 22.05.4-1 (can reproduce on both) from APT repository (not docker)
- LT version: 5.7 with OpenJDK 11.0.15 2022-04-19

**Additional context**
The `base_url` setting as been tested with both local hostname (http://localhost:8081) and external (http://sub.domain.tld/tl/ and https://sub.domain.tld/lt/) because it's not clear if it's a server connection (and we don't need to expose the API for the rest of the world) or a client connection (and LT should be world accessible).
I also tried to write it in the following form :
1. `<base_url desc="Http endpoint for the LanguageTool API server, without /check or /languages postfix at the end.\
" type="string" default="http://localhost:8081"/>`
2. `<base_url desc="Http endpoint for the LanguageTool API server, without /check or /languages postfix at the end.\
" type="string" default=""/>http://localhost:8081</base_url>`

Here is my infrastructure schema :
```
          domain.tld (NC)         cloud.local
          sub.domain.tld         +-----------------------------------+
           (CooL  / LT)          | Nextcloud:80                      |
            +--------+           |   (through Apache)                |
            |        |           | CooL:9980                         |
            | Proxy  +-----------+   (direct, installed with apt)    |
            |        |           | LanguageTool:8081                 |
            +--------+           |   (direct, manually copied jar)   |
curl sub.domain.tld/lt/v2/ OK    +-----------------------------------+
curl cloud.local:8081      OK     curl cloud.local:8081      OK
Browser throught Nextcloud KO     curl sub.domain.tld/lt/v2/ OK
                                  Browser throught Nextcloud Not tested
```

The Proxy is NGinx and the configuration bloc used for LT is : 
```
proxy_redirect          off;
proxy_set_header        Host            $host;
proxy_set_header        X-Real-IP       $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
client_max_body_size    10m;
client_body_buffer_size 128k;
proxy_connect_timeout   90;
proxy_send_timeout      90;
proxy_read_timeout      90;
proxy_buffer_size   16k;
proxy_buffers       32   16k;
proxy_busy_buffers_size 64k;

location ~* ^/lt/(.*)
  {
    proxy_pass http://cloud.local:8081/$1$is_args$args;
  }
```

Curl test is : `curl -d "language=en-US" -d "text=a simple tes" $host/v2/check`

I've tried : 
- From local machine through localhost and proxy
- From proxy to the server port and throught proxy
- From a client throught the proxy

So I am 100% sure that the Proxy/LT side is ok and that it's a CooL problem. I tried asking [on the forum](https://forum.collaboraonline.com/t/configure-grammar-check/1216/4) to be sure it's not a misconfiguration from me and they said it's not so maybe a bug request is a better option.

Is there anything I can do to provide more help to track this ?

**Comment by merttumer** [comment] 2022-07-18 10:00
I think the BaseURL config name is misunderstood and without needing the postfix at the end. Probably we need to update that so it will be more clear. You need to add /v2 to the baseurl. see: https://github.com/CollaboraOnline/online/blob/master/coolwsd.xml.in#L14 it has /v2 at the end so your url should look like that. Can you please try it with /v2 at the end? 

Thank you for creating the issue

**Comment by sedric** [comment] 2022-07-19 09:20
I just did and it change nothing, but it was expected : even with this mistake, I should have logs pointing to errors as the domain part of the URL is good. But I have no trace of any request to sub.domain.tld/lt/ from the browser inspector, in the proxy log, in coolwsd logs or in LT HTTP Server.

As if COOL does not even TRY to use LT.

**Comment by pedropintosilva** [comment] 2022-07-21 08:44
hm, I would expect 'languagetool' string to popup in the logs every time when the XML has it switch on, right @merttumer or am I wrong here?

**Comment by pedropintosilva** [comment] 2022-09-27 14:39
@brknkfr I have put together a step by step page, it is now together with all the other info in the SDK : https://sdk.collaboraonline.com/docs/language_tool.html

**Comment by brknkfr** [comment] 2022-09-27 15:53
I have already checked the SDK documentation. My self-hosted languagetool server is working fine with the Firefox add-on and with the newest LibreOffice, the grammar checking is working fine with the self-hosted server, but somehow, coolwsd is not working (base_url entered correctly, with or without SSL validation). There is no connection from coolwsd to the languagetool server happening. How to debug further?

**Comment by brknkfr** [comment] 2022-11-10 15:58
What more info is needed? Language checking is still not working with the latest version 22.05.8.2.

**Comment by sedric** [comment] 2022-11-18 16:57
As brknkfr, I confirm it still not work, and the same as they do : what more info do you need ?

I gave you configuration from NGinx, Coolwsd (in which you can see that I followed the documentation you link, I tell you how I test, I made a schema of the infrastructure used to be sure there is no misscomprehension. There is **nothing** in the logs.

If you need more intels, please, provide us a way for doing it or AT LEAST, tell us what is missing. I'm a sysadmin, not a C++/JS dev, I can't just read the code to figure it out.

**Comment by aukfood** [comment] 2023-04-21 08:22
Hello, I have the same problems, I have my own languagetool server online and it's works with curl request 
```
curl -d "text=je mappelle guillaume." -d "language=fr-FR" https://languagetool.mydomain.com//v2/check
{"software":{"name":"LanguageTool","version":"6.1","buildDate":"2023-04-04 07:15:59 +0000","apiVersion":1,"premium":false,"premiumHint":"You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.","status":""},"warnings":{"incompleteResults":false},"language":{"name":"French","code":"fr","detectedLanguage":{"name":"French","code":"fr","confidence":0.9999968,"source":""}},"matches":[{"message":"Cette phrase ne commence pas par une majuscule.","shortMessage":"","replacements":[{"value":"Je"}],"offset":0,"length":2,"context":{"text":"je mappelle guillaume.","offset":0,"length":2},"sentence":"je mappelle guillaume.","type":{"typeName":"Other"},"rule":{"id":"UPPERCASE_SENTENCE_START","description":"Absence de majuscule en début de phrase","issueType":"typographical","category":{"id":"CASING","name":"Majuscules"}},"ignoreForIncompleteSentence":true,"contextForSureMatch":-1},{"message":"Un verbe conjugué semble plus approprié.","shortMessage":"","replacements":[{"value":"m'appelle"},{"value":"appelle"},{"value":"rappelle"},{"value":"capelle"},{"value":"capèle"}],"offset":3,"length":8,"context":{"text":"je mappelle guillaume.","offset":3,"length":8},"sentence":"je mappelle guillaume.","type":{"typeName":"Other"},"rule":{"id":"JE_VERBE","subId":"1","sourceFile":"grammar.xml","description":"je + verbe","issueType":"uncategorized","category":{"id":"CAT_GRAMMAIRE","name":"Grammaire"}},"ignoreForIncompleteSentence":true,"contextForSureMatch":5}],"sentenceRanges":
```

My configuration in coolwsd : 
```
   <languagetool desc="LanguageTool Remote API settings for grammar checking">
          <enabled desc="Enable LanguageTool Remote Grammar Checker" type="bool" default="false">true</enabled>
        <base_url desc="Http endpoint for the LanguageTool API server, without /check or /languages postfix at the end." type="string" default="">https://languagetool.mydomain.com/v2</base_url>
        <user_name desc="LangueTool account username for premium usage." type="string" default=""></user_name>
      <api_key desc="Api key provided by LanguageTool account for premium usage." type="string" default=""></api_key>
   </languagetool>
   ```
   
   But in my collabora I have not grammatical correction :(

**Comment by LofiTurtle** [comment] 2023-07-15 07:46
I have the same issue. I am running the CODE docker image, using the "extra_params" environment variable to enable LanguageTool, i.e. `-e "extra_params=--o:languagetool.enabled=true --o:languagetool.base_url=https://languagetool.example.com/v2"`. There are no logs in the CODE container referencing LanguageTool, and no logs from the LanguageTool server indicating any requests are being made to it. The document UI also shows no underlining of grammar errors, just like if LanguageTool was never enabled.

My self-hosted LanguageTool server runs behind a reverse proxy, and it works correctly when accessed using curl through localhost and through the public URL, as well as when using the LanguageTool browser addon. The only issue is with the collabora integration.

What information can I provide to help fix this issue?

**Comment by brknkfr** [comment] 2023-08-09 11:37
Still not working with version 23.05.2.2.

**Comment by Nitrousoxide** [comment] 2023-08-09 11:44
> My self-hosted LanguageTool server runs behind a reverse proxy, and it works correctly when accessed using curl through localhost and through the public URL, as well as when using the LanguageTool browser addon. The only issue is with the collabora integration.

I also am getting corrections back using the browser plugin when I set a manual self-hosted url for it but do not get back any corrections with collabora like I demonstrated above.

See the screenshots

![image](https://github.com/CollaboraOnline/online/assets/1363931/b95db1d3-c855-422c-803f-7ee8ad9b1476)

![image](https://github.com/CollaboraOnline/online/assets/1363931/538f1f14-00df-4cb9-a196-180b94f444c1)

It really seems like it's something to do specifically with collabora itself and no other possible point of failure.

**Comment by Nitrousoxide** [comment] 2023-08-09 12:38
> Still not working with version 23.05.2.2.

Seems to be working for me now with Language Tool 6.1 and Collabora [23.05.2.2.1]:

![image](https://github.com/CollaboraOnline/online/assets/1363931/d15f2c69-29b3-4b3e-ad47-eddfc9924129)

**Comment by LofiTurtle** [comment] 2023-08-11 18:48
LanguageTool support is also working for me after updating to the `23.05.2.2` CODE docker image.

**Comment by sedric** [comment] 2023-08-16 12:17
> Seems to be working for me now with Language Tool 6.1 and Collabora [23.05.2.2]:
> 
> [image]

This is not language tool, but the base LibreOffice spellcheck (hunspell). LanguageTool do way more than that.

It still doesn't work with CODE 23.05.2-2 (deb) + Nextcloud 27.0.2 with 8.1.1 app + LT 6.2.

Again, there is no log **AT ALL**. We should _at least_ see a connection on LT side when we launch it in foreground. Example of what I got with the curl line documented in my bug report :

> 2023-08-16 14:10:01.797 UTC+02:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
> 2023-08-16 14:10:07.663 UTC+02:00 INFO  org.languagetool.server.TextChecker Check done: 12 chars, en-US, requestId: null, #1, null, 0/1 matches, 5819ms, agent:-, sent, q:0, h:1, dH:1, r:1, m:all, premium: false
> 2023-08-16 14:10:07.664 UTC+02:00 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 5905ms; sending code 200

Trying to load/modify a document full of errors with all configurations mentioned in bug report did nothing at all.

**Comment by Nitrousoxide** [comment] 2023-08-16 12:58
> This is not language tool, but the base LibreOffice spellcheck (collaboraoffice-dict-* packages). LanguageTool do way more than that and you'll see blue waves, not red ones.
> 
> It still doesn't work with CODE 23.05.2-2 (deb) + Nextcloud 27.0.2 with 8.1.1 app + LT 6.2.
> 
> Again, there is no log **AT ALL**. We should _at least_ see a connection on LT side when we launch it in foreground. Example of what I got with the curl line documented in my bug report :

I'm sorry it's not working for you, but I am 1000% get corrections back from my self-hosted LanguageTool.  This is not the internal LibreOffice spellcheck.  The squiggly line is yellow, not blue BTW.

The blank agent logs are from the collabora server I'm 99%

```
2023-08-16T12:51:02.538999673Z 2023-08-16 12:51:02.538 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 78ms; sending code 200
2023-08-16T12:51:02.552083507Z 2023-08-16 12:51:02.552 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-08-16T12:51:02.620956175Z 2023-08-16 12:51:02.620 GMT INFO  org.languagetool.server.TextChecker Check done: 54 chars, en-US, requestId: null, #63858, null, 0/2 matches, 68ms, agent:-, sent, q:0, h:1, dH:1, r:66813, m:all, premium: false
2023-08-16T12:51:02.620986862Z 2023-08-16 12:51:02.620 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 68ms; sending code 200
2023-08-16T12:51:02.668558496Z 2023-08-16 12:51:02.668 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-08-16T12:51:02.743767098Z 2023-08-16 12:51:02.743 GMT INFO  org.languagetool.server.TextChecker Check done: 55 chars, en-US, requestId: null, #63859, null, 0/2 matches, 75ms, agent:-, sent, q:0, h:1, dH:1, r:66814, m:all, premium: false
2023-08-16T12:51:02.743806532Z 2023-08-16 12:51:02.743 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 75ms; sending code 200
2023-08-16T12:51:02.825688012Z 2023-08-16 12:51:02.825 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-08-16T12:51:02.882693266Z 2023-08-16 12:51:02.882 GMT INFO  org.languagetool.server.TextChecker Check done: 56 chars, en-US, requestId: null, #63860, null, 0/3 matches, 57ms, agent:-, sent, q:0, h:1, dH:1, r:66815, m:all, premium: false
2023-08-16T12:51:02.882734844Z 2023-08-16 12:51:02.882 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 57ms; sending code 200
2023-08-16T12:51:03.124530584Z 2023-08-16 12:51:03.124 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-08-16T12:51:03.172842935Z 2023-08-16 12:51:03.172 GMT INFO  org.languagetool.server.TextChecker Check done: 57 chars, en-US, requestId: null, #63861, null, 0/3 matches, 48ms, agent:-, sent, q:0, h:1, dH:1, r:66816, m:all, premium: false
2023-08-16T12:51:03.172874494Z 2023-08-16 12:51:03.172 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 48ms; sending code 200
2023-08-16T12:51:11.649475436Z 2023-08-16 12:51:11.649 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-08-16T12:51:11.712220912Z 2023-08-16 12:51:11.712 GMT INFO  org.languagetool.server.TextChecker Check done: 13 chars, en-US, requestId: null, #63862, null, 0/1 matches, 63ms, agent:-, sent, q:0, h:1, dH:1, r:66817, m:all, premium: false
2023-08-16T12:51:11.712251149Z 2023-08-16 12:51:11.712 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 63ms; sending code 200
2023-08-16T12:51:41.116807353Z 2023-08-16 12:51:41.116 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-08-16T12:51:41.116874039Z 2023-08-16 12:51:41.116 GMT INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-08-16T12:51:41.116992582Z 2023-08-16 12:51:41.116 GMT WARN  org.languagetool.language.identifier.DefaultLanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en]
2023-08-16T12:51:41.117095796Z 2023-08-16 12:51:41.117 GMT WARN  org.languagetool.language.identifier.DefaultLanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en]
2023-08-16T12:51:41.157714074Z 2023-08-16 12:51:41.157 GMT INFO  org.languagetool.server.TextChecker Check done: 12 chars, it (mother tongue: en)[auto], requestId: null, #5, null, 0/0 matches, 41ms, agent:webextension-chrome-ng, version: 7.1.8, sent, q:0, h:2, dH:1, r:66819, m:tlo, premium: false
```

![image](https://github.com/CollaboraOnline/online/assets/1363931/e9a2d265-3a84-4e7d-af60-a9b9286e4469)

**Comment by sedric** [comment] 2023-08-16 13:30
Hoooo ! I did not see the yellow one, sorry (it's almost white on my screen :().

So I made more test and this is weirder. My test document is in french (my native language) and I have spellcheck but no grammar check. Creating an english test document with LT and I don't even have spellcheck but as soon as LT is disabled, it work (as documented in #6477). So maybe it's not the same thing at all.

I'll do more testing.

**Comment by S0ulf3re** [comment] 2023-12-02 01:35
I would like to confirm that I am also having this issue with Nextcloud 27.1.4 and Collabora 23.05.5.4. Both in Docker

**Comment by brknkfr** [comment] 2023-12-13 13:30
It seems that with Nextcloud 27.1.4 and the newes Collabora 23.05.6.2 the selfhosted grammar indeed does work. I had to to a clean install before it worked. Can we close the issue?

**Comment by S0ulf3re** [comment] 2023-12-13 20:04
When will this version be made available as a docker image?

**Comment by timur-g** [comment] 2024-01-27 10:27
Some folks here confirmed it works. It also works with https://hub.docker.com/r/collabora/languagetool
I think this could be closed. If this does not work for someone, please explain.

**Closed by timur-g** 2024-01-27 10:27 UTC
Labels: bug, 22.05.x
