### ISSUE TITLE
CODE 6.4.10: Major Performance Regression Opening And Closing Calc Sheets

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2745] opened 2021-07-03 09:20 UTC
**Describe the bug**
It seems that CODE 6.4.10 introduced a major performance regression when opening / closing Calc sheets, which basically renders it unusable for me - and I'm not exaggerating.

I'm frequently using a Calc sheet which has four tabs with about 400 rows and a dozend columns each, and one additional smaller tab - so it's actually not that big.

Opening the sheet now takes about 30 seconds (!) and closing it about 35 seconds (!) every time(!).

That's more than slightly annoying if you have to open / close it more than once in a fortnight...

For the following demonstration / screencast I also added a nearly empty new tab so no sensitive information is shown. It's opened by default, so apparently the massive delay is not directly caused by the tab which is displayed - no idea what CODE's doing there.

While CODE is frozen, the browser uses 100% CPU on one core. The performance monitor's values shown in the screencast are a bit skewed due to the screen recording which is also running - without recording the screen, the CPU usage flowing into Chromium during this period is even more clearly visible, and I measured the delays stated above without any screen recording running, and without any significant background activity on my system.

Unfortunately, I cannot upload the Calc sheet directly, as it contains personal / sensitive data. I'd assume it will probably be obvious to find where the time is spent, but in case it's not and you cannot reproduce, I will try to create an anonymized test case - but this also may take time...

**To Reproduce**
1. See screencast

**Expected behavior**
The Calc sheet can be opened and closed in <= 5 seconds as with CODE 6.4.9 and lower.

**Actual behavior**
The Calc sheet takes more than 30 seconds to open AND also to close each.

**Screenshots**
![CODE-6 4 10-Calc-Open-Close-Sheet-Performance-reduced](https://user-images.githubusercontent.com/26199042/124349556-e88aa880-dbef-11eb-9de2-d88ad453107c.gif)

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 (KDE neon)
 - Browser: Chromium
 - Version: 91.0.4472.101 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

Collabora Online Development Edition (CODE)
Diese Version von Collabora Online Development Edition (CODE) wird bereitgestellt von

LOOLWSD
6.4.10 (git hash: 51b8716)
Angeboten von: ee7c0e28
LOKit
Collabora Office 6.4-42 (git hash: 8aa76ce)
"Ubuntu 18.04.5 LTS"
Copyright © 2021, Collabora Productivity Limited.

**Comment by gohrner** [comment] 2021-07-03 09:53
Ok, just creating a new sheet with a smiliar number of tabs, rows, and columns unfortunately is not sufficient to provoke this behaviour. :-(

I don't have much experience with JavaScript and especially JavaScript debugging, but I think I was able to find the profiler in the Chromium Developer Tools:

![image](https://user-images.githubusercontent.com/26199042/124350467-305ffe80-dbf5-11eb-9758-6dbb289a09c9.png)

Looks like further cell comment related issues to me - those seem to be a rather fragile area in CODE Calc. :-(

**Comment by thebearon** [comment] 2021-07-05 02:14
I think I can reproduce this with the following sample:
https://bugs.documentfoundation.org/attachment.cgi?id=173354
(from https://bugs.documentfoundation.org/show_bug.cgi?id=140866 )

The slowness isn't that bad, but certainly noticeable. Strangely, I'm not getting the same slowness in a local build.

**Comment by mmeeks** [comment] 2021-07-05 13:43
Wow - this is a really cool bug report =) Thanks gohrner ! =) looks like there are a lot of comments in your document and (somehow) we're doing something silly related to those.

**Comment by mmeeks** [comment] 2021-07-05 15:21
Gokay - I suspect this is easy enough to fix - bu avoiding all of the reNewAllSections bounds calculation etc. for every single comment that is added: particularly are they are then all hidden again afterwards ;-)

		if (this.sectionProperties.docLayer._docType === 'spreadsheet')
			this.hideAllComments(); // Apply drawing orders.

I wonder if we could create / push the comments hidden instead by re-working: CommentSection.importComments - and so avoid lots of this work quite trivially ?

Otherwise I assume some freeze/thaw on section calculation might be a good idea.

Thanks!

**Comment by gokaysatir** [comment] 2021-07-06 08:59
Hello, thank you for this detailed bug report and all comments.

We have a patch waiting to be merged for this issue. I hope we will solve this in a short while.

**Comment by gokaysatir** [comment] 2021-07-12 09:10
Hello,

We now have a PR merged into co-6-4 branch.

https://github.com/CollaboraOnline/online/pull/2776

Thank you for this report.

**Closed by gokaysatir** 2021-07-12 09:10 UTC
Labels: bug, unconfirmed
