### ISSUE TITLE
Paragraph formatting is not saved in certain languages in Writer

### ISSUE THREAD

**Issue by gmasei11** [CollaboraOnline/online#5034] opened 2022-07-18 11:49 UTC
**Describe the bug**
For a document opened with parameter "lang=de-DE" the paragraph format changes are not saved and, after the document is reloaded, the paragraph format is the default one for previously changed characteristics.

**To Reproduce**
1. Open a document
2. Select entirely a paragraph
3. Change font size or text alignment or any other format setting
4. Save the document
5. Reload the document
6. The format changes are lost

**Expected behavior**
After reloading the format changes should be preserved

**Actual behavior**
After reloading the paragraph's format changes are lost and it seems that the default values are used.

**Screenshots**

https://user-images.githubusercontent.com/73231749/179501843-a8267e0f-e73f-4059-8949-b4488abb4d7f.mp4

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04.4 LTS
 - Browser: Chrome
 - Version: 103.0.5060.114 (Official Build) (64-bit)

**Additional context**

- Tested with en-US, de-DE, fr-FR and es-ES and only with de-DE can be reproduced.
- It seems that the reference to the automatic style is lost:

![automatic_style_is_lost](https://user-images.githubusercontent.com/73231749/179503759-8391f7c4-6003-492f-b5bc-48af387b5484.jpg)

**Comment by gmasei11** [comment] 2022-07-21 08:57
The issue was generated by the changing of document language from the current one to English and back just for save operation. This triggered a mismatch of style names and the reference to the automatic style that contained format information was lost.
The issue was fixed in 21 by reverting the problematic commit: https://github.com/LibreOffice/core/commit/900891c3b42e80e8d3970fd5fc02b67022ae3795 . But for some reason the fix was not applied for 22.

Should we revert the problematic commit also in 22 ?

**Comment by Ezinnem** [comment] 2022-07-21 09:16
I tested using a similar build and with the parameter "lang=de-DE"

COOLWSD version:
22.05.4.1 git hash: [66c53864](https://github.com/CollaboraOnline/online/commits/66c53864)

https://user-images.githubusercontent.com/54344301/180177262-a320949a-b535-41e2-a7bf-579d163c3b0d.mp4

**Comment by thebearon** [comment] 2022-07-21 11:02
I managed to reproduce it by creating a new document in LibreOffice (in English language), then opening it in COOL in German language, and following the steps outlined by @gmasei11.

This seems to be a regression from https://github.com/LibreOffice/core/commit/4b7b449bbdc51557f62131a3b467b34ad39e8547 in 22.05. This commit is the second iteration after https://github.com/LibreOffice/core/commit/f4ef1e3e580f7a590496d62aaa3dc7e092510a9c in 21.11 (which got reverted), both an attempt at solving the following issue:
- open a document,
- open the same document in the same session in a different UI language (eg. first in English, second in German),
- try saving the document from the second view.

-> Saving will fail.
(this bug seems to have started occurring after https://github.com/LibreOffice/core/commit/8ddd66a36e5e54291e56c1a5804d5db3b1ba16bb )

**Comment by mmeeks** [comment] 2022-07-23 09:28
Hmm - I'm surprised these three steps cause grief - I would really think that switching back to the load-time locale would solve this. Was there any editing between them from the new view? - makes me wonder if the 2nd fix is broken.

Ash - why is 'setLoadLanguage' implemented but never called ? in the current state it -looks- like a complicated way of continuing to switch back to en-US to save ?

@gmasei11 - any chance you can try calling 'setLoadLanguage' at some suitable place after our load occurs ? =) might do the trick.

Thanks!

**Comment by Ashod** [comment] 2022-07-24 12:53
Thanks @gmasei11 for the report and the helpful screencast! A fix is available for review: https://gerrit.libreoffice.org/c/core/+/137391

**Comment by gmasei11** [comment] 2022-07-25 07:43
@Ashod @mmeeks I've tested the patch and it seems that it fixes the issue. Thanks!

I've cherry-picked the https://github.com/LibreOffice/core/commit/4b7b449bbdc51557f62131a3b467b34ad39e8547 patch in 21 and mixed with Ash's patch and it seems to work. Is it OK to backport these two patches to 21 too ? Are there any reasons not to do it ? If not then I can do that myself after Ash's patch will be merged.

**Comment by mmeeks** [comment] 2022-07-25 11:26
Please do back-port to 21 =) good stuff!

**Comment by Ashod** [comment] 2022-07-25 12:12
Fantastic, @gmasei11, thanks for the confirmation! Feel free to close this ticket if nothing further is need. Thanks!

**Comment by thebearon** [comment] 2022-07-25 19:57
> @Ashod @mmeeks I've tested the patch and it seems that it fixes the issue. Thanks!
> 
> Are there any reasons not to do it ?

If we can be fairly sure now there won't be further regressions, this could be backported. Or we could wait a few weeks after the release of 22.05, and backport then if nothing comes up.

**Comment by gmasei11** [comment] 2022-07-29 05:34
Since the backported patches were accepted I will close this issue. If there will be any regressions we'll open separate issues and link to this one. Thanks everyone for help!

**Closed** 2022-07-29 05:35 UTC
Labels: bug, regression, core
