### ISSUE TITLE
Admin console broken in loolwsd 6.4.10 (with Apache 2.4.48, but not with 2.4.38)

### ISSUE THREAD

**Issue by thkoch2001** [CollaboraOnline/online#2910] opened 2021-07-19 12:37 UTC
The bug is described here:
https://forum.collaboraonline.com/t/websocket-connection-to-admin-console-adminws-is-failing/475

Duplicate issue:
https://forum.collaboraonline.com/t/code-cannot-launch-admin-console-after-update/477

TL;DR:
- Error message: “Server has been shut down; please reload the page.”
- websocket connection failing
- log: `Admin::handleInitialRequest bad request| wsd/Admin.cpp:378`
- This if should be true but isn't:
  `if (request.find("Upgrade") != request.end() && Util::iequal(request["Upgrade"], "websocket"))`
- This commit touched the line recently: https://github.com/CollaboraOnline/online/commit/54a10729f3b5ac5913a051a0b810214e30a5b83a

**Comment by thkoch2001** [comment] 2021-07-21 21:39
This expression looks unnecessary brittle and complicated:

    request.find("Upgrade") != request.end()

Why not:

    request.has("Upgrade")
?

**Comment by kendy** [comment] 2021-07-29 10:23
@thkoch2001: Thank you for the report!  Please does it happen also with the 6.4.10-6 that has been released 2 days ago?  Thank you in advance!

**Comment by thkoch2001** [comment] 2021-07-29 10:25
Yes, I updated yesterday and confirmed the issue also with 6.4.10-6.

**Comment by thebearon** [comment] 2021-07-30 02:39
@thkoch2001 would you be able to capture the exact HTTP request that is sent when opening the admin console? I didn't see an error with a terminating reverse proxy setup, but the request could possibly be analyzed.

**Comment by thkoch2001** [comment] 2021-07-30 16:52
I confirmed with Apache module [dumpio](https://httpd.apache.org/docs/current/mod/mod_dumpio.html) that the Apache server receives this request:

```
GET /lool/adminws/ HTTP/1.1\r\n
Host: collaboraonline.REDACTED\r\n
Connection: Upgrade\r\n
Pragma: no-cache\r\n
Cache-Control: no-cache\r\n
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/REDACTED (KHTML, like Gecko) Chrome/REDACTED Safari/REDACTED\r\n
Upgrade: websocket\r\n
Origin: https://collaboraonline.REDACTED\r\n
Sec-WebSocket-Version: 13\r\n
Accept-Encoding: gzip, deflate, br\r\n
Accept-Language: de,en-US;q=0.9,en;q=0.8,ro;q=0.7\r\n
Sec-WebSocket-Key: L9REDACTEDA==\r\n
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n
\r\n
```

I don't know how to check the request that Apache is sending to loolwsd. Is the incoming request maybe included in trace logs in loolwsd?

Meanwhile a colleague compiled 44848c33 (two commits ahead of my version) and on his server the admin console works. If there wouldn't be the other user who reported the same bug, I'd feel dump now.

We noticed though that the colleague uses Apache from Debian stable (2.4.38) and I use backports (2.4.48). I see just two [changes](https://sources.debian.org/src/apache2/2.4.48-3.1/CHANGES/) to websockets between these versions in Apache:

- 2.4.48 mod_proxy_wstunnel: Add ProxyWebsocketFallbackToProxyHttp to opt-out the fallback to mod_proxy_http for WebSocket upgrade and tunneling.
- mod_proxy_wstunnel: Fix websocket proxy over UDS. PR 62932

I don't use Unix Sockets and I also set [ProxyWebsocketFallbackToProxyHttp](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html#proxywebsocketfallbacktoproxyhttp) to Off to rule this one out.

Otherwise the colleague uses SSL between Apache and loolwsd and I don't.

**Comment by thkoch2001** [comment] 2021-07-30 19:25
Detailed logs from the Apache server for the /lool/adminws request:

```
proxy_util.c(2455): AH00943: http: has released connection for (127.0.0.1)
AH01964: Connection to child 392 established (server collaboraonline.REDACTED:443)
mod_proxy.c(686): AH03461: attempting to match URI path '/lool/adminws/' against prefix '/loleaflet' for proxying
mod_proxy.c(686): AH03461: attempting to match URI path '/lool/adminws/' against prefix '/hosting/discovery' for proxying
mod_proxy.c(686): AH03461: attempting to match URI path '/lool/adminws/' against prefix '/hosting/capabilities' for proxying
mod_proxy.c(686): AH03461: attempting to match URI path '/lool/adminws/' against pattern '/lool/(.*)/ws$' for proxying
mod_proxy.c(686): AH03461: attempting to match URI path '/lool/adminws/' against prefix '/lool' for proxying
mod_proxy_wstunnel.c(35): check_trans fallback
mod_proxy.c(780): AH03464: URI path '/lool/adminws/' matches proxy handler 'proxy:http://127.0.0.1:9980/lool/adminws/'
mod_proxy_wstunnel.c(72): canon fallback
mod_proxy_http.c(98): HTTP: canonicalising URL http://127.0.0.1:9980/lool/adminws/
proxy_util.c(2246): http: found worker http://127.0.0.1:9980/lool for http://127.0.0.1:9980/lool/adminws/
mod_proxy.c(1260): AH01143: Running scheme http handler (attempt 0)
mod_proxy_wstunnel.c(340): handler fallback
mod_proxy_http.c(1875): HTTP: serving URL http://127.0.0.1:9980/lool/adminws/
proxy_util.c(2440): AH00942: http: has acquired connection for (127.0.0.1)
proxy_util.c(2495): AH00944: connecting http://127.0.0.1:9980/lool/adminws/ to 127.0.0.1:9980
proxy_util.c(2718): AH00947: connected /lool/adminws/ to 127.0.0.1:9980
proxy_util.c(3153): http: fam 2 socket created to connect to 127.0.0.1
proxy_util.c(3187): AH02824: http: connection established with 127.0.0.1:9980 (127.0.0.1)
proxy_util.c(3371): AH00962: http: connection complete to 127.0.0.1:9980 (127.0.0.1)
mod_proxy_http.c(1198): Status from backend: 400
mod_proxy_http.c(820): Headers received from backend:
mod_proxy_http.c(842): Content-Length: 0
mod_proxy_http.c(842): Server: LOOLWSD HTTP Server 6.4.10
mod_proxy_http.c(842): Date: Fri, 30 Jul 2021 18:41:17
mod_proxy_http.c(1633): start body send
proxy_util.c(2455): AH00943: http: has released connection for (127.0.0.1)
mod_proxy_http.c(1774): end body send
```

**Comment by thkoch2001** [comment] 2021-07-30 20:15
I downgraded Apache from backports (2.4.48) to stable (2.4.38) and now the admin console works.

**Comment by Ashod** [comment] 2021-07-30 21:49
> I downgraded Apache from backports (2.4.48) to stable (2.4.38) and now the admin console works.

Thanks @thkoch2001 for this. Is it safe to assume 6.4.9 worked with 2.4.48?

**Comment by thkoch2001** [comment] 2021-07-31 09:25
Unfortunately I have no information whether COOL 6.4.9 worked with Apache httpd 2.4.48 since I first tried the Admin Console with COOL 6.4.10.

The new Debian stable version with Apache httpd 2.4.48 will be released on August 14th. People who use COOL on the new Debian version will then see a broken Admin console.

Somebody with enough time and knowledge about both systems could script a `git bisect` and find the exact breaking commit of Apache httpd and thus understand where COOL is not playing along with Apache's assumptions. Alternatively, somebody with a good understanding of websockets and the HTTP upgrade mechanism could start from the if statement (see initial issue description) and try to understand why Apache is apparently not forwarding the 'Upgrade: websocket' header.

**Comment by Ashod** [comment] 2021-08-04 15:32
@thkoch2001, I was able to reproduce this issue.

With 2.4.41:
```
GET /lool/adminws/ HTTP/1.1 / Host: localhost:9980 / Connection: Upgrade / Pragma: no-cache / Cache-Control: no-cache / User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 / Upgrade: websocket / Origin: http://localhost:9980 / Sec-WebSocket-Version: 13 / Accept-Encoding: gzip, deflate, br / Accept-Language: en-US,en;q=0.9 / Sec-WebSocket-Key: 9Dxwlli5frEjb+XDB5RvJg== / Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

With 2.4.48:
```
GET /lool/adminws/ HTTP/1.1 / Host: localhost / Pragma: no-cache / Cache-Control: no-cache / User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 / Origin: https://localhost / Sec-WebSocket-Version: 13 / Accept-Encoding: gzip, deflate, br / Accept-Language: en-US,en;q=0.9 / Sec-WebSocket-Key: Z8nZHvm6pw6gRPBRhos/Aw== / Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits / X-Forwarded-For: ::1 / X-Forwarded-Host: localhost / X-Forwarded-Server: 127.0.1.1 / Connection: Keep-Alive
```

Basically, "Connection: Upgrade" is missing from the header with 2.4.48. In fact, the issue is reproducible with 6.4.7 (which is before any changes to the "Upgrade" entry comparison in the code. (Note that I'm using a reverse proxy with ssl-termination, meaning the external connection is with ssl, but loolwsd is running without ssl, but with termination enabled).

Of course this isn't limited to the admin console: I can't load any documents with apache 2.4.48. Can you please confirm whether you are able to load documents with 2.4.48 with reverse proxy?

As far as I can tell, the missing "Connection: Upgrade" header entry is a regression in 2.4.48, as everything works just fine with 2.4.41. Does that make sense for others too, consider the above info?

Thanks!

**Comment by Ashod** [comment] 2021-08-05 09:15
@thkoch2001, https://bz.apache.org/bugzilla/show_bug.cgi?id=65294#c17 suggests that 2.4.48 should have `ProxyWebsocketFallbackToProxyHttp off` that will opt-out of this new logic (see details in that comment), but I wasn't successful in using it. I get the same headers with and without it.

Does it help in your case? Do you see any difference? 

I think that comment explains what is going on, except we are on HTTP 1.1, not 1.0. 

If you confirm that 2.4.48 breaks older releases of Online (as I experience), I think we can have a bug report with Apache and track this down with them (because that would be evidence of a regression on their side).

Thanks again for your help.

**Comment by Ashod** [comment] 2021-08-06 03:58
@thkoch2001, I tried accepting the connection anyway, by removing the condition at https://github.com/CollaboraOnline/online/commit/54a10729f3b5ac5913a051a0b810214e30a5b83a#diff-cf96802684ccb4b0fbc04a7fbb919a7772f9a7f8bf54257f8058f9753fff002fR362 and resuming as normal, but the connection is closed (presumably by the proxy). 

There is nothing I can do to get the connection to work with 2.4.48. I feel we need to open a ticket with Apache and work it out with them.

**Comment by mmeeks** [comment] 2021-09-02 10:22
Lets create an Apache issue - can you chase that @pedropintosilva ? =)

**Comment by pedropintosilva** [comment] 2021-09-09 08:04
> Lets create an Apache issue - can you chase that @pedropintosilva ? =)

hm I fear I do not know enough about this issue to know how to report/explain to the Apache side. Maybe someone that was involved in this ticket report could do a better job (?) @bearon do you think you can take it from here?

**Comment by PhilippeAccorsi** [comment] 2021-09-23 14:29
We have the same problem and not find any solution. Downgrade is not a very good solution because we used Apache on this server also for other services.

**Comment by ebogaard** [comment] 2021-09-24 09:19
It looks like this issue *might* be fixed in httpd 2.4.49: https://downloads.apache.org/httpd/CHANGES_2.4.49
See the section about the mod_proxy infinite loop.

I'm going to test this tomorow.

**Comment by ebogaard** [comment] 2021-10-06 19:48
Yeah, sorry for not reporting back.

2.4.49 didn't fix the issue.

**Comment by mmeeks** [comment] 2021-10-11 12:51
Great news - glad it was not our bug =) lets close this.

**Closed by mmeeks** 2021-10-11 12:51 UTC
Labels: bug

**Comment by xgusto** [comment] 2022-02-03 14:49
I apologize for opening this topic.
I recently installed coolwsd. I got the information [here](https://www.linuxbabe.com/ubuntu/integrate-collabora-onlinenextcloud-without-docker) and [here](https://nocin.eu/nextcloud-installing-collaboraoffice-in-lxc/). I also have a problem with the admin console.
```
Server version: Apache/2.4.52 (Debian)
Server built:   2022-01-03T21:27:14
```
I have described more about my problem [here](https://help.nextcloud.com/t/how-to-set-up-apache-server-for-collabor-online/131722).

**Comment by aukfood** [comment] 2022-05-04 06:21
Hello, I have the same problem with collabora/code in latest docker version with Apache as a proxy

**Comment by pedropintosilva** [comment] 2022-05-04 07:12
Hi @aukfood, maybe better to create another issue (with additional info) since in your case we are talking about [21.11.4.2.1, dc6a61f2a97d](https://hub.docker.com/r/collabora/code/tags) right?
