### ISSUE TITLE
WOPI hosts: Only first domain in each aliasgroup accepted

### ISSUE THREAD

**Issue by vasyugan** [CollaboraOnline/online#7508] opened 2023-10-23 09:03 UTC
### Describe the Bug

I have yesterday received a bug report from a user complaining that Nextcloud office doesn't open for her. After investigating I found that only the primary domain name in each aliasgroup is now recognized, the others are ignored. This used to work just fine until fairly recently. Downgrading to the last collabora 22 makes it work again.

### Steps to Reproduce

1. Have a collabora start script passing  -e 'aliasgroup1=https://cloud.DOMAIN2.org:443,https://cloud.DOMAIN2.org:443,https://cloud.DOMAIN3.org:443' to collabora
2. Click on 'try to open a document first from DOMAIN1, then from DOMAIN2'
3. see it succeed from DOMAIN1 but fail from DOMAIN2
4. See docker container logs -f for the container, you will see the dreaded error message NO accpetable wopi host foud

### Expected Behavior

Should open the document as up to Collabora 22

### Actual Behavior
 Opening the document fails, in the log I see:
No acceptable WOPI hosts found matching the target host 
 ### Additional Context

Server running Ubuntu 22.04, latest docker community edition.

**Comment by labiloute** [comment] 2024-01-11 10:49
Experiencing the same here, unfortunately.

**Comment by SebastianS90** [comment] 2024-01-18 20:05
I probably found the cause: The alias index is missing [when storing the setting](https://github.com/CollaboraOnline/online/blob/cp-23.05.7-3/wsd/COOLWSD.cpp#L3328) but present [when reading it](https://github.com/CollaboraOnline/online/blob/cp-23.05.7-3/wsd/HostUtil.cpp#L126)

**Comment by labiloute** [comment] 2024-03-13 11:23
Hi @SebastianS90 
Did you find a way to workaround this issue ?

**Comment by SebastianS90** [comment] 2024-03-13 12:59
@labiloute Yes. You can either change the [configuration file](https://github.com/CollaboraOnline/online/blob/master/coolwsd.xml.in) or use command line parameters like `--o:storage.wopi.alias_groups[@mode]=groups --o:storage.wopi.alias_groups.group[0].host=https://example.com:443 --o:storage.wopi.alias_groups.group[0].host[@allow]=true --o:storage.wopi.alias_groups.group[0].alias[0]=https://example.net:443`

**Comment by Rash419** [comment] 2024-11-28 14:50
This is fixed with https://github.com/CollaboraOnline/online/pull/10379
CODE 24.04.10.1.1 should work fine : )
Let me know if issue persist

**Closed by Rash419** 2024-11-28 14:50 UTC
Labels: bug, unconfirmed
