### ISSUE TITLE
Options button not working/lack of functionality/dialog in Writer->Format->Sections->Options

### ISSUE THREAD

**Issue by hmeeks-dot** [CollaboraOnline/online#5771] opened 2023-01-27 12:00 UTC
**Describe the bug**
In Writer -> Format -> Sections  
The options button does nothing when triggered

**To Reproduce**
1. Writer and create some text
2. Highlight text and then Insert->Sections
3. Go to Format->Sections->Options
4. See error - nothing happens on button click

**Expected behavior**
Either button to be hidden or another options dialog

**Actual behavior**
Nothing happens

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: chrome
 - Version: 96.0.4664.45 (Official Build) (64-bit)

**Comment by pedropintosilva** [comment] 2023-01-27 13:39
Thanks for reporting it @hmeeks-dot.
I couldn't reproduce this both using master and staging eu (the server we use in our community calls). I also couldn't comprehend what it means ` 96.0.4664.45` is this the version of the  web browser? Could you please paste here the versions that you see when you open the about pop up?

**Comment by hmeeks-dot** [comment] 2023-01-27 13:56
Yes hi,

Sorry that's just the version number I see in the chrome help/about pop up!
: Version 96.0.4664.45 (Official Build) (64-bit)

and strange that you couldn't reproduce that, I'm just using the demo
writer template file - test.docx and I can see the options button but there
is no second dialog coming up for me when I click on it

I've just tried this again with a new blank writer document - I just type
in something random - set it to be a section with the default stuff and
then when I do Format->Sections the sections dialog comes up but then on
that dialog clicking options does nothing for me still...

Not sure if this is just my web version then or what!?

Thanks anyway :)

**Comment by pedropintosilva** [comment] 2023-01-27 14:01
Understood :). So, could you please head over to Help -> About and paste here what you see. For example this is what I see when looking at staging.eu:

COOLWSD version: 22.05.10.0 git hash:  https://github.com/CollaboraOnline/online/commits/048bece8

**Comment by pedropintosilva** [comment] 2023-01-30 10:56
Could you please paste here a screen-record of what you see ? Here is mine (staging eu):


https://user-images.githubusercontent.com/65948705/215458519-fb2e41f3-8b04-4bb2-8341-0f4c66114c87.mp4

**Comment by hmeeks-dot** [comment] 2023-01-30 15:10
Hi

Was a bit confused about your screen recording because it looked like you
didn't click on the sections options button only the sections remove one?...

Here is a screenshot from my side but not much is happening because that's
the problem!
This is also with the console open - it looks like the dialog is just being
deleted after being created and that is why you can't see it...

The section - OPTIONS button should open another dialog which you can see
in normal LO but the dialog is fairly complex the UI files for it are:

openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/modules/swriter/ui/formatsectiondialog.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/modules/swriter/ui/columnpage.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/svt/ui/linewindow.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/svx/ui/colorwindow.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/cui/ui/areatabpage.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/cui/ui/colorpage.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/cui/ui/colorpage.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/cui/ui/imagetabpage.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/modules/swriter/ui/footnotesendnotestabpage.ui",
O_RDONLY) = 23
openat(AT_FDCWD,
"/data/opt/libreoffice/master/instdir/program/../share/config/soffice.cfg/modules/swriter/ui/indentpage.ui",
O_RDONLY) = 23


Thought it could just be an async dialog problem but neither dialog (the
parent Section dlg or child Section-Options) are jsdialogs,

This dialog also works offline so not really sure what is going on here?

Thanks,

hannah

**Comment by Minion3665** [comment] 2023-02-09 10:46
> @Minion3665 or NickWingate would you be interested in looking this up?

Sure! I'd like to take a look

**Comment by hmeeks-dot** [comment] 2023-02-09 11:40
Thanks Pedro!

**Comment by Minion3665** [comment] 2023-02-19 10:23
![image](https://user-images.githubusercontent.com/34243578/219942075-6f0d1fa1-39a8-4b52-be01-c9a014495a08.png)
I've managed to get the dialog rendering 🎉 

As it is a tabbed dialog it needs a little more work to make the tab content render properly, but I'm hoping that it should be relatively straightforward

I decided to convert to a jsdialog too as we would need to do so anyway so there is little point in only fixing the tunneled dialog

**Comment by pedropintosilva** [comment] 2023-02-21 15:54
That's awesome @Minion3665 !

**Comment by pedropintosilva** [comment] 2023-02-27 11:40
https://gerrit.libreoffice.org/c/core/+/147295

**Comment by pedropintosilva** [comment] 2023-06-28 11:36
https://gerrit.libreoffice.org/c/core/+/151188

**Comment by eszkadev** [comment] 2023-07-06 09:49
merged

**Closed by eszkadev** 2023-07-06 09:49 UTC
Labels: bug, core
