### ISSUE TITLE
Continuous View / Web Layout

### ISSUE THREAD

**Issue by panomitrius** [CollaboraOnline/online#7198] opened 2023-09-01 08:06 UTC
I'm looking for a way to edit documents without the text being visually divided as pages (what's usually called Continuous View / Web Layout). Is there such a setting, or is it not implemented yet?

**Comment by Ezinnem** [comment] 2023-09-06 08:52
It may be considered as an enhancement feature for the future.

**Comment by TimMagee** [comment] 2024-07-28 13:38
This is a duplicate of #3154.

**Closed** 2024-08-13 11:29 UTC
Labels: enhancement
