### ISSUE TITLE
Android: LOActivity loading dialog freezes when open file

### ISSUE THREAD

**Issue by AlexeyRybakov** [CollaboraOnline/online#2865] opened 2021-07-14 11:54 UTC
**Describe the bug**

Application is completely frozen with loading dialog. Device reboot is needed to continue use app. Sometimes the device is completely frozen.

**To Reproduce**
1. Open any docx file
2. Try to zoom and scroll a document fast
3. Close activity while document tiles are not completely loaded yet
4. Rapidly open document again

**Expected behavior**

Possibility open and close document multiple times

**Actual behavior**

Application is completely frozen with loading dialog

**Screenshots**

![image](https://user-images.githubusercontent.com/9782701/125615661-324f757f-1918-4181-8352-2045a64e68ab.png)

https://user-images.githubusercontent.com/9782701/125617622-13fd9590-fb66-4e76-951d-7a1c248dc7ff.mp4

**Smartphone**
 - Device: Xiaimi mi 8
 - OS: Android 10 (MIUI 12.0.1)
 - Version: Collabora Office from Google Play 6.4.3

**Additional context**

Note the last messages from logs and loolwsd are  Waiting for LOOLWSD to finish... and LOOLWSD has finished.
It looks like LOOLWSD is not finished properly with last opened document or timing issue with fast reopen.

Logs in attachments:
[logs.log](https://github.com/CollaboraOnline/online/files/6815740/logs.log)
Document to reproduce:
[1626263219953.docx](https://github.com/CollaboraOnline/online/files/6815753/1626263219953.docx)

**Comment by rpear** [comment] 2021-07-15 03:46
For me it happens with other random file types too, I tried ODT, ODP, ODS, DOC as well as DOCX. Also when mine was stuck at Loading... I could exit by clicking the hamburger ||| on the devices toolbar, then clicking 'Close', there was no need to restart the device.  Easy way for me o reproduce on my device (Samsung S8+) :

1. Open any file (no need to enter edit mode, no need to zoom or do anything).
2. Close it.
3. Open any file, 
4. It might hang at Loading...,  if not then Open and Close a few more times.

It is random, a couple of times it worked fine about 6 or seven open/closes, but then I waited 10 seconds or so while closed and tried again and it hung.

**Comment by Ezinnem** [comment] 2021-07-19 07:38
I can reproduce this behavior in the Collabora Office 6.4.9

Online git hash: [69a5739c9](https://github.com/CollaboraOnline/online/commits/69a5739c9)

**Comment by Ezinnem** [comment] 2022-05-02 10:34
This issue seems to have been fixed.

 I cannot reproduce it using Collabora Office app 21.11.3.6 git hash: [eb73aa34](https://github.com/CollaboraOnline/online/commits/eb73aa34)

**Comment by rpear** [comment] 2023-02-11 06:46
@AlexeyRybakov @Ezinnem  This issue seems to have been fixed for me, tested using 21.11.6.1 on a smartphone.  I have been using it before today quite a lot, I just didn't update this ticket. So I would say it is OK to Close/Complete

**Closed** 2024-08-20 11:39 UTC
Labels: bug
