### ISSUE TITLE
Spinfield disappears in Impress on lost focus

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#9797] opened 2024-08-13 15:24 UTC
Collabora Online COOLWSD version: 24.04.6.1 (git hash: d3ae0648), LOKit version: Collabora OfficeDev 24.04.6.1 (git hash: b6e0586)

| Open presentation and select an object (like Shape), see Position and Size |  ![image](https://github.com/user-attachments/assets/936c0c6c-d6cb-4904-a5a7-b62a2415175b)
Click out somewhere else in the slide
| Click again on the object, again open Position and Size, see no spinfield | ![image](https://github.com/user-attachments/assets/a3b698c2-3b4f-4339-bc4a-83ee9eebcab8)

Note: seen when looking #9498, so units are different issue so far.

**Comment by thebearon** [comment] 2024-08-16 22:08
Looks like a regression in 23.05 compared to 22.05.

**Comment by thebearon** [comment] 2024-08-17 00:10
Regression is from the following commit:
https://github.com/CollaboraOnline/online/commit/168f7cde0705861e460593c889766eaf11f2b71b
https://github.com/CollaboraOnline/online/pull/6845
```
Author:     Szymon Kłos <szymon.klos@collabora.com>
AuthorDate: Fri Jul 7 19:28:04 2023 +0200
Commit:     Szymon Kłos <eszkadev@gmail.com>
CommitDate: Tue Jul 11 12:48:28 2023 +0200

    jsdialog: field with time format should be simple edit
```

CC @eszkadev.

**Comment by eszkadev** [comment] 2024-10-22 10:07
seems to be fixed now, I think it was fixed by https://github.com/CollaboraOnline/online/pull/10135

**Closed by eszkadev** 2024-10-22 10:07 UTC
Labels: bug, regression, 23.05, 24.04
