### ISSUE TITLE
Document Cannot be saved Error

### ISSUE THREAD

**Issue by tkaprol** [CollaboraOnline/online#1749] opened 2021-03-17 11:35 UTC
**Describe the bug**
A corrupted file content sent to WOPI Endpoint by LOOLWSD. Despite successful put document requests, one of the put requests went wrong and I lost the actual file content. Originally, there was 20-page length of document content exists on the file before the incident happens.

**To Reproduce**
1. Open the Attached File on any LOOL
2. Make changes on the file
3. Try to save it
2. See the error

**Expected behavior**
The file should be saved correctly

**Actual behavior**
Corrupted file had been generated

**Screenshots**
N/A

**Desktop (please complete the following information)**
 - OS: Any
 - Browser: any
 - Version: Any

**Additional context**
I also tried to open the file on Next Cloud's demo which returns the same error. 

The file can be opened by the Desktop version of LibreOffice. Desktop attempts to recover the file but it displays an empty page. 

[bakalim.odt.zip](https://github.com/CollaboraOnline/online/files/6155933/bakalim.odt.zip)

**Comment by tkaprol** [comment] 2021-04-05 08:58
right, the issue is not recovering the file actually. Actually any fix to prevent that kind of data loss.

**Comment by thebearon** [comment] 2021-04-06 18:13
Do you have the original file and reproducer steps that resulted in this bad file perhaps?

**Comment by Ezinnem** [comment] 2021-08-24 12:03
Closing the issue due to lack of reply.

**Closed by Ezinnem** 2021-08-24 12:03 UTC
Labels: bug, unconfirmed
