### ISSUE TITLE
Ruler: Tab/Indent "Triangles" Appear Along Left Edge of Window

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#7427] opened 2023-10-12 15:12 UTC
### Describe the Bug

Tab/Indent "triangles" sometimes appear wayyy outside the ruler.

### Steps to Reproduce

0. In Writer.
1. Go to "View" Tab.
2. Click "Zoom In" button.
3. Click "Ruler" button.

You can see the Tab/Indent "triangles" outside of ruler, along the very left-edge of window:

![Collabora 23 05 5 1 - Tab Stop Indents in Ruler + Zoom](https://github.com/CollaboraOnline/online/assets/5774324/f9d04b8d-52cf-4681-a5c1-c48df0177ecf)

### Video

[Collabora.23.05.5.1.-.Ruler.Tab.Stop.Triangles.Along.Left.Edge.webm](https://github.com/CollaboraOnline/online/assets/5774324/af25b62f-3efc-4f83-9064-94ac80f645d1)

- 0–7 seconds = Enabling ruler + seeing buggy tab triangles.
- 7–10 seconds = Pressing "Zoom Out" to "correct" the issue.

### Expected Behavior

Every time you open up the Ruler, the Tab Stop triangles should be inside ruler + at proper distances.

### Actual Behavior

When you open the Ruler again, after changing zoom levels, the triangles will appear along left-edge.

### Desktop

- **OS:** Windows 10
- **Browser:** Chrome
- **Version:** Version 117.0.5938.150 (Official Build) (64-bit)

I noticed it in Staging during COOL Weekly Meeting:

> COOLWSD version: 23.05.5.1 (git hash: dffef0e9 (E))
> LOKit version: Collabora Office 23.05.5.1 (git hash: 9f03693)
> Served by: openSUSE Leap 15.5
> Server ID: 3a813eff

and reproduced locally in:

> COOLWSD version: 23.05.4.2 (git hash: 0ba51f81)
> LOKit version: Collabora Office 23.05.4.2 (git hash: b5a7948)
> Served by: Linux Mint 21.1
> Server ID: 78797e84

### Additional Context

This bug only seems to occur when you:

- Change/Reset Zoom levels with the Ruler closed.

Next time you open ruler, the triangles will be along left edge.

If you do not change zooms, then reopen Ruler, the Tab Stop triangles are fine.

**Comment by Ezinnem** [comment] 2023-10-18 10:07
I can confirm this issue. 

It occurs when:
1. The Ruler is not visible
2, The Zoom levels are changed (Zoom in and Zoom out about twice)
3. The Ruler is set to be visible

**Comment by Darshan-upadhyay1110** [comment] 2024-07-15 14:45
> 1. uler i

@Ezinnem this seems to be fixed now. Not reproducible

COOLWSD version: 24.04.5.1 (git hash: 1ecf31df)
LOKit version: Collabora OfficeDev 24.04.5.1 (git hash: e1cfc65)
Served by: Ubuntu 23.10
Server ID: f5be9861

**Closed by Darshan-upadhyay1110** 2024-07-15 14:45 UTC
Labels: bug
