### ISSUE TITLE
Docker Container does not start, if IPv6 is disabled on Server.

### ISSUE THREAD

**Issue by KaeTuuN** [CollaboraOnline/online#4062] opened 2022-01-26 13:22 UTC
**Describe the bug**
Docker Container does not start, if IPv6 is disabled on Server.

**To Reproduce**
`Try: docker run -t -d -p 127.0.0.1:9980:9980 -e "domain=<replaced>" --name=COLLABORAOFFICE --restart always --cap-add MKNOD collabora/code`

**Expected behavior**
Container Starts, maybe warns, that no IPv6 was found.

**Actual behavior**
Doesn't start.
Logfile output from: `docker logs COLLABORAOFFICE | grep -E " ERR|FTL "`
```
wsd-00001-00001 2022-01-26 10:56:04.112373 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/cool_test_mount]| common/JailUtil.cpp:70
wsd-00001-00001 2022-01-26 10:56:04.113305 +0000 [ coolwsd ] ERR  Failed to unmount [/opt/cool/child-roots/]| common/JailUtil.cpp:70
wsd-00001-00001 2022-01-26 10:56:04.114332 +0000 [ coolwsd ] ERR  Failed to bind-mount [/opt/cool/systemplate] -> [/opt/cool/child-roots/cool_test_mount].| common/JailUtil.cpp:47
wsd-00001-00001 2022-01-26 10:56:04.114358 +0000 [ coolwsd ] ERR  Bind-Mounting fails and will be disabled for this run. To disable permanently set mount_jail_tree config entry in coolwsd.xml to false.| common/JailUtil.cpp:209
wsd-00001-00001 2022-01-26 10:56:04.792928 +0000 [ coolwsd ] ERR  Failed to open directory [/usr/bin/browser/welcome] (ENOENT: No such file or directory)| wsd/FileServer.cpp:758
wsd-00001-00001 2022-01-26 10:56:04.801620 +0000 [ coolwsd ] ERR  #-1 Failed set ipv6 socket to 0 (EBADF: Bad file descriptor)| net/Socket.cpp:804
wsd-00001-00001 2022-01-26 10:56:04.801668 +0000 [ coolwsd ] ERR  #-1 Failed to bind to: IPv6 port: 9980 (EBADF: Bad file descriptor)| net/Socket.cpp:811
wsd-00001-00001 2022-01-26 10:56:04.801693 +0000 [ coolwsd ] FTL  Failed to listen on Server port(s) (9980-9980). Exiting.| wsd/COOLWSD.cpp:4155
```
**Screenshots**
none

**Server**
 - OS: Ubuntu Server 20.04 LTS HWE
 - Docker: 5:20.10.12~3-0~ubuntu-focal (via Official PPA)

Greetings

**Comment by thebearon** [comment] 2023-04-05 07:23
Looks like a dupe of #3102.

**Closed by thebearon** 2023-04-05 07:23 UTC
Labels: bug, unconfirmed

**Comment by antonical** [comment] 2023-04-10 11:47
> Looks like a dupe of #3102.

It might be a dupe but clearly nothing has happened to fix this issue.

Cheers
