### ISSUE TITLE
Comments with cyrillic chars

### ISSUE THREAD

**Issue by ptenchik0** [CollaboraOnline/online#5788] opened 2023-01-30 21:35 UTC
**Describe the bug**
Comment with cyrillic characters on selected text didn't save, dialog window just disappear. Plus switching between languages(Alt+Shift) closes dialog window.
But comments with latin characters and digits work fine.

**To Reproduce**
1. Select text
2. Click on 'add comment'
3. Type cyrillic text
4. Hit save button

**Screenshots**
![215080154-79733ba6-0cad-425c-9d04-6a38b73dae27](https://user-images.githubusercontent.com/9156901/215600170-b7e403c5-e44a-4a6a-b101-852fb535f2cb.gif)

**Desktop (please complete the following information)**
 - OS: Ubuntu 22.04.1
 - Browser: FF, Chrome
 - Version: 24.0.4

## Server details
**Operating system**: Ubuntu Linux 20.04.5
**Web server:** Apache
**Database:** MariaDB
**PHP version:** 8.1
**Nextcloud version:** 24.0.4
**Version of the richdocuments app** 6.3.3
**Version of Collabora Online** 22.5.802

**Comment by thebearon** [comment] 2023-01-31 05:55
This is a duplicate of #4732.

**Closed by thebearon** 2023-01-31 05:55 UTC
Labels: bug, unconfirmed
