### ISSUE TITLE
"Read-only" option for the Android app

### ISSUE THREAD

**Issue by Iey4iej3** [CollaboraOnline/online#2831] opened 2021-07-10 13:25 UTC
I also use Collabora to read documents on Android. I hope that it is possible to enable a read-only mode so that simply reading the document does not touch the timestamp and the modifications are not saved unless explicitly permitted by the user.

This is especially useful when the user performed something unexpected. In this case, the file is not polluted if the user decides not to save the modifications.

**Comment by thebearon** [comment] 2021-07-12 01:46
Files on Android already open in read-only mode, you have to tap the pencil icon to switch to edit mode, and if you accidentally do that, tapping on the "<" icon in the top left corner switches back to read-only mode.

**Comment by Iey4iej3** [comment] 2021-07-12 08:30
No, the time stamp is modified even without modification and after tapping "<", at least on version `6.4.9`.

In fact, there was another moment when the app is not properly closed without any modification, the file became unreadable, but I cannot reproduce it now.

**Comment by Ezinnem** [comment] 2021-08-31 12:00
Closing this issue because this seems to be a duplicate of #1372.

**Closed by Ezinnem** 2021-08-31 12:00 UTC
Labels: enhancement, unconfirmed
