### ISSUE TITLE
iOS app: can't use the Emoji keyboard

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#733] opened 2020-11-20 06:40 UTC
**Describe the bug**
On the Apple smart keyboard (attached hardware keyboard) there is a "globe" key in the lower left corner. Using this key, the keyboard selection on the screen pops up. When choosing the "Emoji" keyboard, a dialog pops up on the screen where the user can choose an emoticon which will then be inserted into the text. 

So far this works; however after choosing an emoticon a wrong text input happens - not the emoticon is inserted, but the byte sequence is split up into multiple characters which are inserted (not sure how to explain that better).

**To Reproduce**
1. Open a writer document using the iOS app
2. Push the "globe" key on the attached Apple smart keyboard
3. Use the arrow keys to select the "Emoji" keyboard
4. Choose an emoticon from the list

**Expected behavior**
The chosen emoticon should be inserted into the text.

**Actual behavior**
The multibyte emoticon is instead split up into multiple characters which are inserted into the text

**Screenshots**
![emoticons_split_up](https://user-images.githubusercontent.com/1211300/99767609-9cc53c00-2b03-11eb-844b-62b8981ca359.gif)

**Tablet**
 - OS: iPad OS 14.2
 - Version: 6.4.1 (1)

**Additional context**
This used to work in previous versions of the app.
Maybe one of those bugs and their corresponding commits are useful:
https://bugs.documentfoundation.org/show_bug.cgi?id=128069
https://bugs.documentfoundation.org/show_bug.cgi?id=124350

**Comment by tml1024** [comment] 2020-11-24 08:46
Looking into this now. I think also non-BMP characters and even flags (which actually are two code points) used to work at some time, but this has regressed.

**Comment by mmeeks** [comment] 2020-11-24 11:04
Would be interesting to know what ends up in the hidden text area.
Nicolas - can you tripple click on help->about and select 'Show Clipboard' - and see what shows up in the text area that should become visible as an overlay nearby the cursor =)
Quite possibly the hand-crafted UTF-16 parser we need for IE11 has not had enough testing ;-) cf. TextInput.js getValueAsCodePoints - and would appreciate that.
Also - quite possibly - we need a richer text-input area, that can accept different fonts - I notice some other code around the place can accept font change via the input field (!?) which is a bit of an odd concept, but may be needed - although, clearly transferring any missing fonts from client -> server is a massive can of worms ... hmm =)

**Comment by tml1024** [comment] 2020-11-24 11:26
@mmeeks I am on it already. The handling of non-BMP characters is fairly broken in the code. Confusion between code points and UTF-16 code units etc. Am fixing.

**Comment by tml1024** [comment] 2020-11-24 11:30
The problem is that getValueAsCodePoints(), as its name says, returns an array of integers that are Unicode code points (thus can be larger than 65536, especially for emojis and interesting scripts). Not UTF-16 code units (which are always less than 65536). Still the code uses the JS function fromCharCode() on these numbers. That function expects UTF-16 code units, and it apparently simply truncates the argument to 16 bits.

**Comment by tml1024** [comment] 2020-11-24 13:28
Another bug is that the code tries to convert from a surrogate pair to code point using the expression `code = high + code - 0xdc00 + 0x100000;` The 0x100000 should be 0x10000.

**Comment by nikslor** [comment] 2020-11-24 19:05
Thanks a lot for the improvements @tml1024! 6.4.1 (3) is on par with the functionality we had in older versions!

One remaining issue I see is, that some emoticons are split up into their individual parts so the "male painter" (which is one emotion) becomes two emoticons after inserting: guy + color palette.

![emoticons_split_up_2](https://user-images.githubusercontent.com/1211300/100139731-2ff9cb00-2e90-11eb-8926-5544c2272dad.gif)

**Comment by nikslor** [comment] 2020-11-24 19:05
For the future me:
```ffmpeg -i foo.mp4 -vf "fps=10,scale=800:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 foo.gif```

**Comment by tml1024** [comment] 2020-11-25 09:47
Looking into the "male artist" issue now. I fear that is something that will need to be implemented in LibreOffice core, though, and probably should be seen as a missing feature, not a bug.

**Comment by tml1024** [comment] 2020-11-25 09:58
But sure, to the end-user it looks like a bug, as that clever emoji that is a combination of multiple code points with a zero-width-joiner looks like any other emoji when they are choosing one. The end-user can not know which emojis are implemented in which way.

**Comment by tml1024** [comment] 2020-11-25 10:01
And it can be even more complicated, one can add in a skin tone, for instance: https://emojipedia.org/man-artist-medium-light-skin-tone/ . What looks like a single emoji (glyph) 👨🏼‍🎨 consists of four code points: 👨 Man, 🏼 Medium-Light Skin Tone, ‍ Zero Width Joiner and 🎨 Artist Palette. See https://emojipedia.org/man-artist-medium-light-skin-tone/

**Comment by tml1024** [comment] 2020-11-25 10:03
For web-based Collabora Online, where LibreOffice core runs on Linux, the required functionality is probably in some external library, perhaps cairo. (Not entirely clear to me.) On iOS (and macOS) we don't use cairo, but system functionality, so there actually it might be easier to make it "just work". But as it doesn't "just work" on iOS currently, it is possible that some changes are required in LibreOffice core, too.

**Comment by tml1024** [comment] 2020-11-25 10:50
Filed upstream bug https://bugs.documentfoundation.org/show_bug.cgi?id=138481

**Comment by tml1024** [comment] 2020-11-25 13:10
Interesting: In LibreOffice, on macOS, if I use the Apple Color Emoji font, it works! So possibly it will work in the iOS app, too, if I just in some ways mak sure that font gets used.

**Comment by tml1024** [comment] 2020-11-25 20:18
Suggested fix in https://gerrit.libreoffice.org/c/core/+/106632 . Let's see what the reviewers say, if anything.

**Comment by tml1024** [comment] 2020-11-26 12:17
(See above-mentioned Gerrit change for more detailed technical discussion. This is a very complex issue, and digging it reveals at least one very ugly and unclear bit in LibreOffice...)

**Closed** 2020-11-27 09:34 UTC
Labels: bug, ios-app
