### ISSUE TITLE
iOS App: the dialog "Form > Properties" has overlapping buttons

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#5842] opened 2023-02-13 08:06 UTC
**Describe the bug**
The dialog "Form > Properties" has overlapping buttons in the current TestFlight version (22.05.202302092239)

**To Reproduce**
1. Open a writer document in the TestFligh iOS app
2. Tap on "Form"
3. Insert a "Dropdown"
4. Set cursor on the just added element
5. Tap on "Properties"

**Expected behavior**
All buttons should be visible

**Actual behavior**
Some buttons overlapp

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/218403171-5d7e4cbb-a1a9-4c61-828f-8fd7ab9d626a.png)

**Tablet**
 - OS: iPadOS 15.6.1
 - Version: 22.05.202302092239

**Comment by nikslor** [comment] 2023-02-18 09:51
Works now, tested with 22.05.10 (22.2.202302182232).
Should I close it, or do you want @plubius?

**Comment by plubius** [comment] 2023-02-18 13:05
@nikslor I am pleasantly surprised this bug is now fixed. This bug was in my next group of bugs to look at.

I think the dialog buttons are created by the underlying LibreOffice code. IIRC, the LibreOffice code in the latest test patch includes a small number of changes so I will give credit for the bug fix to the LibreOffice developers.

**Comment by nikslor** [comment] 2023-02-20 07:22
@plubius IIRC during the last CooL developer meeting (Thursday, 2023-02-16) @eszkadev mentioned, that he works on this; maybe hid did his magic there :)

**Comment by thebearon** [comment] 2023-02-20 11:14
This is a dupe of #5787, and indeed it's fixed now.

**Closed by thebearon** 2023-02-20 11:14 UTC
Labels: bug, ios
