### ISSUE TITLE
Almost impossible to enter input bar in calc, in iOS app or browser on iPad, with notebookbar

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#404] opened 2020-10-23 07:20 UTC
**Describe the bug**
Most of the time I fail to be able to put the cursor into the input bar of calc. I mean the large input field which sits avove the actual spreadsheet. Also the button to expand that field into a multi line edit field (down arrow) right next to the input bar seems not to be clickable.

**To Reproduce**
1. Open a spreadsheet in calc using the iOS app
2. Try to put the cursor into the input bar above the spreadsheet

**Expected behavior**
The cursor should easily be placeable in the input bar.

**Actual behavior**
It's almost impossible to put the cursor into the input bar.

**Tablet**
 - OS: iOS 14.1
 - Version: 6.4.0 (5)

**Additional context**
I have a hardware keyboard attached to my iPad (Apple Smarty Keyboard).

**Comment by tml1024** [comment] 2020-10-29 11:32
Hmm, yes. I am almost sure that this used to work better at some stage. (Or was that maybe in the 4.2.x app?)

**Comment by tml1024** [comment] 2020-10-29 11:43
For what it's worth, it seems equally hard to enter the input bar when using Safari on iPad against a "make run" with the user_interface changed to notebookbar in the loolwsd.xml. So does not seem to be an iOS app specific issue. @thebearon, how is it on an Android tablet, against make run, using notebookbar UI?

**Comment by tml1024** [comment] 2020-10-29 11:52
And yes, it does indeed seem that in "classic" mode, it is fairly trivial to make the input bar get input focus with blinking caret.

**Comment by tml1024** [comment] 2020-10-29 12:22
Another interesting phenomenon is that as I desperately tap away on the input bar (sometimes surely hitting a bit on the outside), occasionally, totally unexpected, a "Templates" dialog opens. 
![IMG_0024](https://user-images.githubusercontent.com/310731/97573204-12048c00-19f2-11eb-9d6e-de5221726204.png)

**Comment by eszkadev** [comment] 2020-10-29 12:55
@tml1024 this is because input bar is part of a main window. On click we send click event with added previously set offset. If offset is wrong we can click into eg. toolbar/notebookbar. I had fix for similar issue in the past:
d543cdaaab9e9c46d60ebc2db9cd7f685f8e5ca7   (core commit)
35534b7d63d3072862cf02b7a9b910a8ff3e75e0   (online commit)

**Comment by eszkadev** [comment] 2020-10-29 12:58
eh I see strange change from '|' to '||' operator in above commit... maybe it's the issue.

**Comment by eszkadev** [comment] 2020-11-03 11:03
it was a regression in core, I have fix for that: https://gerrit.libreoffice.org/c/core/+/105240

**Comment by thebearon** [comment] 2020-11-10 09:10
Seems fixed in build 6.4.0 (9). Thanks, @eszkadev!

**Closed by thebearon** 2020-11-10 09:10 UTC
Labels: bug
