### ISSUE TITLE
Specific file is unreadable so that in nextcloud office, not even the chrome appears

### ISSUE THREAD

**Issue by JMoVS** [CollaboraOnline/online#6857] opened 2023-07-08 13:53 UTC
**Describe the bug**
Document cannot be edited with Collabora. If the same document is saved as odf, then resaved as docx, it works.

**To Reproduce**
1. try to open the magic file - nothing happens

**Expected behavior**
Proper display of the file

**Actual behavior**
Blank window without chrome

**Screenshots**
![grafik](https://github.com/CollaboraOnline/online/assets/7354506/71d0114f-9232-4762-9737-4cb96ebadb28)

**Desktop (please complete the following information)**
 - OS: all affected
 - Browser: all affected
 - Version: [e.g. 22]

**Additional context**

The file is confidential but I sent a sanitised version to @mmeeks and @vmiklos directly.

**Comment by mmeeks** [comment] 2023-07-08 15:05
@vmiklos this looks like a floating frame issue that affects 23.05 specifically. @JMoVS can you paste the exact versions from help->about in Online (from another document). More details from IRC make this sound very multi-page-floating-frame-related =)

<JMoVS[m]> I bisected the problem down
<JMoVS[m]> an extract from the document.xml
<JMoVS[m]> this does not display:
* JMoVS[m] uploaded an image: (83KiB) < https://libera.ems.host/_matrix/media/v3/download/phelas.com/oiskqMwbaGzZXGWMgdnQBhfN/image.png >
<mmeeks> oh wow =)
<JMoVS[m]> but, when I remove either the w:tbl section (line 4-13769), it works, or I remove the w:p section (13770-13960)
<mmeeks> JMoVS[m]: and what is in the paragraph ?
<JMoVS[m]> in libreoffice om the desktop it works fine

**Comment by mmeeks** [comment] 2023-07-08 15:08
Trace is:
`Thread 1 (Thread 0x7fc63533dbc0 (LWP 199322) "kitbroker_003"):
#0  ImplLogicToPixel (nMapDenom=Python Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x111
#1  OutputDevice::LogicToPixel(tools::Rectangle const&) const (rLogicRect=..., this=0x1) at /home/data/opt/libreoffice/co-23.05/vcl/source/outdev/map.cxx:925
#2  OutputDevice::LogicToPixel(tools::Rectangle const&) const (this=this@entry=0x6a55e90, rLogicRect=...) at /home/data/opt/libreoffice/co-23.05/vcl/source/outdev/map.cxx:916
#3  0x00007fc62718f600 in SwPageFrame::GetHorizontalShadowRect(SwRect const&, SwViewShell const*, OutputDevice const*, SwRect&, bool, bool, bool) (_rPageRect=SwRect = {...}, _pViewShell=_pViewShell@entry=0x6ae7d80, pRenderContext=pRenderContext@entry=0x6a55e90, _orHorizontalShadowRect=SwRect = {...}, bPaintLeftShadow=bPaintLeftShadow@entry=false, bPaintRightShadow=bPaintRightShadow@entry=false, bRightSidebar=true) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/paintfrm.cxx:5937
#4  0x00007fc627190941 in SwPageFrame::GetBorderAndShadowBoundRect(SwRect const&, SwViewShell const*, OutputDevice const*, SwRect&, bool, bool, bool) (_rPageRect=SwRect = {...}, _pViewShell=0x6ae7d80, pRenderContext=0x6a55e90, _orBorderAndShadowBoundRect=SwRect = {...}, bLeftShadow=<optimized out>, bRightShadow=<optimized out>, bRightSidebar=true) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/paintfrm.cxx:6314
#5  0x00007fc62717e820 in SwPageFrame::DestroyImpl() (this=0x6d8b780) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/pagechg.cxx:301
#6  0x00007fc6271b0906 in SwFrame::DestroyFrame(SwFrame*) (pFrame=0x6d8b780) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/ssfrm.cxx:395
#7  0x00007fc62718141a in SwRootFrame::RemovePage(SwPageFrame**, SwRemoveResult) (this=<optimized out>, pDelRef=<optimized out>, eResult=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/pagechg.cxx:1504
#8  0x00007fc627182035 in (anonymous namespace)::doInsertPage(SwRootFrame*, SwPageFrame**, SwFrameFormat*, SwPageDesc*, bool, SwPageFrame**) (pRoot=0x6ab5330, pRefSibling=0x7ffca261f6c0, pFormat=<optimized out>, pDesc=0x67d9f20, bFootnote=<optimized out>, pRefPage=0x7ffca261f6c8) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/pagechg.cxx:1359
#9  0x00007fc627182164 in SwFrame::InsertPage(SwPageFrame*, bool) (this=this@entry=0x6d15130, pPrevPage=0x6cab110, bFootnote=bFootnote@entry=false) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/pagechg.cxx:1414
#10 0x00007fc62714f16c in SwFrame::GetNextFlyLeaf(MakePageType) (this=0x6d15130, eMakePage=MAKEPAGE_INSERT) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/flycnt.cxx:1625
#11 0x00007fc6271404e9 in SwFlowFrame::MoveFwd(bool, bool, bool) (this=this@entry=0x6d15230, bMakePage=<optimized out>, bPageBreak=bPageBreak@entry=false, bMoveAlways=bMoveAlways@entry=false) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/flowfrm.cxx:2048
#12 0x00007fc6271c039a in SwTabFrame::MakeAll(OutputDevice*) (this=0x6d15130, pRenderContext=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/tabfrm.cxx:2064
#13 0x00007fc6271becf6 in SwTabFrame::MakeAll(OutputDevice*) (this=0x6a9ef00, pRenderContext=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/tabfrm.cxx:2685
#14 0x00007fc62712f63a in SwFrame::PrepareMake(OutputDevice*) (this=0x6a9ef00, pRenderContext=0x6a55e90) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/calcmove.cxx:375
#15 0x00007fc6271c2f51 in SwFrame::Calc(OutputDevice*) const (this=this@entry=0x6a9ef00, pRenderContext=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/trvlfrm.cxx:1803
#16 0x00007fc62716f72d in SwLayAction::FormatLayoutTab(SwTabFrame*, bool) (this=0x7ffca2620170, pTab=0x6a9ef00, bAddRect=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/layact.cxx:1531
#17 0x00007fc627170fd2 in SwLayAction::FormatLayoutFly(SwFlyFrame*) (this=0x7ffca2620170, pFly=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/layact.cxx:1495
#18 0x00007fc62717a8d5 in SwObjectFormatter::FormatObj_(SwAnchoredObject&) (this=0x6c6b210, _rAnchoredObj=...) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/objectformatter.cxx:286
#19 0x00007fc62717be2d in SwObjectFormatterTextFrame::DoFormatObj(SwAnchoredObject&, bool) (_bCheckForMovedFwd=false, _rAnchoredObj=..., this=0x6c6b210) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/objectformattertxtfrm.cxx:133
#20 SwObjectFormatterTextFrame::DoFormatObj(SwAnchoredObject&, bool) (this=0x6c6b210, _rAnchoredObj=..., _bCheckForMovedFwd=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/objectformattertxtfrm.cxx:117
#21 0x00007fc62717a373 in SwObjectFormatter::FormatObjsAtFrame_(SwTextFrame*) (this=this@entry=0x6c6b210, _pMasterTextFrame=_pMasterTextFrame@entry=0x0) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/objectformatter.cxx:408
#22 0x00007fc62717c25a in SwObjectFormatterTextFrame::DoFormatObjs() (this=0x6c6b210) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/objectformattertxtfrm.cxx:348
#23 0x00007fc62717a5fa in SwObjectFormatter::FormatObjsAtFrame(SwFrame&, SwPageFrame const&, SwLayAction*) (_rAnchorFrame=..., _rPageFrame=<optimized out>, _pLayAction=_pLayAction@entry=0x7ffca2620170) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/objectformatter.cxx:160
#24 0x00007fc62716f0b6 in SwLayAction::FormatContent(SwPageFrame*) (this=0x7ffca2620170, pPage=0x69367e0) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/layact.cxx:1734
#25 0x00007fc627171c42 in SwLayAction::InternalAction(OutputDevice*) (this=0x7ffca2620170, pRenderContext=0x6a55e90) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/layact.cxx:603
#26 0x00007fc6271726c1 in SwLayAction::Action(OutputDevice*) (this=this@entry=0x7ffca2620170, pRenderContext=0x6a55e90) at /home/data/opt/libreoffice/co-23.05/sw/source/core/layout/layact.cxx:395
#27 0x00007fc62752889b in SwViewShell::ImplEndAction(bool) (this=0x6ae7d80, bIdleEnd=<optimized out>) at /home/data/opt/libreoffice/co-23.05/include/rtl/ref.hxx:206
#28 0x00007fc626eae794 in SwViewShell::EndAction(bool) (bIdleEnd=false, this=0x6ae7d80) at /home/data/opt/libreoffice/co-23.05/sw/inc/viewsh.hxx:633
#29 SwCursorShell::EndAction(bool) (this=0x6ae7d80, bIdleEnd=bIdleEnd@entry=false) at /home/data/opt/libreoffice/co-23.05/sw/source/core/crsr/crsrsh.cxx:263
#30 0x00007fc627868097 in SwView::OuterResizePixel(Point const&, Size const&) (this=0x6948a80, rOfst=<optimized out>, rSize=<optimized out>) at /usr/include/c++/11/bits/unique_ptr.h:173
#31 0x00007fc6334ab633 in SfxViewFrame::DoAdjustPosSizePixel(SfxViewShell*, Point const&, Size const&, bool) (inplaceEditModeChange=<optimized out>, rSize=<optimized out>, rPos=<optimized out>, pSh=<optimized out>, this=0x6ab12b0) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/viewfrm.cxx:1967
#32 SfxViewFrame::DoAdjustPosSizePixel(SfxViewShell*, Point const&, Size const&, bool) (this=0x6ab12b0, pSh=<optimized out>, rPos=<optimized out>, rSize=<optimized out>, inplaceEditModeChange=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/viewfrm.cxx:1951
#33 0x00007fc6334ac070 in SfxViewFrame::Resize(bool) (this=0x6ab12b0, bForce=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/viewfrm.cxx:2761
#34 0x00007fc63070531c in vcl::Window::ImplCallResize() (this=0x68aa750) at /home/data/opt/libreoffice/co-23.05/vcl/source/window/event.cxx:525
#35 0x00007fc630785510 in vcl::Window::Show(bool, ShowFlags) (this=this@entry=0x68aa750, bVisible=bVisible@entry=true, nFlags=nFlags@entry=ShowFlags::NONE) at /home/data/opt/libreoffice/co-23.05/vcl/source/window/window.cxx:2297
#36 0x00007fc63349feae in SfxBaseController::ConnectSfxFrame_Impl(SfxBaseController::ConnectSfxFrame) (this=0x69a6d30, i_eConnect=SfxBaseController::E_CONNECT) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/sfxbasecontroller.cxx:1185
#37 0x00007fc6334a0ee4 in SfxBaseController::attachFrame(com::sun::star::uno::Reference<com::sun::star::frame::XFrame> const&) (this=0x69a6d30, xFrame=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/sfxbasecontroller.cxx:530
#38 0x00007fc633486954 in (anonymous namespace)::SfxFrameLoader_Impl::impl_createDocumentView (i_rViewName="Default", i_rViewFactoryArgs=..., i_rFrame=uno::Reference to ((anonymous namespace)::XFrameImpl *) 0x659f360, i_rModel=uno::Reference to (SwXTextDocument *) 0x66504f0) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/frmload.cxx:584
#39 (anonymous namespace)::SfxFrameLoader_Impl::load(com::sun::star::uno::Sequence<com::sun::star::beans::PropertyValue> const&, com::sun::star::uno::Reference<com::sun::star::frame::XFrame> const&) (this=<optimized out>, rArgs=<optimized out>, _rTargetFrame=<optimized out>) at /home/data/opt/libreoffice/co-23.05/sfx2/source/view/frmload.cxx:759
#40 0x00007fc6339f5bbc in framework::LoadEnv::impl_loadContent() (this=0x7ffca2620ca0) at /home/data/opt/libreoffice/co-23.05/framework/source/loadenv/loadenv.cxx:1176
#41 0x00007fc6339f8bbc in framework::LoadEnv::start() (this=0x7ffca2620ca0) at /home/data/opt/libreoffice/co-23.05/framework/source/loadenv/loadenv.cxx:412
#42 0x00007fc6339f92e6 in framework::LoadEnv::startLoading(rtl::OUString const&, com::sun::star::uno::Sequence<com::sun::star::beans::PropertyValue> const&, com::sun::star::uno::Reference<com::sun::star::frame::XFrame> const&, rtl::OUString const&, int, LoadEnvFeatures) (this=0x7ffca2620ca0, sURL=<optimized out>, lMediaDescriptor=<optimized out>, xBaseFrame=<optimized out>, sTarget=<optimized out>, nSearchFlags=0, eFeature=LoadEnvFeatures::NONE) at /home/data/opt/libreoffice/co-23.05/framework/source/loadenv/loadenv.cxx:308
#43 0x00007fc6339f9b12 in framework::LoadEnv::loadComponentFromURL(com::sun::star::uno::Reference<com::sun::star::frame::XComponentLoader> const&, com::sun::star::uno::Reference<com::sun::star::uno::XComponentContext> const&, rtl::OUString const&, rtl::OUString const&, int, com::sun::star::uno::Sequence<com::sun::star::beans::PropertyValue> const&) (xLoader=uno::Reference to (framework::Desktop *) 0x4cb4708, xContext=uno::Reference to (cppu::(anonymous namespace)::ComponentContext *) 0x17aab90, sURL="file:///tmp/user/docs/6HzoblRSFEa5jP1C/TS.docx", sTarget="_blank", nSearchFlags=nSearchFlags@entry=0, lArgs=uno::Sequence of length 5 = {...}) at /home/data/opt/libreoffice/co-23.05/framework/source/loadenv/loadenv.cxx:168
#44 0x00007fc633a0a49f in framework::Desktop::loadComponentFromURL(rtl::OUString const&, rtl::OUString const&, int, com::sun::star::uno::Sequence<com::sun::star::beans::PropertyValue> const&) (this=0x4cb4690, sURL="file:///tmp/user/docs/6HzoblRSFEa5jP1C/TS.docx", sTargetFrameName="_blank", nSearchFlags=0, lArguments=uno::Sequence of length 5 = {...}) at /home/data/opt/libreoffice/co-23.05/framework/source/services/desktop.cxx:595
#45 0x00007fc634ee50ef in lo_documentLoadWithOptions(LibreOfficeKit*, char const*, char const*) (pThis=0x173fa00, pURL=<optimized out>, pOptions=<optimized out>) at /home/data/opt/libreoffice/co-23.05/desktop/source/lib/init.cxx:2808
#46 0x0000000000612c60 in lok::Office::documentLoad(char const*, char const*) (this=0x65254f0, pUrl=0x652e400 "file:///tmp/user/docs/6HzoblRSFEa5jP1C/TS.docx", pFilterOptions=0x6407290 ",DeviceFormFactor=desktop,EnableMacrosExecution=false,MacroSecurityLevel=1,Timezone=Europe/London") at /home/data/opt/libreoffice/co-23.05/include/LibreOfficeKit/LibreOfficeKit.hxx:926
#47 0x000000000062d08d in Document::load(std::shared_ptr<ChildSession> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x652f220, session=std::shared_ptr<ChildSession> (use count 3, weak count 1) = {...}, renderOpts="") at kit/Kit.cpp:1569
`

**Comment by JMoVS** [comment] 2023-07-09 07:48
```
COOLWSD Version:
23.05.1.2 git hash: 
[a708901](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/a708901'));)
(E)
LOKit Version:
built on 
[a great technology base](javascript:void(window.open('http://col.la/lot'));)
Collabora Office 23.05.1.2 git hash: 
[cc6b8db](javascript:void(window.open('https://hub.libreoffice.org/git-core/cc6b8db'));)
Angeboten von: Debian GNU/Linux 12 (bookworm) 
[007e203d](https://office.phelas.com/hosting/discovery)

Copyright © 2023, Collabora Productivity Limited
```

**Comment by vmiklos** [comment] 2023-07-10 06:17
I can reproduce a layout loop, which is indeed specific to multi-page floating tables. I'll take a look.

**Comment by vmiklos** [comment] 2023-07-12 07:21
https://gerrit.libreoffice.org/c/core/+/154343 fix for master is pending CI here, still need to backport it.

**Comment by mmeeks** [comment] 2023-07-12 08:18
Nice work fixing it and also generating an anonymized unit test - thanks Miklos =)

**Comment by vmiklos** [comment] 2023-07-19 09:34
The backport was submitted to co-23.05 on Monday, closing.

**Closed by vmiklos** 2023-07-19 09:34 UTC
Labels: bug, 23.05
