### ISSUE TITLE
Calc: Dropdown for value lists not visible

### ISSUE THREAD

**Issue by ssergio-ll** [CollaboraOnline/online#6986] opened 2023-07-31 05:48 UTC
### Steps to Reproduce

 have version 23.05.2.2 of Collabora.

In the Excel sheets, if I add a list validation field, in the latest version, the "Select" dropdown to choose one of the field's values disappears, making it impossible to work with the lists.

1. Create an Excel sheet.
2. Select a cell, click on "Data," and then "Data Validation."
3. Set the field to "List" mode and add values.
4. Now, a "select" should appear in the cell, but it doesn't show up, so you can't choose a value from the list.

### Expected Behavior

A dropdown should appear to choose the values.

### Actual Behavior

The dropdown does not appear.

### Screenshots

Screen 1: https://i.imgur.com/EpGJb03.png
Screen 2: https://i.imgur.com/BslHWcR.png
Screen 3: https://i.imgur.com/5lk5Yso.png

![image](https://github.com/CollaboraOnline/online/assets/7240617/bcc05065-dc73-4fbc-a15b-10ef57fdc00f)
![image](https://github.com/CollaboraOnline/online/assets/7240617/27af70a0-3ebe-4f75-9fe8-d30e6e0d0998)

Thanks!

**Comment by Ezinnem** [comment] 2023-07-31 09:13
I can confirm that the List Dropdown icon is missing.

In my experience, the first List item I added is visible but the rest of the items are not visble

**Comment by timur-g** [comment] 2023-08-01 09:51
This seems the same as #6956. When I tested that one, it worked for me, but not today. Also, input box is now too small.

**Comment by thebearon** [comment] 2023-08-16 12:09
It's just that the icon is missing, otherwise it's working fine, if you select the cell, and click the same place as it should be.
It also only occurs with branding.

It's a regression from the following commit:

https://github.com/CollaboraOnline/online/commit/fb5909bc404f19b3673722600fd022e01210c1e4
https://github.com/CollaboraOnline/online/pull/6955
```
Author:     Pranam Lashkari <lpranam@collabora.com>
AuthorDate: Fri Jul 21 22:49:17 2023 +0700
Commit:     pedropintosilva <65948705+pedropintosilva@users.noreply.github.com>
CommitDate: Mon Jul 24 10:06:35 2023 +0200

    theme: use integration theme value from the interation message
```

CC @lpranam

**Comment by djacksonosu** [comment] 2023-08-31 04:21
Any status on when this will be fixed?

**Comment by skleffmann** [comment] 2023-09-20 07:57
Still NOT fixed in 23.05.4.1

**Comment by Ornanovitch** [comment] 2023-09-25 13:29
I can reproduce in 23.05.4-2

**Comment by Ezinnem** [comment] 2023-10-16 15:38
The fix has been made on the branding side.

COOLWSD version:
23.05.5.1 git hash: [af8ba819](https://github.com/CollaboraOnline/online/commits/af8ba819)(E)

**Comment by Ornanovitch** [comment] 2023-10-16 15:54
Is it supposed to be fixed with 23.05.5.1 or after? I just updated and it still not working :/

**Comment by skleffmann** [comment] 2023-10-17 07:16
I can confirm this is NOT fixed in COOLWSD-Version: 23.05.5.1 git hash: [1fea227] (E) / Collabora Office 23.05.5.1 git hash: [c8d84f5]

**Comment by pedropintosilva** [comment] 2023-10-17 08:01
Sorry everyone it seems there has been a confusion here. 
Let me please clarify the issue.

The icon is not missing. However it's been, incidentally, removed when using Nextcloud. The fix is still not in.

My expectation is that fixes from both sides will be able to be tested by next week (release). 

Thank you.

**Comment by pedropintosilva** [comment] 2023-10-17 08:02
> This seems related or the same as #6956. When I tested that one, it worked for me, but not today. There seem to be 3 issues:
> 
>     1. inserting values with simple enter does not keep values, unless \n is used (that was [Data -> Validity -> List #6956](https://github.com/CollaboraOnline/online/issues/6956).).
> 
>     2. size of Entries input box is now too small, was larger as it should (as in screenshot, no integration)
> 
>     3. list dropdown icon is missing, you can't choose a value from the list, only the first List item is visible (as reported here) .
> 
> 
> ![image](https://user-images.githubusercontent.com/7240617/257478113-46ee5ea6-f9dd-4d96-aecd-1b839020c307.png)

Thanks @timur-g but I think this is another unrelated bug

**Comment by Ornanovitch** [comment] 2023-10-17 10:06
Thanks for the clarifications! And thanks a lot for your hard work everyone :)

**Comment by mr-bolle** [comment] 2023-11-01 09:02
After the last update https://github.com/CollaboraOnline/online/commits/5093121 i can confirm that the issue is solved. 

![Screenshot_20231101_092350_Chrome.jpg](https://github.com/CollaboraOnline/online/assets/22414212/18b15bbc-db3e-49ff-b750-e28ddfa6e371)

**Closed** 2023-11-01 09:03 UTC
Labels: bug, regression, 23.05
