### ISSUE TITLE
Remove the ... at NB Labels

### ISSUE THREAD

**Issue by Andreas-Kainz** [CollaboraOnline/online#1285] opened 2021-01-20 12:11 UTC
In LibreOffice the three dots (...) for an dialog wasn't shown in cool they will be shown. 

I suggest to don't show the ... in cool.

Cool
![2021-01-20 13_09_34-ws-a3df5ab9-a090-4043-8293-148f004bb2e7_0 - noVNC](https://user-images.githubusercontent.com/8517736/105173056-c957fd00-5b20-11eb-8ba3-db47234127ce.png)
LibreOffice tab
![2021-01-20 13_11_07-ws-a3df5ab9-a090-4043-8293-148f004bb2e7_0 - noVNC](https://user-images.githubusercontent.com/8517736/105173204-fad0c880-5b20-11eb-8771-a0b2fdeee149.png)

**Comment by Andreas-Kainz** [comment] 2021-01-20 12:11
@pedropintosilva any idea how to remove them?

**Comment by pedropintosilva** [comment] 2021-01-20 12:28
> I suggest to don't show the ... in cool.

Yes, I agree and I have suggested the same some time ago on Telegram and I think in some meeting.

I also have discussed this with @eszkadev and I have inspect it. It seems it's not as easy as remove (hardcoded) because it's coming already like that from translated strings. Now the question is where there are coming from or that maybe we are getting the original strings not from the tabs but from the menu items on core. 

Nevertheless @eszkadev said he thinks it will be easier to make sure that no ellipsis are there programmatically without affecting any current strings from the weblate side etc . If he does beat us, maybe you or I can come up with a PR (I will keep you posted)

**Comment by Andreas-Kainz** [comment] 2021-01-20 13:15
If you check both screenshots come from cool. The insert tab screenshot is made by .JS and JSON and the layout tab come direct from core.

However I know that we already discussed, I only want to have an real issue for tracking.

**Comment by pedropintosilva** [comment] 2021-01-20 15:16
Yeah definitely is important to have this in some tracking issue, thanks : ) and true the structure is done there but the translated strings are then applied according to user's idiom (at least with the majority if not all the labels)

**Comment by kendy** [comment] 2021-01-21 11:01
@Andreas-Kainz: There are more variants of texts in the .xcu files for various commands, I suspect we are using a wrong one for the Notebookbar (?)  @eszkadev ?

**Comment by pedropintosilva** [comment] 2021-04-15 07:45
as seen in the my commits I have fixed at the time before the release the more flagrant cases, but it would be great to have it fixed in all other places.

It seems we are pulling from core the wrong kind of string from those uno commands (menu instead of tab bar). Fix: get the right type of string (from tab bar)

Online:
![image](https://user-images.githubusercontent.com/65948705/114832822-37822800-9dcf-11eb-9d97-bd4340de12c8.png)

Core:
![image](https://user-images.githubusercontent.com/65948705/114832885-4963cb00-9dcf-11eb-9361-bff282bfce39.png)

**Comment by pedropintosilva** [comment] 2021-04-22 05:24
_let's please keep this open_

- [x] Temporally solution merged  a41ab8f , thanks @Andreas-Kainz !
- [ ] Definitive solution: get the right strings from core in the first place

**Comment by lpranam** [comment] 2021-04-26 11:18
a41abf has caused a regression. and which is making cypress fail.

that patch also removed elepses from formula bar help. try formula->logical->AND(help)
there it should have elipsis in the last parameter like this:
`AND( Logical value 1, Logical value 2, ...)'`

but unfortunately, last `...` is removed


got to know about this via @Rash419's PR: https://github.com/CollaboraOnline/online/pull/2147

**Comment by pedropintosilva** [comment] 2021-11-12 09:21
this is still present in many places

**Comment by Ezinnem** [comment] 2022-04-01 12:27
This issue seems to have been fixed. No longer seen on the COOLWSD version: 21.11.3.3 git hash: [ad4ad21](https://github.com/CollaboraOnline/online/commits/ad4ad21)

**Closed** 2022-04-01 12:27 UTC
Labels: Easy Hack, UX, NB-default blocker
