### ISSUE TITLE
Andriod Mobile: Pinch-zoom can displace sheet area

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#7276] opened 2023-09-19 10:59 UTC
### Describe the Bug

Pinch Zoom affects the dimensions of the Column and Row.

### Steps to Reproduce

1. Open a Calc file in Android.
2. Using fingers, Zoom out and Scroll up/down

Notice that the Column/Row width is displaced
### Expected Behavior

The zoom does not cause area displacement.

### Actual Behavior

The zoom does cause area displacement.

### Screenshots

Uploading XRecorder_28082023_164845_(online-video-cutter.com)_(1).mp4…

### Smartphone

(Please complete the following information)
 - **Device:**Samsung A13
 - **OS:** Andriod 13
 - **Version:** 23.05

**Comment by timur-g** [comment] 2023-09-19 11:09
dupe of #7275

**Closed by timur-g** 2023-09-19 11:09 UTC
Labels: bug, unconfirmed
