### ISSUE TITLE
Dropdown menu items stops working case the filename nears the Help button location while shrinking the browser size

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#4613] opened 2022-04-15 19:32 UTC
**Describe the bug**
Help dropdown menu stops working case the filename enters near the Help button location shrinking the browser size

**To Reproduce**
1. Go to your Browser full screen, open Nextcloud, open a file to edit with CODE
2. Click on 'Help' in the menu bar while hoovering over the Help button lights up, the dropdown menu opens when click it.
3. Take the Browser out of full screen, click the right side to schrink the screen right to left so the filename (blank.odt) move toward the "Help" button
4. When the filename gets near the Help button the menu does not light up anymove when hoovering over and can no longer be clicked on (screenshot). Also not that while hooverig near the help button with the mouse pointer the file location description popup up at the shown location in the screenshot.

**Expected behavior**
Help menu should still function when the Browser screen is resized

**Actual behavior**
When the filename gets near the Help button the menu does not light up anymove when hoovering over and can no longer be clicked on (screenshot)

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/37268999/163623564-c4377b18-b4f4-4de7-bc6a-45a66045839f.png)

**Desktop (please complete the following information)**
 - OS: WIndows 11
 - Browser: Firefox 99.0.1

**Additional context**
COOLWSD versie:
21.11.3.6 git hash: [eb73aa3]
LOKit versie:
Collabora Office 21.06.26.1 git hash: [524dda8]
Nextcloud 23.03

**Comment by Ezinnem** [comment] 2022-04-28 11:24
Reproducible on 
COOLWSD version: 22.05.0.1 git hash: [455532c2](https://github.com/CollaboraOnline/online/commits/455532c2)(E)
LOKit version: Collabora Office 22.05.0.1 git hash: [a14eab0](https://git.libreoffice.org/core/+log/a14eab0)

**Comment by sebastiaanveld** [comment] 2022-05-26 10:33
See also #4806

**Comment by kkofler** [comment] 2022-05-26 12:06
Indeed, on my 1280×1024 monitor, I do not even have to shrink the browser window to see this bug, it happens even with a maximized browser window.

**Comment by sebastiaanveld** [comment] 2022-06-08 19:02
Fixed in Staging.
COOLWSD versie: 22.05.0.1 git hash: [d11a23be]
LOKit versie:
Collabora Office 22.05.2.1 git hash: [8d1627f]

**Comment by kkofler** [comment] 2022-11-22 04:09
> Fixed in Staging.
> COOLWSD versie: 22.05.0.1 git hash: [d11a23b]

I do not believe it was actually fixed in 22.05.0.1, because the server is now running 22.05.8 and the bug is still there.

**Comment by kwaun** [comment] 2023-01-11 18:05
I am running 22.05.9.2.1 and sadly the bug is still there.

**Comment by vasyugan** [comment] 2023-02-02 19:39
I am run

> Fixed in Staging. COOLWSD versie: 22.05.0.1 git hash: [[d11a23b](https://github.com/CollaboraOnline/online/commit/d11a23be72d932cc43c31b92c8ce16dd5f1e8c5b)] LOKit versie: Collabora Office 22.05.2.1 git hash: [8d1627f]

I am running 22.05.9.3 and this bug is unfortunately still stubbornly present.

**Comment by kkofler** [comment] 2023-02-02 20:19
I am running 22.05.10 now, it looks slightly better, the title is moved more to the right, so at least it only overlaps with most of the help ("Hilfe" in German) menu, which can be used by clicking on the left edge of the 'H', which is not covered, but it still overlaps with most of the text of "Hilfe" and also with the "Last saved: …" notice.

**Comment by vasyugan** [comment] 2023-02-03 01:24
> I am running 22.05.10 now, it looks slightly better, the title is moved more to the right, so at least it only overlaps with most of the help ("Hilfe" in German) menu, which can be used by clicking on the left edge of the 'H', which is not covered, but it still overlaps with most of the text of "Hilfe" and also with the "Last saved: …" notice.

For me, nothing has changed.

**Comment by kkofler** [comment] 2023-02-03 01:54
I am not sure that anything in CODE has really changed for me either, it may have been slightly better on the files I tried today for some unrelated reason. It is clear that the bug is not really fixed, or the title would not overlap any menus at all.

**Comment by sebastiaanveld** [comment] 2023-02-19 12:13
Looks fixed for me in latest CODE: as screen shrinks the items in top bar no longer shift left over the menu bar.
COOLWSD version: 22.05.10.1 git hash: [719ae9b]
LOKit version: built on Collabora Office 22.05.10.1 git hash: [dadcf15]

![image](https://user-images.githubusercontent.com/37268999/219947195-6c7dd9d4-7d2c-4d5b-8194-72efa47fc424.png)


Also looks fixed in Staging, as the screen shrinks items dissapear from the top toolbar:
COOLWSD version: 23.05.0.1 git hash: [d3518f7f]
LOKit version: built on Collabora Office 23.05.0.1 git hash: [ff9a1ba]
Served by: openSUSE Leap 15.3 [6e930f1a]

![image](https://user-images.githubusercontent.com/37268999/219947029-d8d2dacd-8ba4-4b68-97da-3d94a67f6388.png)

As other who has this issue agree it's fixed for them too the ticket can be closed.

**Comment by Ezinnem** [comment] 2023-02-20 08:52
This is no longer reproducible.

Tested on:
COOLWSD version: 22.05.10.2 git hash:  [2b7e520 ]( https://github.com/CollaboraOnline/online/commits/2b7e520 )

**Closed by Ezinnem** 2023-02-20 08:52 UTC
Labels: bug
