### ISSUE TITLE
Font not preserved

### ISSUE THREAD

**Issue by nadirlouati** [CollaboraOnline/online#6382] opened 2023-05-18 13:14 UTC
**Describe the bug**
The font is not preserved if i type before the first caracter in an bulled list

**To Reproduce**
when i add text on the first list item before “Random text”, the font is not preserved.
Random text use calibri font
but the inserted text is ms sans serif
i attached the sample .docx file. 

**Expected behavior**
font preserved

**Actual behavior**
font not preserved

**Screenshots**
[test.docx](https://github.com/CollaboraOnline/online/files/11508035/test.docx)
![image](https://github.com/CollaboraOnline/online/assets/61733635/f5a2d387-531d-46a3-bf6e-b21abcec480d)

**Desktop (please complete the following information)**
 - collabora online 22.05.12.4 docker
 - same problem with 
       COOLWSD version:
      22.05.14.3git hash: [c360011]
      
      LOKit version:
      Collabora Office 22.05.14.3git hash: [8e4f947]
      Served by: Ubuntu 18.04.6 LTS [91357248]

link to original ticket
https://forum.collaboraonline.com/t/font-not-preserved/1795/7

**Comment by Tex2002ans** [comment] 2023-05-18 14:01
Yes, I was able to reproduce this too:

- Open `test.docx`.
- Click at beginning of 1st bullet.
- Type something.

Actual:

- Font = “MS Sans Serif” + 10pt is used.

Expected:

- Font = “Calibri” + 13pt.

- - -

**Side Note:** Looks like in COOL, if you place the cursor:

- Right after a bullet
- OR very beginning of the “Résultat” line

typing new text starts using the:

- “Default Paragraph” Style

which is set to:

- “MS Sans Serif” + 10pt font

not matching the direct formatting next to the cursor.

- - -

### Testing Info

DOCX does not work in today's master:

> COOLWSD version:
> 23.05.0.1 git hash: (012b00d6)
> LOKit version:
> Collabora Office 23.05.0.1 git hash: (bc5c5de)
> Served by: Linux Mint 21.1 (33ee7769)

DOCX works as expected in:

- LibreOffice 7.5.3

and CODE:

> Version: 23.05.0.20230516 (X86_64)
> Build ID: 7b0259573fb3c16e43fb47cf5f2548c81f162383
> CPU threads: 4; OS: Linux 5.15; UI render: default; VCL: gtk3
> Locale: en-US (en_US.UTF-8); UI: en-US
> Calc: threaded

**Comment by nadirlouati** [comment] 2023-06-13 07:18
any help ?

**Comment by nadirlouati** [comment] 2023-08-01 07:26
it seems like no one can handle this wired bug :smile:

**Comment by Tex2002ans** [comment] 2023-08-10 04:23
Hey nadirlouati,

It will get fixed eventually. Especially if we have good documents + simple reproducible steps like this one!

Thanks for testing on the latest version too + seeing it's still an issue.

(Just yesterday, I got an email that [one of the LibreOffice crashes I randomly tested last year](https://bugs.documentfoundation.org/show_bug.cgi?id=147938) was fixed! Devs will poke around and get around to fixing these things eventually!)

**Comment by nadirlouati** [comment] 2024-03-25 07:12
Helo, it's been a while !

any updates ?

**Comment by Tex2002ans** [comment] 2024-03-27 23:23
No. No updates so far. When there is, you'll be one of the first to know!

- - -

I just retested again, and looks like it's still the same in latest:

> COOLWSD version: 24.04.1.1 (git hash: 8b97c452)
> LOKit version: Collabora Office 24.04.1.1 (git hash: 96bbedb)
> Served by: Linux Mint 21.3
> Server ID: be779a4e

**Comment by hartsberger** [comment] 2024-05-24 10:49
Just to let you know: It doesn't only affect bullet points, but also "fields". 
(I'm not sure how this function is called in English. field function?, field command?)

Here are some screenshots: 

Before edit --> Times New Roman: 
![2024-05-24 12_35_09-vorlage1 docx](https://github.com/CollaboraOnline/online/assets/60740965/460ac23a-e229-4ee7-a673-9b5e8016c7ee)

When adding text at the end --> keeps Times New Roman: 
![2024-05-24 12_36_34-vorlage1 docx](https://github.com/CollaboraOnline/online/assets/60740965/e59ece69-eec8-43e9-9b03-e7d84ba374a5)

When adding text at the beginning or replacing the field --> changes to Arial: 
![2024-05-24 12_35_49-vorlage1 docx](https://github.com/CollaboraOnline/online/assets/60740965/daf65ede-fe73-4a3d-8759-a72e21a656d9)


This is especially annoing, because it happens with our main template file for letters. 

If there is anything I can help/test let me know. Thanks.

**Comment by Tex2002ans** [comment] 2024-06-27 02:00
Hey @hartsberger , just noticed your Fields + Fonts issue. Do you think you could:

- Submit a separate Bug Report
- \+ Share a sample document with the problem

It may be related to this specific list/bullet issue, or it might not. But having your problem document would really help too. Thanks. :)

**Comment by JaumePujantell** [comment] 2024-10-08 11:24
A proposed fix for this issue on core: https://gerrit.libreoffice.org/c/core/+/174657

**Comment by nadirlouati** [comment] 2024-10-09 07:02
Thanks, good news ! hope it will be included in next version

**Comment by Ezinnem** [comment] 2024-10-16 06:53
The fix has been implemented and will be included the next 24.04 update.

Tested using:
COOLWSD version: 24.04.9.0(git hash: [a330f9e7](https://github.com/CollaboraOnline/online/commits/a330f9e7) (E))
LOKit version: Collabora Office 24.04.9.0(git hash: [3eec192](https://git.libreoffice.org/core/+log/3eec192))

[Screencast from 16-10-2024 07:41:33.webm](https://github.com/user-attachments/assets/69bf067f-7619-45d4-89c9-b742040cb067)

**Closed by Ezinnem** 2024-10-16 06:53 UTC
Labels: bug
