### ISSUE TITLE
No URL Hyperlinks Available with ods or odt shared as link in NC

### ISSUE THREAD

**Issue by skykingisepic** [CollaboraOnline/online#5672] opened 2023-01-06 19:00 UTC
**Describe the bug**
Sharing an ods or odt doc via shared link in NC doesn't allow clicking or `<Ctrl>` clicking on link to go to that URL link. Publishing a document full of URL hyperlinks for users to access is useless since they don't work. Sharing as editable is NOT an option.

**Comment by thebearon** [comment] 2023-01-17 03:04
This is a duplicate of #1248.

**Closed by thebearon** 2023-01-17 03:04 UTC
Labels: bug, unconfirmed

**Comment by RainerBielefeld** [comment] 2024-08-21 13:44
This is a really **[annoying](https://help.nextcloud.com/t/nextcloud-office-hyperlink-in-spreadsheet-does-not-work-in-readonly-mode/201118)** bug!

**Comment by RainerBielefeld** [comment] 2024-08-22 05:52
And why is it "not planned" to fix an annoying bug?

**Comment by thebearon** [comment] 2024-08-28 10:10
@RainerBielefeld As noted:
> This is a duplicate of https://github.com/CollaboraOnline/online/issues/1248.

Please see there. And it's supposed to be resolved now.
