### ISSUE TITLE
iOS app: unable to open a file with "open in" 

### ISSUE THREAD

**Issue by tyreun** [CollaboraOnline/online#1817] opened 2021-03-23 11:31 UTC
**Describe the bug**
With 
iPad 7ème gen
iOS 14.4.1
collabora office 6.4.7
**To Reproduce**
1) If my file (odt, ods, odp) is in the native iOS app "Files", when I tap on it the file open. 
2) If my file (odt, ods, odp) is in an other app (Documents by Readdle, Pearltrees, Googledrive.....), when I try to open it with "open in Collabora", nothing happends. **I Can't open it**. I have to send a copy in the native iOS app "Files" to be able to open the file.

https://user-images.githubusercontent.com/1543205/112139266-dbaeef80-8bd2-11eb-8203-64d8bcebcc1a.mov

**Comment by tyreun** [comment] 2021-03-25 09:20
Issue solved with the last release

**Comment by tyreun** [comment] 2021-03-25 10:34
Before this last release, in the native iOS app "Files", I had to tap twice on a file to open it. Now, with one tap, the file will open.    
But with the release 6.4.7, I have the same issue if the file is in an other app.

**Comment by tml1024** [comment] 2021-04-06 12:29
When you say _my file (odt, ods, odp) is in an other app_, what do you mean? That it is located in a file provider extension, like Google Drive or OneDrive, those that show up under "Locations" to the left in this image? 
![A34B8D06-AC4F-44FA-87EE-F32069D21CF8_1_105_c](https://user-images.githubusercontent.com/310731/113710072-ec3f8980-96eb-11eb-8ed1-3090d3a4e787.jpeg) If so, this issue is probably a duplicate of https://github.com/CollaboraOnline/online/issues/1509, and was hopefully fixed in 6.4.7-2 (App Store version number).

**Comment by tyreun** [comment] 2021-04-08 14:06
> When you say _my file (odt, ods, odp) is in an other app_, what do you mean? That it is located in a file provider extension, like Google Drive or OneDrive, those that show up under "Locations" to the left in this image?
> ![A34B8D06-AC4F-44FA-87EE-F32069D21CF8_1_105_c](https://user-images.githubusercontent.com/310731/113710072-ec3f8980-96eb-11eb-8ed1-3090d3a4e787.jpeg) If so, this issue is probably a duplicate of #1509, and was hopefully fixed by [a51df73](https://github.com/CollaboraOnline/online/commit/a51df73a955b303e5b505d18764b7be4c199f678) which is in 6.4.7-2 (App Store version number).

No, my file is in an app. I can't access to my file in the iOS app "Files" (no extension). So, I share this file (odt, doc, docx) in an other app and select collabora but I can't open this file. Issue with
- Pearltrees
- Documents by readdle
- iPlugmate
- Sheets from Google

But since the last release, it works with the app "google drive".

**Comment by tyreun** [comment] 2021-05-03 07:22
hi,

This issue is not solved with the last release 6.4.7-3

Regards

**Comment by tyreun** [comment] 2021-06-08 13:52
UP !

It's no possible to edit an existing document stored in an other app with collabora.

It is a major bug, isn't it ?

Regards


https://user-images.githubusercontent.com/1543205/121196596-e8a5bb80-c870-11eb-979f-33c51c28c525.mov

**Comment by tyreun** [comment] 2021-11-19 09:44
this is the same bug that #1885

**Comment by Ezinnem** [comment] 2021-11-19 12:31
I can reproduce this issue using 6.4.13 (git hash: cea7112).

**Comment by sebastiaanveld** [comment] 2021-12-08 16:06
Issue is still there in App 21.06.1.0 (Testflight)

**Comment by sebastiaanveld** [comment] 2022-04-15 18:38
Looks solved in 21.11.3 (6)

I was able to select I file in an app (Nextcloud in my test)> select Open In> select Collabora Office. File was opened in the Collabora App where I could View and Edit. On Save the file was Saved in the source app (Nextloud) updating the original file. On Exit of the Collabora App I ended up in the Collabora startfolder and could click to return to the source app.

If others agree we can close this issue.

**Comment by tyreun** [comment] 2022-04-15 21:17
Hi,

It’s better. Now I can open an odt file with the command « open in » but I can’t edit the file. I can just comment the file


Cheers

Ronan

**Comment by sebastiaanveld** [comment] 2022-04-16 13:27
>  It’s better. Now I can open an odt file with the command « open in » but I can’t edit the file. I can just comment the file 
> […](#)

would’t that depend on the filetype you’re opening? If I open an odt I can use the Edit button to start editing. Case a pdf you won’t have an edit button, but only the option to add comments.

**Comment by tyreun** [comment] 2022-04-17 18:02
No, I can reproduce this issue with odt files from apps like
Document by Readdle
Peartrees
Google drive

**Comment by sebastiaanveld** [comment] 2023-02-19 14:29
@tyreun is this still an issue for you? I tested today and works fine for me using Collabora Office Testflight 22.05.10 (22.5.202302180032) on IOS 16.3.1 (iPhone 14)

**Comment by tyreun** [comment] 2023-02-21 07:43
Hi,

I can now open an odt file from an external storage in the app collabora but I can only read the file, I can’t edit it


￼￼￼￼￼

**Comment by sebastiaanveld** [comment] 2023-02-28 08:17
Mmm it works fine for me using Collabora Office Testflight 22.05.10 on iPad 5th gen iOS 16.3.1 using Dutch localization.
What I do see in your screenshot https://user-images.githubusercontent.com/1543205/220283895-751430c7-abc9-4e5b-9404-9392825406a2.jpg the close button for the document is located at the middle of the page while mine is in the at the right of the page.  Due to that the document title and sidebar button are also not show in your screenshot, they should be between the menu buttons and the close button in the top bar.

**Comment by tyreun** [comment] 2023-02-28 09:11
Hi,

you can see on the screenshot the same file with landscape view. It's not possible to edit the file. The top bar is the same as if the file was a PDF.

![IMG_4CEC95A4DB52-1](https://user-images.githubusercontent.com/1543205/221806151-59132ca9-47fb-4965-b36b-66fb2d0ffacc.jpeg)
![IMG_B16449782575-1](https://user-images.githubusercontent.com/1543205/221806168-55f747b1-d0fd-4db3-b0b1-78019b3c827b.jpeg)


![IMG_B16449782575-1](https://user-images.githubusercontent.com/1543205/221805130-e1d7ce2e-cfa8-4045-9b7d-01f28c044738.jpeg)

**Closed** 2024-11-05 12:28 UTC
Labels: bug, ios, 6.4.X

**Comment by tyreun** [comment] 2024-11-05 12:30
Issue solved with iOS18 et the app version 24.04.7.3 but not with iOS17

**Comment by tyreun** [comment] 2025-03-24 08:47
Hi,

Same issue on iPad 10th gen, iOS 18.3.2, collabora 24.04.12.4, French settings (language and timezone). 
I can open an odt file in collabora from an external storage but I can only view and comment it, I can't edit this file.
Example with Google drive
![IMG_0639](https://user-images.githubusercontent.com/1543205/220283863-de1406c0-a03a-49d9-b7a8-b4c9418b4d53.jpg)
![IMG_0640](https://user-images.githubusercontent.com/1543205/220283882-3f94ce38-3ffa-48f6-9546-b824e7fb9d58.jpg)
![IMG_0641](https://user-images.githubusercontent.com/1543205/220283888-7354fae9-d173-4d5d-924c-81edbfd337ea.jpg)
![IMG_0642](https://user-images.githubusercontent.com/1543205/220283893-1bb93e3d-3ad2-409d-8fb2-d81a3d284957.PNG)
![IMG_0643](https://user-images.githubusercontent.com/1543205/220283895-751430c7-abc9-4e5b-9404-9392825406a2.jpg)
