### ISSUE TITLE
Mobile: Text cannot be copied from a read-only files

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#6927] opened 2023-07-18 11:10 UTC
**Describe the bug**
Text cannot be copied from a read-only file

**To Reproduce**
1. Open a file
2. Without clicking on the pencil icon to switch to edit mode, long-press on a text to select and copy it.

**Expected behavior**
The text is highlighted and can be copied

**Actual behavior**
The text is not highlighted and cannot be copied

**Screenshots**
screenshot of the expected behaviour

![Screenshot_20230713-193532_1u (1)](https://github.com/CollaboraOnline/online/assets/54344301/be8de7cd-e46f-4cc3-9df4-8c143a10d52d)

**Comment by pedropintosilva** [comment] 2023-09-20 07:50
duplicate of https://github.com/CollaboraOnline/online/issues/4914

**Closed by pedropintosilva** 2023-09-20 07:50 UTC
Labels: enhancement
