### ISSUE TITLE
Opening certain PowerPoint PPTX files crash the IOS App

### ISSUE THREAD

**Issue by sebastiaanveld** [CollaboraOnline/online#1710] opened 2021-03-12 15:22 UTC
Opening certain PowerPoint PPTX files crash the IOS App. The files can be opened fine in CODE. 
Collabora Office 6.4.6, previous 6.4.x had the same issue.

**To Reproduce**
1. Go to 'Collabora Office' App on IOS
2. In Locations, click on 'Open on my iPhone' or 'Nextcloud' depending where your file is stored; opening the file makes the App crash on either location.
3. Scroll down to the file name (attached example file) and click to open it.
4. The App crashes and and the report can be send to the App Store.

**Expected behavior**
The file should be opened.

**Actual behavior**
The App crashes.

**Screenshots**
nothing visible

**Smartphone (please complete the following information)**
 - Device: iPhone X
 - OS: IOS 14.4.1

Attached one
[Presentation-UEM-GSKOFY18.pptx](https://github.com/CollaboraOnline/online/files/6130997/Presentation-UEM-GSKOFY18.pptx)
 of the problem files

**Comment by tml1024** [comment] 2021-03-16 08:18
Yep, can reproduce, will investigate.

**Comment by tml1024** [comment] 2021-03-16 08:50
Stack trace from crash (when built from current core:cp-6.4 + online:co-6-4):

#0	0x0000000109ba03fc in std::__1::shared_ptr<SalBitmap>::shared_ptr(std::__1::shared_ptr<SalBitmap> const&) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4061
#1	0x0000000109b9aaf4 in std::__1::shared_ptr<SalBitmap>::shared_ptr(std::__1::shared_ptr<SalBitmap> const&) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4063
#2	0x0000000109b9aa78 in Bitmap::Bitmap(Bitmap const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/bitmap/bitmap.cxx:39
#3	0x0000000109b9ab30 in Bitmap::Bitmap(Bitmap const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/bitmap/bitmap.cxx:42
#4	0x0000000109918910 in BitmapEx::BitmapEx(Bitmap const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/bitmapex.cxx:114
#5	0x00000001099189d0 in BitmapEx::BitmapEx(Bitmap const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/bitmapex.cxx:118
#6	0x0000000109b947d4 in BitmapEx::operator=(Bitmap const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/include/vcl/bitmapex.hxx:58
#7	0x0000000109b4bb80 in VectorGraphicData::ensurePdfReplacement() at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/vectorgraphicdata.cxx:154
#8	0x0000000109b4bcb8 in VectorGraphicData::ensureReplacement() at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/vectorgraphicdata.cxx:166
#9	0x0000000109b4e4a4 in VectorGraphicData::getReplacement() const at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/vectorgraphicdata.cxx:345
#10	0x00000001099cb010 in ImpGraphic::getVectorGraphicReplacement() const at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/impgraph.cxx:528
#11	0x00000001099cbcb8 in ImpGraphic::ImplGetBitmapEx(GraphicConversionParameters const&) const at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/impgraph.cxx:659
#12	0x00000001099bd1c0 in Graphic::GetBitmapEx(GraphicConversionParameters const&) const at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/graph.cxx:351
#13	0x000000010268e590 in emfio::EmfReader::ReadMultiformatsComment() at /Volumes/TML13/lo/cp-6.4-ios-debug/emfio/source/reader/emfreader.cxx:512
#14	0x000000010268dfcc in emfio::EmfReader::ReadGDIComment(unsigned int) at /Volumes/TML13/lo/cp-6.4-ios-debug/emfio/source/reader/emfreader.cxx:439
#15	0x000000010268f94c in emfio::EmfReader::ReadEnhWMF() at /Volumes/TML13/lo/cp-6.4-ios-debug/emfio/source/reader/emfreader.cxx:870
#16	0x000000010266ce48 in emfio::emfreader::XEmfParser::getDecomposition(com::sun::star::uno::Reference<com::sun::star::io::XInputStream> const&, rtl::OUString const&, com::sun::star::uno::Sequence<com::sun::star::beans::PropertyValue> const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/emfio/source/emfuno/xemfparser.cxx:153
#17	0x0000000109b4c158 in VectorGraphicData::ensureSequenceAndRange() at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/vectorgraphicdata.cxx:220
#18	0x0000000109b4c640 in VectorGraphicData::getRange() const at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/gdi/vectorgraphicdata.cxx:331
#19	0x0000000102295e30 in drawinglayer::primitive2d::create2DDecompositionOfGraphic(drawinglayer::primitive2d::Primitive2DContainer&, Graphic const&, basegfx::B2DHomMatrix const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/primitive2d/graphicprimitivehelper2d.cxx:489
#20	0x000000010229c6d4 in drawinglayer::primitive2d::GraphicPrimitive2D::create2DDecomposition(drawinglayer::primitive2d::Primitive2DContainer&, drawinglayer::geometry::ViewInformation2D const&) const at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/primitive2d/graphicprimitive2d.cxx:111
#21	0x000000010227dc44 in drawinglayer::primitive2d::BufferedDecompositionPrimitive2D::get2DDecomposition(drawinglayer::primitive2d::Primitive2DDecompositionVisitor&, drawinglayer::geometry::ViewInformation2D const&) const at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/primitive2d/baseprimitive2d.cxx:126
#22	0x0000000102302bd8 in drawinglayer::processor2d::BaseProcessor2D::process(drawinglayer::primitive2d::BasePrimitive2D const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/baseprocessor2d.cxx:47
#23	0x0000000102323104 in drawinglayer::processor2d::VclPixelProcessor2D::processBasePrimitive2D(drawinglayer::primitive2d::BasePrimitive2D const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/vclpixelprocessor2d.cxx:420
#24	0x0000000102302d6c in drawinglayer::processor2d::BaseProcessor2D::process(drawinglayer::primitive2d::Primitive2DContainer const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/baseprocessor2d.cxx:70
#25	0x0000000102302be8 in drawinglayer::processor2d::BaseProcessor2D::process(drawinglayer::primitive2d::BasePrimitive2D const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/baseprocessor2d.cxx:48
#26	0x0000000102323104 in drawinglayer::processor2d::VclPixelProcessor2D::processBasePrimitive2D(drawinglayer::primitive2d::BasePrimitive2D const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/vclpixelprocessor2d.cxx:420
#27	0x0000000102302d6c in drawinglayer::processor2d::BaseProcessor2D::process(drawinglayer::primitive2d::Primitive2DContainer const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/baseprocessor2d.cxx:70
#28	0x0000000102302be8 in drawinglayer::processor2d::BaseProcessor2D::process(drawinglayer::primitive2d::BasePrimitive2D const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/baseprocessor2d.cxx:48
#29	0x0000000102323104 in drawinglayer::processor2d::VclPixelProcessor2D::processBasePrimitive2D(drawinglayer::primitive2d::BasePrimitive2D const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/vclpixelprocessor2d.cxx:420
#30	0x0000000102302d6c in drawinglayer::processor2d::BaseProcessor2D::process(drawinglayer::primitive2d::Primitive2DContainer const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/baseprocessor2d.cxx:70
#31	0x00000001023289d4 in drawinglayer::processor2d::VclProcessor2D::RenderMaskPrimitive2DPixel(drawinglayer::primitive2d::MaskPrimitive2D const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/vclprocessor2d.cxx:727
#32	0x0000000102322ef4 in drawinglayer::processor2d::VclPixelProcessor2D::processBasePrimitive2D(drawinglayer::primitive2d::BasePrimitive2D const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/vclpixelprocessor2d.cxx:310
#33	0x0000000102302d6c in drawinglayer::processor2d::BaseProcessor2D::process(drawinglayer::primitive2d::Primitive2DContainer const&) at /Volumes/TML13/lo/cp-6.4-ios-debug/drawinglayer/source/processor2d/baseprocessor2d.cxx:70
#34	0x0000000106ac37c4 in sdr::contact::ObjectContactOfPageView::DoProcessDisplay(sdr::contact::DisplayInfo&) at /Volumes/TML13/lo/cp-6.4-ios-debug/svx/source/sdr/contact/objectcontactofpageview.cxx:290
#35	0x0000000106ac3098 in sdr::contact::ObjectContactOfPageView::ProcessDisplay(sdr::contact::DisplayInfo&) at /Volumes/TML13/lo/cp-6.4-ios-debug/svx/source/sdr/contact/objectcontactofpageview.cxx:121
#36	0x0000000106b40668 in SdrPageWindow::RedrawAll(sdr::contact::ViewObjectContactRedirector*) at /Volumes/TML13/lo/cp-6.4-ios-debug/svx/source/svdraw/sdrpagewindow.cxx:337
#37	0x0000000106d90350 in SdrPageView::CompleteRedraw(SdrPaintWindow&, vcl::Region const&, sdr::contact::ViewObjectContactRedirector*) at /Volumes/TML13/lo/cp-6.4-ios-debug/svx/source/svdraw/svdpagv.cxx:253
#38	0x0000000106d9ad88 in SdrPaintView::DoCompleteRedraw(SdrPaintWindow&, vcl::Region const&, sdr::contact::ViewObjectContactRedirector*) at /Volumes/TML13/lo/cp-6.4-ios-debug/svx/source/svdraw/svdpntv.cxx:649
#39	0x0000000106d9acc8 in SdrPaintView::CompleteRedraw(OutputDevice*, vcl::Region const&, sdr::contact::ViewObjectContactRedirector*) at /Volumes/TML13/lo/cp-6.4-ios-debug/svx/source/svdraw/svdpntv.cxx:562
#40	0x0000000105c228c8 in sd::View::CompleteRedraw(OutputDevice*, vcl::Region const&, sdr::contact::ViewObjectContactRedirector*) at /Volumes/TML13/lo/cp-6.4-ios-debug/sd/source/ui/view/sdview.cxx:470
#41	0x0000000105b762f0 in sd::DrawView::CompleteRedraw(OutputDevice*, vcl::Region const&, sdr::contact::ViewObjectContactRedirector*) at /Volumes/TML13/lo/cp-6.4-ios-debug/sd/source/ui/view/drawview.cxx:521
#42	0x0000000105abaa88 in SdXImpressDocument::paintTile(VirtualDevice&, int, int, int, int, long, long) at /Volumes/TML13/lo/cp-6.4-ios-debug/sd/source/ui/unoidl/unomodel.cxx:2247
#43	0x00000001063fd1d8 in paintTileToCGContext at /Volumes/TML13/lo/cp-6.4-ios-debug/desktop/source/lib/init.cxx:2139
#44	0x00000001063e8d50 in doc_paintTileToCGContext(_LibreOfficeKitDocument*, void*, int, int, int, int, int, int) at /Volumes/TML13/lo/cp-6.4-ios-debug/desktop/source/lib/init.cxx:3233
#45	0x00000001063fd390 in paintTileIOS at /Volumes/TML13/lo/cp-6.4-ios-debug/desktop/source/lib/init.cxx:2156
#46	0x00000001063e8a08 in doc_paintTile(_LibreOfficeKitDocument*, unsigned char*, int, int, int, int, int, int) at /Volumes/TML13/lo/cp-6.4-ios-debug/desktop/source/lib/init.cxx:3170
#47	0x00000001063e9450 in doc_paintPartTile(_LibreOfficeKitDocument*, unsigned char*, int, int, int, int, int, int, int) at /Volumes/TML13/lo/cp-6.4-ios-debug/desktop/source/lib/init.cxx:3316
#48	0x0000000100f986f8 in lok::Document::paintPartTile(unsigned char*, int, int, int, int, int, int, int) at /Volumes/TML13/lo/cp-6.4-ios-debug/include/LibreOfficeKit/LibreOfficeKit.hxx:584
#49	0x0000000100f96478 in RenderTiles::doRender(std::__1::shared_ptr<lok::Document>, TileCombined&, PngCache&, ThreadPool&, bool, std::__1::function<void (unsigned char*, int, int, unsigned long, unsigned long, int, int, LibreOfficeKitTileMode)> const&, std::__1::function<void (char const*, unsigned long)> const&) at /Volumes/TML13/lo/online-ios-device/common/RenderTiles.hpp:523
#50	0x0000000100fa877c in Document::renderTiles(TileCombined&, bool) at /Volumes/TML13/lo/online-ios-device/kit/Kit.cpp:744
#51	0x0000000100fa6a6c in Document::renderCombinedTiles(StringVector const&) at /Volumes/TML13/lo/online-ios-device/kit/Kit.cpp:701
#52	0x0000000100fa5340 in Document::drainQueue(std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) at /Volumes/TML13/lo/online-ios-device/kit/Kit.cpp:1532
#53	0x0000000100fa4638 in KitSocketPoll::drainQueue(std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) at /Volumes/TML13/lo/online-ios-device/kit/Kit.cpp:1820
#54	0x0000000100f9a7d0 in KitSocketPoll::kitPoll(int) at /Volumes/TML13/lo/online-ios-device/kit/Kit.cpp:1862
#55	0x0000000100f9a174 in pollCallback(void*, int) at /Volumes/TML13/lo/online-ios-device/kit/Kit.cpp:2114
#56	0x0000000109e9b1ec in AquaSalInstance::DoYield(bool, bool) at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/headless/svpinst.cxx:492
#57	0x0000000109cb0850 in ImplYield(bool, bool) at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/app/svapp.cxx:464
#58	0x0000000109cb0654 in Application::Yield() at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/app/svapp.cxx:528
#59	0x0000000109cb05cc in Application::Execute() at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/app/svapp.cxx:445
#60	0x00000001063ac15c in desktop::Desktop::Main() at /Volumes/TML13/lo/cp-6.4-ios-debug/desktop/source/app/app.cxx:1617
#61	0x0000000109cce39c in ImplSVMain() at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/app/svmain.cxx:191
#62	0x0000000109ccf7d0 in SVMain() at /Volumes/TML13/lo/cp-6.4-ios-debug/vcl/source/app/svmain.cxx:225
#63	0x00000001063e0b9c in soffice_main at /Volumes/TML13/lo/cp-6.4-ios-debug/desktop/source/app/sofficemain.cxx:115

**Comment by tml1024** [comment] 2021-03-16 09:06
The cause for the crash is that in VectorGraphicData::ensurePdfReplacement() , the aBitmaps vector is empty when it reaches the assignment `maReplacement = aBitmaps[0];`

**Comment by tml1024** [comment] 2021-03-23 10:07
Is fixed in the latest TestFlight build.

**Comment by nikslor** [comment] 2021-03-24 08:51
I can open the file in 6.4.7 (1) w/o crash and think the issue can be closed.

**Closed** 2021-03-24 08:52 UTC
Labels: bug, ios-app

**Comment by sebastiaanveld** [comment] 2021-03-24 10:16
Tested it with several docs that couldn't be opened before and works fine with 6.4.7.
