### ISSUE TITLE
iOS App: some icons in the sidebar of the writer component are not well aligned

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#6100] opened 2023-03-27 09:15 UTC
**Describe the bug**
In the current TestFlight version (22.05.11, 22.5.202303212054), some buttons in the sidebar are not well aligned. The result may vary depending on the context of the cursor (paragraph, table, ...). But some elements are always misaligned. Namely:
* ```Underlining``` button not aligned with ```Italic``` and ```Bold```

As a result: 
* The buttons ```strike through```, ```shadow``` , ```remove formatting``` are too far right (in a L-t-R setup)

Also, some buttons change the size, depending on being active/non-active and then move the other buttons off screen (e.g. ```strike through```, ```shadow```).

**To Reproduce**
1. Open a writer document in the current iOS TestFlight version
2. Open the sidebar

**Expected behavior**
* the buttons should be well aligned and visible all the time
* buttons should (probably?) not change size depending on being active/non-active

**Actual behavior**
* the buttons are mis-aligned and sometimes they are not visible due to size changes of some buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/1211300/227897714-0fc7e38e-b29d-405d-8d39-c678207a9b1f.png)

**Tabled**
 - OS: iPadOS 16.3.1
 - Version: 22.05.11, 22.5.202303212054

**Comment by plubius** [comment] 2023-03-28 18:48
I can reproduce this bug with the TestFlight build but, running a local build with newer Collabora Online code, I cannot reproduce it.
![Screenshot 2023-03-28 at 2 41 10 PM](https://user-images.githubusercontent.com/104370511/228337822-132f1a8e-3d8f-472f-899b-2ec72a15f70d.png)

**Comment by plubius** [comment] 2023-03-30 19:36
I found the cause of this bug: the build scripts used for TestFlight builds includes Collabora Online's branded CSS and images and I had set the build scripts to pull these assets from the wrong branch.

The next TestFlight will display all these toolbar buttons at normal size. I set the build script to use the same branch as the 21.x release that is currently in the App Store.

**Comment by plubius** [comment] 2023-04-02 12:54
The fix for this bug is in the current TestFlight. Does the fix work for you?

**Comment by nikslor** [comment] 2023-04-06 06:32
Tested again in 22.05.12 (22.5.202304051456); works as expected now :)
Thanks a lot @plubius I think you can close this issue as fixed.

**Closed** 2023-04-06 10:04 UTC
Labels: bug, ios
