### ISSUE TITLE
Fonts outside the well known paths won't be installed to collabora online but remains cached

### ISSUE THREAD

**Issue by durdin85** [CollaboraOnline/online#5087] opened 2022-08-01 09:52 UTC
**Describe the bug**
When system font is installed outside the well known font path, collabora would show the font in the possible font selection due to font being cached, but won't copy it to jail resulting in invisible text in document.

**To Reproduce**
1. Install some font outside of /usr/share/fonts, the **fonts-texgyre** deb package is nice example
2. Run **coolconfig update-system-template** --> Collabora would copy the font cache, but not the font files
3. Create new document, save document, write some text and select one of the _missing_ fonts. Text would disappear. Save document.
4. Uninstall the font from the system, run **fc-cache -v -r** and **coolconfig update-system-template** once more.
5. Open same document, text would appear again

**Expected behavior**
There are two possible outcomes, one is to throw an error, another is to do not show fonts with actually missing files in dropdown. Another possible outcome is to render the text with some "default" font instead of hiding it.

**Actual behavior**
Invisible text in document.

**Screenshots**
This font is not physically present on the _/opt/cool/systemplate/_, but still available in the font selection:
![snip1](https://user-images.githubusercontent.com/6603216/182122624-71523a2c-0d6e-4ff3-b9e6-3a9d5f78dea8.png)

**Additional context**
Collabora online, installed from deb/ubuntu packages, ver. 22.05.4-1

**Comment by dirdi** [comment] 2023-01-07 22:19
Seems to be a duplicate of https://github.com/CollaboraOnline/online/issues/4555.

**Comment by timur-g** [comment] 2023-11-30 11:04
Those steps sre nice, thanks, but as you said let us keep it in https://github.com/CollaboraOnline/online/issues/4555.

**Closed by timur-g** 2023-11-30 11:04 UTC
Labels: bug, unconfirmed
