### ISSUE TITLE
Can't create comments with German special characters (Umlaute: äöüß)

### ISSUE THREAD

**Issue by saschawinandy** [CollaboraOnline/online#5006] opened 2022-07-12 11:10 UTC
If I try to create a comment with a special character (öäüß) the comment do not appear after click on "save".

1. Create a new text document in Nextcloud by adding a document with "+"
2. Write some text: "lorem ipsum ..." 
3. Mark a part of the text
4. Add a comment
5. Insert a text that contains a special german character äöüß
6. Hit "save"
7. Nothing was saved

Without a german special character, you are able to save the comment

**Expected behavior**
Also comments with a special character are saveable

**Actual behavior**
All comments with a special character will not be saved without error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/76199408/178476571-09f89c88-9947-41fe-b718-bbe105c6c1c5.png)

**Desktop (please complete the following information)**
 - OS: Windows 10 LTSC
 - Browser: Edge
 - Version: 102

- Nextcloud: 24.0.2
- Collabora Online - Built-in CODE Server: 22.5.301
- Nextcloud Office: 6.1.1

**Comment by Ezinnem** [comment] 2022-07-14 09:54
This seems to be a duplicate of #4732.

Since they are similar, it would be best to track the issue on #4732

**Closed by Ezinnem** 2022-07-14 09:54 UTC
Labels: bug, unconfirmed
