### ISSUE TITLE
copy - paste between different documents not work

### ISSUE THREAD

**Issue by Eugene7219** [CollaboraOnline/online#5223] opened 2022-09-08 05:16 UTC
**Describe the bug**
copy - paste between different xlsx documents opened in two or more brouser tabs not work

**To Reproduce**
1. open in brouser first xlsx document
2. open  in brouser in other tab second xlsx document
3. create in the first document new sheet
4. return to second document and copy-paste all page (Ctrl+a, Ctrl+c)
5. go to the first document to new crated sheet
6. try to paste (Ctrl+v)
7. result - empty sheet, not inserted

**Expected behavior**
On the new sheet of first doc must be inserted data from second document 

**Actual behavior**
Any data between of different documents, opened in different tabs is not inserted

**Screenshots**
nt actual

**Desktop (please complete the following information)**
 - OS: windows 10
 - Browser: chrome any version and firefox 104.0.1 tested
 - Version: chrome any version and firefox 104.0.1

**Smartphone (please complete the following information)**
 Smartphones not tested

**Additional context**
!!! copy - paste between one xlsx document opened in two or more brouser tabs works properly

**Comment by RegisPerdreau** [comment] 2022-10-19 10:23
Confirmed

**Comment by gitgt** [comment] 2023-03-13 16:56
I tested this but could not reproduce with COOLWSD version: 22.05.10.1 and Firefox browser in Windows 10. 
Please write your COOLWSD whenever reporting and confirming.

**Comment by gitgt** [comment] 2023-05-30 10:18
@Eugene7219  @RegisPerdreau concerning previous comment, plese retest.

**Comment by thebearon** [comment] 2023-07-11 10:26
No reply, closing.

**Closed by thebearon** 2023-07-11 10:26 UTC
Labels: bug, unconfirmed, info needed
