### ISSUE TITLE
Table formatting resets when adding columns/rows

### ISSUE THREAD

**Issue by KiaraGrouwstra** [CollaboraOnline/online#5173] opened 2022-08-20 14:44 UTC
**Describe the bug**
I found when changing the layout of a table the formatting will change.

**To Reproduce**

- make table
- make first row bold
- add column
- find bold formatting is gone

**Expected behavior**
Formatting intact

**Actual behavior**
Formatting reset

**Desktop (please complete the following information)**
 - OS: Arch
 - Browser: Firefox
 - Version: 103.0.2

**Comment by Ezinnem** [comment] 2022-08-23 08:51
Reproducible in: 
COOLWSD version:
22.05.5.3 git hash: [0dff3076](https://github.com/CollaboraOnline/online/commits/0dff3076)(E)

**Comment by thebearon** [comment] 2023-05-07 04:57
This was changed in the following two commits. The reason was that when using the Insert Table dialog, the table cells had no borders, only when added with the toolbar/tabbed bar widget.

https://cgit.freedesktop.org/libreoffice/core/commit/?id=ef46afe71751929b8b17d278d83c8e3ceefc862f
```
author		Mert Tumer <mert.tumer@collabora.com>	2022-03-23 14:23:23 +0300
committer	Szymon Kłos <szymon.klos@collabora.com>	2023-02-09 19:10:58 +0000

sw: change inserttable style option default to 1
```

https://cgit.freedesktop.org/libreoffice/core/commit/?id=8620b204b51a9e0552a0002f7f06292bdfad37a7
```
author		Mert Tumer <mert.tumer@collabora.com>	2022-03-25 17:56:30 +0300
committer	Szymon Kłos <szymon.klos@collabora.com>	2023-02-09 19:11:09 +0000

make default selected table style to Default Table Style for only online
```

The second commit explains the reason:
```
unfortunately when the table has a style sw/qa/uitest/writer_tests4/tdf115573.py fails
because tables that have pre-applied style resets the style of the elements in their cells
when a new row is inserted and the ui test above relies on that. For now this is LOK only
```

This is due to the following LibreOffice behavior: https://bugs.documentfoundation.org/show_bug.cgi?id=126008

**Comment by thebearon** [comment] 2024-05-29 10:44
Let's mark this as duplicate of #7280.

**Closed by thebearon** 2024-05-29 10:44 UTC
Labels: bug, core
