### ISSUE TITLE
iOS App: Calc - Paste icon is disabled and does not respond when clicked

### ISSUE THREAD

**Issue by Ezinnem** [CollaboraOnline/online#5908] opened 2023-02-25 11:49 UTC
**Describe the bug**
At the initial start of the application, the Paste icon of the Calc does not respond to click and looks disabled

**To Reproduce**
1. Go to the TestFlight and Install Collabora Office app
2. Create and open a new Calc file
3. Add data some cells
4.  select some of the cells, Copy
5. Go to a new cell or sheet, then try to Paste

**Expected behavior**
The copied data get pasted

**Actual behavior**
There is no way to paste the data, the Paste icon in the menu toolbar is disabled

If you close and reopen the application/file, the Paste icon gets enabled and works as expected again

**Screenshots**

https://user-images.githubusercontent.com/54344301/221355249-79609c68-9220-481e-ad0c-aefe3d9e0aeb.mp4

**Desktop (please complete the following information)**
 - OS: iOS
 - Collabora office app on TestFlight
 - Version: 22.05.10

**Comment by Ezinnem** [comment] 2023-02-25 11:51
@plubius

**Comment by plubius** [comment] 2023-02-25 13:50
I think this is a duplicate of issue #5839. The problem looks like the Copy button is failing to copy to the system clipboard.

**Comment by plubius** [comment] 2023-03-10 15:22
Using the patch in pull request #5988, I can now copy and paste so it appears that this bug was caused by the code marking the document as read-only.

I will keep this bug open as I did find a new bug. When pasting something that was copied from a different app for the first time, a (I presume native) dialog will ask you to allow or disallow pasting form the other app. If you tap the disallow button, the iOS will crash in LibreOffice core's Window::SetLOKNotifier() method.

I will investigate the crashing bug.

**Comment by plubius** [comment] 2023-03-10 17:13
I have added a LibreOffice patch that fixes the crashing when the "disallow" option is selected:

https://gerrit.libreoffice.org/c/core/+/148655

**Comment by plubius** [comment] 2023-03-13 21:13
The fix for this bug is now in the latest TestFlight build. Please close if the bug is fixed for you.

**Comment by plubius** [comment] 2023-03-23 22:58
My fix is in the latest test patch. Can you close the bug if the fix works for you?

**Comment by nikslor** [comment] 2023-03-27 07:56
Works for me in 22.05.11 (22.5.202303212054); but I'll leave it to @Ezinnem to close as she reported it.

**Closed** 2023-04-13 22:46 UTC
Labels: bug, ios
