### ISSUE TITLE
Cannot protect / unprotect sheet

### ISSUE THREAD

**Issue by avatar1024** [CollaboraOnline/online#551] opened 2020-11-06 15:33 UTC
Since updating to CODE 6.4.0, it is no longer possible to protect or unprotect sheets on a spreadsheet. The option is missing both on right click on the sheet name and from the menu.

**Comment by cornouws** [comment] 2020-11-06 21:06
are you sure that un/protect are available in earlier versions of Online?
If so, pls tell me where I have to look - I don't see it.
thnx

**Comment by avatar1024** [comment] 2020-11-06 21:56
@cornouws Thank you for the reply. I am pretty sure since most spreadsheet are work with are protected but since I cannot go back to earlier version it's true that I cannot verify. I would be surprised if I had just noticed it know since I have been using CODE for a while know, but it is a possibility.
Are you able to try on 4.2 or 4.0?

**Comment by Andreas-Kainz** [comment] 2020-11-06 21:58
I will add it to the menubar, should work there.

**Comment by avatar1024** [comment] 2020-11-06 22:01
@Andreas-Kainz Thanks a lot! Is it available somewhere currently that I have missed?

**Comment by Andreas-Kainz** [comment] 2020-11-06 22:02
didn't saw it, but I know the codebase not that long. however I sync the COOL menubar with the LibO one and protect is available so it should be available in Cool too.

**Comment by avatar1024** [comment] 2020-11-06 22:08
@Andreas-Kainz Ok thanks! I look forward to it. CODE has been shaping up really nicely and I'm trying to get more and more people on it!
Can you update this post when you know in which release those change will be made?

**Comment by mmeeks** [comment] 2020-11-06 22:15
One thing to be aware of ... we need to make sure any new dialogs we throw up are async enabled. What does that mean ? that means that the dialog doesn't chew up a stack frame by calling 'Execute' in the code, since this can cause problems for collaborative editing (that are not immediately apparent). So - worth getting code review on any new .uno commands we expose =) someone needs to take a peek at the implementation(s). Of course - if it was exposed before, or is present in Notebookbar but not in menus (or vv.) then someone already had a look I think; so great to sync. those two.

Thanks !

**Comment by Andreas-Kainz** [comment] 2020-11-06 22:34
I'm not 100% sure what you mean @mmeeks. What I did is, that I test before add an .uno command (dialog) to the menubar. In addition I'm sure that the dialogues I added to the menubar are also available in the notebookbar implementation (now standard layout). I didn't add commands which want be useful or didn't work.
anyhow it can alway happen that something get wrong. I'm not a big fan that all the menubar's are located within one .js file. In LibO there are separate files for writer, calc, impress, ... in online everything is in one (big) Control.Menubar.js file.

**Comment by cornouws** [comment] 2020-11-09 14:30
> @cornouws 
> Are you able to try on 4.2 or 4.0?
Yes. I have access to a server running 4.2 - So I carefully checked before asking you ;)
But the good news is, that apparently working online and offline for you feel similarly great, that you see it as one experience ;)

**Comment by avatar1024** [comment] 2021-11-29 16:46
Hello, this got closed but as far as I can tell @Andreas-Kainz commit was not incorporated since I still cannot see any option (ether in right click on sheet name nor on the menu) to protect / unprotect sheets. Should it be reopened?

**Comment by thebearon** [comment] 2021-11-30 03:26
Sure, let's reopen. And just noting that I don't think protecting sheets was ever available in Collabora Online.

**Comment by avatar1024** [comment] 2021-12-01 13:19
> Sure, let's reopen. And just noting that I don't think protecting sheets was ever available in Collabora Online.

Yes you are right, it was not available, my mistake. So maybe this should be a feature request rather than a bug?

**Comment by avatar1024** [comment] 2022-04-16 09:52
Can someone change the tag to feature request on this?

**Comment by andrsharov** [comment] 2022-05-26 10:06
Hi, everybody.

We also need this feature. 

We need to protect some columns and cell in the general Calc documents

**Comment by avatar1024** [comment] 2022-07-29 08:13
Should this be marked as feature request or enhancement instead of a bug?? And do we know if there is any plan to add this function?

**Comment by andrsharov** [comment] 2022-07-29 11:51
Hi, @avatar1024 . 

Yes this is not a bug, this is feature request . Please make it as feature request. 

We need some functionality like Google Sheets , like this  https://support.google.com/a/users/answer/9308980?hl=en

**Comment by pedropintosilva** [comment] 2023-02-21 09:10
@thebearon or @gitgt could you re-check what's the status of this? If it's still valid or if it was implemented. I have replaced the bug tag with enhancement

**Comment by gitgt** [comment] 2023-02-21 10:00
Valid enhancement seen in multiple channels.

**Comment by hfiguiere** [comment] 2024-02-14 14:26
The changes have landed. You can protect / unprotect a sheet, and do the same for the cells. There is a visual indicator as well.

In 23.05.9.1 or the one after.

**Closed by hfiguiere** 2024-02-14 14:26 UTC
Labels: enhancement
