### ISSUE TITLE
iOS App: Lines and basic shapes are hard to handle using a finger

### ISSUE THREAD

**Issue by nikslor** [CollaboraOnline/online#2099] opened 2021-04-22 15:11 UTC
**Describe the bug**
Lines as well as other "thin" elements from the "Basic Shapes" collection are hard to select and use using a finger. In many cases I struggle to get the line selected at all; the area that acts on a finger tap must be increased.

![image](https://user-images.githubusercontent.com/1211300/115738634-827edb00-a38d-11eb-8297-95a1d457a4b4.png)

**To Reproduce**
1. Open a writer document in the iOS app
2. Insert a line and/or a basic shape as shown in the screenshot
3. Try to select the element using a finger

**Expected behavior**
It should be easy to select such an element and then drag it around or resize it.

**Actual behavior**
It's very hard to select such an element.

**Tablet**
 - OS: iPadOS 14.4.2
 - Version: 6.4.9 (1)

**Comment by nikslor** [comment] 2023-02-23 11:40
@pedropintosilva is this something we should label with "UX"? I wonder how complex it is to fix this?

**Comment by pedropintosilva** [comment] 2023-02-23 13:24
Maybe we can close this ( #2099 ) as a duplicate of #1462 ? It would be good if we do so to add your screenshot there and notes (let me do that)

**Closed** 2023-02-23 13:27 UTC
Labels: bug, UX, ios
