### ISSUE TITLE
Android app does not save changes on close

### ISSUE THREAD

**Issue by timur-g** [CollaboraOnline/online#9861] opened 2024-08-20 16:49 UTC
Android app 24.04 snapshot does not save changes on edit, up-left check mark, up-left back button to close.
That worked in 21.11 so regression.

@Minion3665 please see.

**Comment by Minion3665** [comment] 2024-08-21 08:08
@timur-g I've tested and I'm not able to reproduce this. We have lots of different snapshots - some are built from different code - may you give me more of an idea of the version (e.g. menu>help>about and send the "git hash" of both COOLWSD and LOKit)

additionally, are there any other details that could be required for this bug to occur - e.g. I'm testing with a new, blank writer document: do you have a test doc that this is reproducible on? does it only happen for one type of document?

Thanks!

**Comment by timur-g** [comment] 2024-08-21 09:42
Thank you, it really is about specific document.

[New Text Document.odt](https://github.com/user-attachments/files/16689663/New.Text.Document.odt)

App is armeabi7 24.04.99-759.

Help-About does not copy info for me.

**Comment by Minion3665** [comment] 2024-08-21 11:00
> Thank you, it really is about specific document, that could save also in 23.05.7.

I'm really not getting this, even while using the document you provided ... there must be something else too ... may you send some screenshots/a screen recording, particularly of the info in Help-About? Thanks

**Comment by timur-g** [comment] 2024-08-21 12:22
![Edited](https://github.com/user-attachments/assets/6e55745b-8746-407e-8702-af83a666669a)
![Opened](https://github.com/user-attachments/assets/a41fe1d8-de29-4222-bedd-a54cd8eff316)
![Version](https://github.com/user-attachments/assets/af7c5129-195c-4009-8d54-fa36975908ad)

Here are screenshots. Text added in edit mode is not there after exit by up-left button and reopen.

**Comment by timur-g** [comment] 2024-08-22 07:04
I cannot reproduce today. I restarted the phone.
Yesterday I reprodued multiple times. 
We may keep it open for a while and later close of no similar report.

**Comment by timur-g** [comment] 2024-08-22 07:04
I cannot reproduce today. I restarted the phone.
Yesterday I reprodued multiple times. 
We may keep it open for a while and later close of no similar report.

**Comment by Minion3665** [comment] 2024-08-27 08:51
Closing as unreproducible, if you are able to reproduce this again please feel free to write in this issue and we'll reopen it

**Closed by Minion3665** 2024-08-27 08:51 UTC
Labels: bug, regression, android, unconfirmed, 24.04, Not Reproducible
