### ISSUE TITLE
Writer: Can't create a hyperlink when text contains Estonian characters

### ISSUE THREAD

**Issue by edmundlaugasson** [CollaboraOnline/online#3646] opened 2021-11-16 22:43 UTC
**Describe the bug**
When words contain [Estonian characters](https://en.wikipedia.org/wiki/Estonian_language#Alphabet), cannot create a hyperlink in Writer.

**To Reproduce**
1. Insert multiple words with Estonian characters
2. select them
3. open "Insert hyperlink" dialog either with CTRL+K or via appropriate button
4. Insert the hyperlink and press OK or Enter
5. Hyperlink is NOT created

**Expected behavior**
Hyperlink IS created

**Actual behavior**
Hyperlink is NOT created

**Desktop (please complete the following information)**
- OS: [EndeavourOS](https://en.wikipedia.org/wiki/EndeavourOS) with [KDE](https://en.wikipedia.org/wiki/KDE)
- Browser: Chromium
- Version: 95.0.4638.69
- Nextcloud 22.2.3
- Collabora Online 4.2.3
- Collabora Online - Built-in CODE Server 6.4.1303

**Additional context**
Example sentence in Estonian:
_Siin on mitu sõna ühes lauses._
You can make hyperlink with three first words but as soon as comes one of Estonian characters into selected words, no hyperlink will be created.
Try to create hyperlink with words, that contain Estonian characters: õ, ü, ä, ö, ž, š. You can also just type one of these characters and try to make that character as hyperlink - it won't succeed.

**Comment by Ezinnem** [comment] 2021-11-18 08:39
I cannot seem to be able to reproduce this issue on my end using the LOOLWSD 6.4.14 (git hash: [e30c297b0](https://github.com/CollaboraOnline/online/commits/e30c297b0)).

**Comment by Ezinnem** [comment] 2021-12-02 09:25
Closing this issue because it is not reproducible on my end and the author did not respond.

**Comment by edmundlaugasson** [comment] 2021-12-02 16:09
Well, I cannot then just use Nextcloud and its Collabora Online... It's easy to say, that not reproducible... It seems like I am kidding and thinking out these issues... It's weird way to solve issues by just closing them... It seems for me, that you just didn't notice, that there are Estonian characters involved. Certainly with English alphabet you don't see these issues. Currently there is Nextcloud 23.x update available, that breaks a lot of apps, including Collabora Online and CODE server - cannot update. Let's hope, that this will be fixed soon and we can update. perhaps it will fix also current issue as I see, that no other solution is not coming...

**Comment by timur-g** [comment] 2024-02-05 10:53
This might have been a duplicate of #2628. Both are not reproducible for me using current Online or Built-in Server. 
It would be good if you can also retest.

**Closed by timur-g** 2024-02-05 10:53 UTC
Labels: bug, unconfirmed
