### ISSUE TITLE
Calc: Scrolling is smoother with Chromium than Firefox.

### ISSUE THREAD

**Issue by Go-rom** [CollaboraOnline/online#4475] opened 2022-03-24 10:12 UTC
Hello

**Describe the bug**
With Spreadsheet, scrolling is better handled with Chromium than Firefox.

**To Reproduce**
1. Open a new spreadsheet with Chromium and Firefox (better with a template)
2. Scroll up/down
3. Compare

**Expected behavior**
Get same scrolling behavior with Firefox

**Actual behavior**
With Chromium, i'm able to scroll up and down without skipping a row.
With Firefox, scrolling down skips at least 2 rows.

I checked smooth scrolling setting in Firefox and it's ON.

**Desktop (please complete the following information)**
 - OS: Linux Mint 20.1 up to date
 - Browser: Firefox 98.0.2 and Chromium 99
 - Version COOLWSD : 21.11.2.4

Thank you, have a great day.

**Comment by mmeeks** [comment] 2022-03-31 10:12
Might be interesting to use whatever firefox uses for profiling to look at this.
The ultimate fix is probably some of copy-Area optimization in the CanvasTileLayer.js - but worth profiling first =)

**Comment by gohrner** [comment] 2022-04-26 10:58
I can confirm that accessing bigger Calc sheets with Firefox causes much higher system load and much more "laggy" browser behaviour compared to Chromium.

(Interestingly, but another issue probably, is that scrolling with the mouse wheel does not work in Firefox (at least on Linux)?)

**Comment by Alternativend** [comment] 2022-04-28 17:51
I can confirm this too. I can also confirm the comment from @gohrner.  

Im at Firefox 100 Linux and Windows Desktops
Coolwsd 21.11.4.1 git hash:  [5e2e1b63]
LOKit Version: Collabora OfficeDev 21.06.27.1
Debian Bullseye

Im also having trouble opening docx and other files with Firefox. Chromium is fine but Firefox get stuck and the documents are not opening at all anymore in most times.

**Comment by gohrner** [comment] 2022-04-29 07:43
@Alternativend: I didn't observer any edit problems in Firefox so far - just that it's much more "laggy" than in Chrome.

@mmeeks: Trying to profile it was the first thing I attempted, but so far I was not successful in using Firefox' profiling features.

While it's pretty simple in Chrome, Firefox just opens a second, completely empty white tab with the URL https://profiler.firefox.com/from-browser?implementation=js, and no information in the Development Tool section whatsoever.

I didn't really have time to invest into debugging this and so far could not figure out what to do with it or how to use it... Not sure if I'm using it in a wrong way, or if something's broken in Firefox, or where the problem is...

**Comment by Alternativend** [comment] 2022-04-29 12:33
I did a profile run: https://share.firefox.dev/3LyNnri. Hope it helps. 
@gohrner it definitely is more laggy. Maybe my problems will occur at you too when you update to the same versions. Would be nice to know if im doing something wrong here or it´s Firefox or Coolwsd or whatever.

**Comment by mmeeks** [comment] 2022-04-29 16:52
@Alternativend thanks for that - really useful to have the exception from the console in Firefox ! =)

**Comment by mmeeks** [comment] 2022-04-29 17:12
@Alternativend so back to the firefox profile - that is some very pretty thing; I didn't realize they had a nice profile sharing site - that rocks. Then again - can you profile the scrolling up and down in a sheet which is the root bug here? we should discuss the firefox not working issue in the another ticket to avoid cluttering this one.

**Comment by Alternativend** [comment] 2022-05-02 12:53
@mmeeks 
Sure thing, here you go: https://share.firefox.dev/3F8lkg7

It was a basically empty XLSX file in that case. Hope it helps. If you need the account again, just tell me.

**Comment by mmeeks** [comment] 2023-01-10 11:49
Ooh - the link to the firefox profiling site is beautiful - thanks for that  - very interesting - seems a lot of the render time is spent on the CPU doing Skia rendering of the canvas: 
![image](https://user-images.githubusercontent.com/122848/211543403-5a2c3c80-94da-4fb5-a1ac-f5b207252fe1.png)
Which is rather interesting - there is a lot of similiarity to those rendering patterns too - I'd like to hope we're not re-drawing the same things multiple times - but it's possible there is something silly like that going on - of course, split-panes means we need to do the rendering pass 4x times - but this should be clipped suitably.

Interesting trace - thanks ! =)

**Comment by mmeeks** [comment] 2023-01-10 12:37
Ooh - the link to the firefox profiling site is beautiful - thanks for that - very interesting - seems a lot of the render time is spent on the CPU doing Skia rendering of the canvas:
![profile](https://user-images.githubusercontent.com/122848/211553480-8aaf0928-5856-4f3e-809d-29895c9ab867.png)
Which is rather interesting - there is a lot of similiarity to those rendering patterns too - I'd like to hope we're not re-drawing the same things multiple times - but it's possible there is something silly like that going on - of course, split-panes means we need to do the rendering pass 4x times - but this should be clipped suitably.

**Comment by gokaysatir** [comment] 2023-01-16 14:11
This should improve with the next CODE release next week. We just merged a path for reducing the number of drawing calls.

**Comment by raxod502** [comment] 2023-01-18 23:35
Cross-linking to my forum post about the same issue - https://help.nextcloud.com/t/collabora-laggy-only-on-firefox-not-chrome/153734

Excited to hear this may improve soon, I will be happy to help test!

**Comment by thebearon** [comment] 2023-02-16 00:03
@raxod502 and others, has this become better for you in CODE 22.05.10-1?

**Comment by raxod502** [comment] 2023-02-16 02:01
I've been working on understanding how I can control the version of Collabora that is used in my Nextcloud deployment (https://github.com/nextcloud/all-in-one), or even tell what version is in use, so that I could help answer exactly that question. I spent some time looking for documentation and even poking around the process tables and config files I found in the Docker images on my server, but to no avail. Do you happen to know if any of this is exposed or customizable in nextcloud-aio? I am happy to ask for support downstream as well if not.

**Comment by Programie** [comment] 2023-02-16 09:25
I just tested CODE 22.05.10-1 in Firefox 110.0 and scrolling is now much better than before.

**Comment by gohrner** [comment] 2023-03-07 12:57
@gitgt: It's "usable" with Firefox, but still significantly "snappier" with Chrome.

**CODE version:**

COOLWSD Version:
22.05.10.8
git hash: 
[ef89c82](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/ef89c82'));)
(E)
LOKit Version:
built on 
[a great technology base](javascript:void(window.open('http://col.la/lot'));)
Collabora Office 22.05.10.7
git hash: 
[d1b6e23](javascript:void(window.open('https://hub.libreoffice.org/git-core/d1b6e23'));)
Angeboten von:
 
Ubuntu 18.04.6 LTS
 
e1519bac

**Client computer:**
* Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
* Ubuntu 22.04
* Firefox 110.0.1 (64-bit) (Ubuntu Snap)
* Chromium Version 110.0.5481.100 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by raxod502** [comment] 2023-04-04 01:25
After a few months I finally found a place in Nextcloud where I can check what version of Collabora is being used:

```
Coolwsd version details: 22.05.12.4
```

This is now more recent than the 22.05.10-1 mentioned in https://github.com/CollaboraOnline/online/issues/4475#issuecomment-1432255357. Like other commenters I find the behavior on the border of usable, but still scrolling is around 5FPS in Firefox versus no perceptible lag or delay in Chrome.

**Comment by relikd** [comment] 2023-05-30 20:09
I've tested this (with docker) on 22.05.14.3.1, 22.05.12.4.1, 22.05.12.1.1, 22.05.10.8.1, and 22.05.10.1.1. I am not 100% sure but it *feels* like version 10 is a tad faster than the newer releases 12 and up. I am not sure if I can distinguish the differences anymore after so much back and forth of the versions. Also, maybe it depends on the server load and thus isnt comparable and I just imagine differences.

(5.15 isnt available on docker yet, so I cant test it with the latest release)

But I can add one more thing: Whenever I scroll in FF, collabora places all scroll actions in a queue and executes them one after another. If I rapidly scroll up and down on my touchpad, these scroll actions are executed one after another. If I scroll up-down-up-down-up-down and then let go of any scrolling, the page will still perform all scroll events even though I am not touching the keyboard/touchpad anymore. I wonder whether this is the reason for the slow scroll performance.

(using latest Firefox on mac)

**Comment by Go-rom** [comment] 2023-06-15 06:31
Hello,

last version tested : 22.05.13.1
Scrolling is better with Firefox but doesn't match Chromium.

With Chromium, the scrolling experience is near as good as a desktop class application.

**Comment by Ornanovitch** [comment] 2023-07-18 12:01
Hi,

I experience the same issue in 23.05: the scrolling is way better with Chromium than with FF.

Thanks!

**Comment by timur-g** [comment] 2023-08-08 13:57
Hey folks, with thanks for your previous reporting and testing, please test again with 23.05.2.2,
As seen in the previously referenced issue, this may be improved there, and if so, this ticket may be considered resolved.
I understand that reporters used 22.05 but it is no more relevant for this.

**Comment by Ornanovitch** [comment] 2023-08-08 20:41
Fixed for me :)

**Comment by mmeeks** [comment] 2023-08-09 13:13
Wonderful - thanks everyone for your helpful feedback here ! =)

**Closed by mmeeks** 2023-08-09 13:13 UTC
Labels: bug, info needed, 22.05.x

**Comment by flightmansam** [comment] 2024-04-09 05:46
This doesn't seem to be fixed on the current latest builds. I am finding the chromium is night and day difference than firefox (even with GPU acceleration switched on in firefox).


COOLWSD version:
23.05.10.1
git hash: 
baa6eef
(E)
LOKit version:
built on 
a great technology base
Collabora Office 23.05.10.1
git hash: 
c8fa7c0
Served by:
 
Debian GNU/Linux 12 (bookworm)
