### ISSUE TITLE
XIRR function does not work

### ISSUE THREAD

**Issue by ifuchs** [CollaboraOnline/online#1519] opened 2021-02-23 01:05 UTC
**Describe the bug**
XIRR unction produces a 0 result regardless of input
**To Reproduce**
1. Place -2 in cell A1
2. Place 4 in cell A2
3. Place dates in cells B1:B2
4. Put =xirr(a1:a2,b1:b2) in any cell
Get result of 0E-307

**Expected behavior**
Result should be percentage that depends on the input

**Desktop (please complete the following information)**
 - OS: [iOS]

**Comment by thebearon** [comment] 2021-02-23 06:41
Strangely this bug is only in the iOS app.

**Comment by timar** [comment] 2021-02-23 09:11
What dates did you put to cells B1:B2?

**Comment by ifuchs** [comment] 2021-02-23 12:31
It didn’t seen to matter. 02/20/2020, 02/20/2021 will produce the error.

**Comment by thebearon** [comment] 2021-02-24 14:43
Here's a sample ODS, the result in B3 should be 1: 
[xirr.zip](https://github.com/CollaboraOnline/online/files/6036731/xirr.zip)

**Comment by ifuchs** [comment] 2021-02-24 14:50
My bad. My dates were in an incorrect format. (MM/DD/YYYY) rather than
YYYY-MM-DD

**Comment by ifuchs** [comment] 2021-02-24 15:30
I spoke too soon. The sheet does not work (as before):

**Comment by ifuchs** [comment] 2021-02-24 15:32
https://imgur.com/a/VLlA4J5

**Comment by timar** [comment] 2021-02-25 12:47
We found that probably the spreadsheet functions defined in the `scaddins` source code module are not working on iOS. We'll investigate why.

**Comment by tml1024** [comment] 2021-03-02 09:36
On this now.

**Comment by tml1024** [comment] 2021-03-02 10:23
Surprisingly, seems that the problem is related to the C++/UNO bridge code for iOS and the handling of floating-point return values in that. Quite possible that that is something which has been broken forever for iOS but which gets exercised only by the functions in the scaddins thing. (My initial educated guess was it has to be related to the dynamic loading of the scaddins things, but apparently not.)

**Comment by timar** [comment] 2021-03-03 21:30
The fix will be in next release for iOS, so let's close this here.

**Closed by timar** 2021-03-03 21:30 UTC
Labels: bug, ios-app
