### ISSUE TITLE
Scroll in sheet bug

### ISSUE THREAD

**Issue by Starvin86** [CollaboraOnline/online#7637] opened 2023-11-08 22:32 UTC
### Describe the Bug

Scroll resets when using both horizontal and vertical scroll at the same time

### Steps to Reproduce

1. Open a new or existing sheet. 
2. Scroll both a bit down and to the right
3. Add a simpel text
4. Move the scroll round a bit. 
5. As long as you are not fixed to top row or first coll. 
6. After a few sec it locks up a bit, and reset scroll to either top row or first coll. 
7. No error just it keeps resetting scroll if you scroll a bit down and right. 

### Expected Behavior

Don't reset scroll, but keep being at position you scroll to so you can read or edit the sheet. 

### Actual Behavior

It reset your vertical or horizontal scroll and you can't read or edit outside the default loading area, if both scrolled down and right in the sheet. 

### Screenshots

Not applicable. 

### Smartphone

(Please complete the following information)
- samsung s10
- android  12
- collabora office android app
- version 25.05.5.2

**Comment by Ezinnem** [comment] 2023-11-21 20:59
Please can you add a screen-recording to give a more visual understanding of the issue?

**Comment by martinzwirner** [comment] 2023-12-30 13:57
I have the same issue in one of my own files and was able to reproduce it with a new file using the steps above.

I'm running Collabora Office Android app version 23.05.5.2 on Android 9 on a Samsung Galaxy S7.

**Comment by Starvin86** [comment] 2023-12-30 16:15
> Please can you add a screen-recording to give a more visual understanding of the issue?

https://cloud.ghostcode.dk/apps/memories/s/KEmt2niyrrr6fSc

**Comment by Tex2002ans** [comment] 2024-02-06 02:56
@Starvin86 , I'm attaching your video here so it doesn't get lost (in case your shared link goes down):

https://github.com/CollaboraOnline/online/assets/5774324/c51dd6ef-11a5-4403-9632-ed25605c1b9d

@Ezinnem, mind checking this again? I think it can probably be confirmed at least, since @martinzwirner had the same exact issue.

@martinzwirner Can you please post your Collabora app's **Three-line menu > About** info too?

**Comment by Oriann** [comment] 2024-03-13 15:57
I have same issue as OP.

**Comment by Donty10** [comment] 2024-06-12 22:02
I am also experiencing this issue

**Comment by Tex2002ans** [comment] 2024-06-13 07:23
Hey @Oriann + @Donty10 . Could you please give your Collabora:

- **Three-line menu > About** info

and any other helpful version info too?

**Comment by Oriann** [comment] 2024-06-13 07:25
Posting screenshot here
![Screenshot_20240613_092510_Nextcloud.jpg](https://github.com/CollaboraOnline/online/assets/11374526/8b9071e1-4507-4868-b883-224b2bd24a80)

**Comment by Donty10** [comment] 2024-06-13 08:06
COOLWSD version: 24.04.4.1
(git hash: 
9091043
(E))
LOKit version: Collabora Office 24.04.4.1
(git hash: 
fdb5e53)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: 4c386a8b

I am running Collabora Online in a podman container on a Fedora 40 Server VM and I am running Nextcloud in a Debian Bookworm VM on the same machine. Also no issues on desktop. Both are being run behind NGINX reverse proxy.

**Comment by Oriann** [comment] 2024-07-09 07:58
Resolution in 23.05 but we are already in 24.04 with no fix, does somebody from devs register this problem ? Collabora is unusable on mobile phone with this bug.

**Comment by siccovansas** [comment] 2024-09-15 15:57
This issue seems to be fixed since at least 24.04.6.2. See the latest comments in https://github.com/CollaboraOnline/online/issues/9291.

**Comment by timur-g** [comment] 2024-09-16 06:42
Seems so. Not sure how, I thought I tested it with 24.04.6.2. 
There is another issue I saw few times, but I do not have steps: after I scrolled, sheet continues to scroll on its own. That probably deserves anotther ticket, if reproduced by someone else. 
cc @Minion3665

**Comment by Minion3665** [comment] 2024-09-16 09:10
> This issue seems to be fixed since at least 24.04.6.2

awesome, glad to hear :)

> There is another issue I saw few times, but I do not have steps: after I scrolled, sheet continues to scroll on its own

in that case, may you make an issue for it anyway, keeping it unconfirmed. Thanks!

I'm going to close this now as it's fixed, thanks very much for the report and testing everyone :)

**Closed by Minion3665** 2024-09-16 09:10 UTC
Labels: bug, android, 23.05, 24.04
