### ISSUE TITLE
Font Previews in the Sidebar "Style" dropdown shrink/expand on each open

### ISSUE THREAD

**Issue by Tex2002ans** [CollaboraOnline/online#8499] opened 2024-03-09 06:01 UTC
### Describe the Bug

In the sidebar's "Style" dropdown, each time the font dropdown is opened/closed, some font previews change size.

### Steps to Reproduce

In Writer:

0. **View > Sidebar** ON
1. In the sidebar, under "Style":
   - Open and close the font dropdown multiple times.

[Collabora.24.04.0.0.-.Sidebar.Style.Dropdown.Fonts.Resizing.webm](https://github.com/CollaboraOnline/online/assets/5774324/33459077-c60b-4568-8a9f-e49e958351f9)

- 2–10 secs = I open/close it 6 times.
- At 4 secs = you can even see "Clear Formatting" and "Preformatted Text" change as dropdown is open.
- At 7 secs = you can see "Clear Formatting" was italics.
   - So not just a size issue. Formatting gets introduced too.

### Expected Behavior

All font previews to stay the same.

### Actual Behavior

"Clear Formatting" and "Preformatted Text" keep getting larger/smaller each time you open the dropdown.

### Desktop

- **Collabora version:** 24.04.0.0
- **OS and version:** Linux Mint 21.3
- **Browser and version:** Firefox 123.0

> COOLWSD version: 24.04.0.0 (git hash: ff61e2a5)
> LOKit version: Collabora Office 23.05.9.3 (git hash: 0dbe461)
> Served by: Linux Mint 21.3
> Server ID: 0a888e51

I also saw this happen on Share using Chrome:

> COOLWSD version: 23.05.9.3snapshot (git hash: 14e0056)
> LOKit version: Collabora Office 23.05.9.20240305 (git hash: 0dbe461)
> Served by: Ubuntu 22.04.4 LTS
> Server ID: 2850da3d

### Additional Context

First spotted this during COOL Weekly 159.

It might only happen on the "first/last" fonts showing in the list. The fonts in-between those 2 seem to stay steady.

**Comment by codewithvk** [comment] 2024-04-04 05:17
Similar issue : #8562

**Comment by Tex2002ans** [comment] 2024-04-25 02:07
Still an issue on:

> COOLWSD version: 24.04.1.3 (git hash: 8510db55)
> LOKit version: Collabora Office 24.04.1.4 (git hash: 91ae3cd)
> Served by: Linux Mint 21.3
> Server ID: b7bb7996

**Comment by Darshan-upadhyay1110** [comment] 2024-11-11 16:48
Duplicate of https://github.com/CollaboraOnline/online/issues/8562

**Closed by Darshan-upadhyay1110** 2024-11-11 16:48 UTC
Labels: bug, unconfirmed
