### ISSUE TITLE
Moving in excel sheet on android cause resseting view, also sheet is choppy

### ISSUE THREAD

**Issue by Oriann** [CollaboraOnline/online#9291] opened 2024-06-15 14:10 UTC
**Describe the bug**
Opening excel sheet in nextcloud android app is resseting view to upper left most corner, also moving through sheet is choppy.

**To Reproduce**
1. Open excel sheet in nextcloud on android phone
2. Move through the sheet
3. View consistently resseting to upper left most corner and moving through sheet is also choppy.

**Expected behavior**
Moving through sheet is not resseting view and is not choppy.

**Screenshots**
Video here:

https://github.com/nextcloud/richdocuments/assets/11374526/c1c95564-9c86-4841-9488-5566a413f4ae

**Client details:**
 - OS: Android 14
 - Nextcloud app version: 3.29.0
 - Collabora online version: 24.04.3.2 (standalone install)
 - Device: Samsung Galaxy S24 Ultra

## Server details

**Operating system**:
Debian 12 Bookworm
**Web server:** 
Nginx 26.1
**Database:**
MariaDB 10.11.8
**PHP version:**
PHP 8.2
**Nextcloud version:**
28.0.6
**Version of the richdocuments app**
8.3.7
**Version of Collabora Online**
24.04.3.2
**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "canonical_webroot": "",
            "disable_certificate_verification": "",
            "doc_format": "ooxml",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "8.3.7",
            "public_wopi_url": "https:\/\/collabora.*****.cz",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "192.168.2.0\/24",
            "wopi_url": "https:\/\/collabora.*****.cz"
        }
    }
}

```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Empty log
```

#### Browser log
```
Not applicable, problem is in android app
```

</details>

**Comment by siccovansas** [comment] 2024-06-29 21:16
I'm having the same issue when I open a spreadsheet with my Nextcloud app on Android. I have similar issues with the standalone [Collabora Office](https://play.google.com/store/apps/details?id=com.collabora.libreoffice&hl=en_US) app.

My info:
- Device: Samsung Galaxy S23
- OS: Android 14
- Nextcloud app version: 3.29.0
- Collabora Online - Built-in CODE Server : 24.4.402

- Collabora Office app version: 23.05.7.4

This issue seems related to or the same as #7637?

**Comment by siccovansas** [comment] 2024-06-29 21:18
I'm having the same issue when I open a spreadsheet with my Nextcloud app on Android. I have similar issues with the standalone [Collabora Office](https://play.google.com/store/apps/details?id=com.collabora.libreoffice&hl=en_US) app.

My info:
- OS: Android 14
- Nextcloud app version: 3.29.0
- Collabora online version: 24.04.3.2 (standalone install)
- Device: Samsung Galaxy S23

- Collabora Office app version: 23.05.7.4

This issue seems related to or the same as #7637 and #7936?

**Comment by siccovansas** [comment] 2024-08-28 12:54
This issues still persists with Collabora Office app version 24.04.

My info:
- Nextcloud version: 28.0.9
- Device: Samsung Galaxy S23
- OS: Android 14
- Nextcloud app version: 3.29.1
- Collabora Online - Built-in CODE Server : 24.4.502
- Collabora Office app version: 24.04.6.2

This issue also seems to be related: https://help.nextcloud.com/t/nextcloud-office-scrolling-issue-in-spreadsheets-on-mobile/188535/10

Could someone from Collabora weigh in on this (@Ezinnem @Minion3665 @timur-g)? Do you need more info? Can you reproduce it? It is quite a serious issue for multiple people (see also the related issues in my previous comment) as it makes viewing/editing a spreadsheet in the Android Collabora/Nextcloud app impossible.

**Comment by timur-g** [comment] 2024-08-28 12:58
This is know issue that was not resolved in Android app 24.04.6, that is the first release after 23.05.5.

**Comment by Minion3665** [comment] 2024-08-28 13:14
Thanks for the `@mention`, @siccovansas - the choppiness is a problem, but I'm most concerned about the jumping to the top-left corner here ... frustratingly it's also something that I'm having trouble making happen on my devices.

Do you see this on all spreadsheets, or does it only happen on some of them? If it's only some spreadsheets, could you perhaps send us one to test with?

---

Thanks again, and apologies for the radio silence on your report. You've done a great job at keeping this ticket up-to-date with all the different places you've found this happening, and I appreciate it!

**Comment by OdinsAuge** [comment] 2024-08-28 13:30
I have the same issue, I raised it in the NC forum.
So that's my experience:
I tried different spreadsheets, uploaded Excel file and newly generated odt file.
With lots of content and almost no content.
It happened on all the files, more content seems to cause it earlier.
I tried acces from LAN and WAN, no difference.
I tried 3 different phones (all Android, a Pixel, a Samsung and a OnePlus) happened on all devices.
I shared the link to someone in the NC forum and he said he couldn't reproduce it.

**Comment by Minion3665** [comment] 2024-08-28 13:46
> more content seems to cause it earlier

👀 interesting, is this earlier in time or earlier in the sheet? (i.e. does it only start happening after a few minutes in the document or do you have to scroll down further to make it happen at all with less content)

---

It's interesting that someone else on the NC forum couldn't reproduce it but you've been able to wholly reliably too - I wonder if it only affects a high proportion of devices or something like that ... maybe I should drag out my old Android phones from my drawer 😅

**Comment by Minion3665** [comment] 2024-08-28 14:41
> @Minion3665 thanks for the quick reply 🙏!
> 
> I did some more debugging and my previous comment was incorrect. It seems that the issue is fixed in Collabora Office Android app 24.04.6.2!

Awesome to hear that! As we know the issue isn't reproducible for everyone, I'd like to check with @OdinsAuge to make sure that it's not occuring in the recent 24.04.6.2 update before we close the ticket. May you test with the latest version (or let us know what version you tested with?). Thanks!

> If I open the same file in the Nextcloud Android app (3.29.1) I still have the issue though. I'm not sure which version of Collabora is integrated in 3.29.1 of the Nextcloud Android app?

My belief is the Nextcloud app uses whatever version of Collabora Online your server does - although I could be wrong on that, it's an educated guess more than knowing. To check, when you're in Collabora you could go into the menu, click on about, and take a screenshot. It'll say the versions of COOLWSD (that's this repository) as well as LOKit (that's the version of LibreOffice it's communicating with). It'll also have more details including the git hashes of both that can let me know the exact version.

**Comment by siccovansas** [comment] 2024-08-28 20:21
Thanks again for the quick reply :pray:!

I reinstalled an older version of the Collabora Office Android app (23.05.7.4) to double check if the bug was there, and indeed the issue is present. The latest version 24.04.6.2 version of the Collabora Office Android app works fine. The Nextcloud Android app uses version 24.04.5.2, and the issue is present there. So I'll wait for an update of richdocumentscode (@timar :heart:) after which I'll check if the issues is then also solved in the Nextcloud Android app :pray:.

:x: the issue is present
**Collabora Office Android app**
Version: **23.05.7.4**

:x: the issue is present
**Nextcloud Android app**
COOLWSD version: **24.04.5.2**
(git hash: ca2ed20(E))
LOKit version: Collabora Office 24.04.5.2
(git hash: ff487ed)

:white_check_mark: works fine
**Collabora Office Android app**
Version: **24.04.6.2**
online git-hash: ff31007487
core git-hash: be5e7ffd7c20

**Comment by OdinsAuge** [comment] 2024-08-29 08:41
@Minion3665 with later, I meant scrolling further (sorry for beeing not precise enough).
I could recreate the tests @siccovansas did but would need some time, as I'm a bit busy atm.

**Comment by siccovansas** [comment] 2024-09-15 15:52
So richdocumentcode was just updated to 24.4.702 and this fixes the issue! Thanks everyone 🙏!

✅ works fine
**Nextcloud Android app**
COOLWSD version: **24.04.7.2**
(git hash: d5ebff5 (E))
LOKit version: Collabora Office 24.04.7.2
(git hash: 8c74383)

**Comment by Minion3665** [comment] 2024-09-16 09:07
> now this issue is also fixed when using Collabora in Nextcloud

awesome, glad to hear that! In that case, I'll close this issue :)

**Closed by Minion3665** 2024-09-16 09:07 UTC
Labels: bug, phone, unconfirmed, calc
