### ISSUE TITLE
Writer (but probably Calc and Impress as well): Textboxes and Frames and maybe other objects cannot be copied 

### ISSUE THREAD

**Issue by smirta** [CollaboraOnline/online#1628] opened 2021-03-08 11:01 UTC
**Describe the bug**
Objects such as text boxes, frames and maybe more of this type cannot be copied or cut and pasted. But this works in the web browser.

**To Reproduce**
1. Open a document containing frames or text boxes
2. Select part of the text including them
3. Select "Copy" or "Cut"
4. Select "Paste" at another position in the document

**Expected behavior**
Text boxes and frames get copied to destination.

**Actual behavior**
Text boxes are not being copied and of the frames only the text (sometimes).

**Screenshots**
https://user-images.githubusercontent.com/6649852/110312443-60134700-8005-11eb-8f64-c17c78d31e7d.mov

**Smartphone (please complete the following information)**
 - Device: iPad
 - OS: iPadOS 14.2
 - Browser: n/a
 - Version: CollaboraOnline 6.4.4 and latest Textflight (6.4.5 (2)) 

**Additional context**

**Comment by tml1024** [comment] 2021-03-23 13:19
On this now. Can reproduce.

**Comment by tml1024** [comment] 2021-03-23 14:25
The same thing happens in current LibreOffice on macOS, too: If you copy something that contains a shape with text, quit LibreOffice, start it again, and paste into a text document, the shape is not there. (The iOS app does not keep any internal in-process clipboard, so copying and pasting in it is equivalent in desktop LO to copying, exiting, starting again, and pasting.)

Will check what happens on Windows.

With Linux it is much harder compare as it doesn't really have a system clipboard in the same sense as macOS, iOS, and Windows have, as far as I understand.

**Comment by tml1024** [comment] 2021-03-23 14:30
The same happens with Collabora Office on Windows, too. So this is a generic issue, not iOS-specific.

**Comment by tml1024** [comment] 2021-03-23 18:50
In fact the root cause of the issue can be demonstrated in an even simpler way in normal desktop LibreOffice. No exiting and re-starting required. See https://bugs.documentfoundation.org/show_bug.cgi?id=141210 . (This surely must be a duplicate of some much older bug report, but I was lazy and filed a new one.)

**Comment by tml1024** [comment] 2021-09-13 11:51
Removing the iOS label as per my comment from Mar 23.

**Comment by Darshan-upadhyay1110** [comment] 2024-08-13 11:35
Works okay in latest version 

COOLWSD version: 24.04.6.1 (git hash: 9dfee827)
LOKit version: Collabora OfficeDev 24.04.6.1 (git hash: 8b00f3a)
Served by: Ubuntu 23.10
Server ID: 83043426

**Closed** 2024-08-13 11:34 UTC
Labels: bug, desktop
