### ISSUE TITLE
emoji won't display

### ISSUE THREAD

**Issue by KiaraGrouwstra** [CollaboraOnline/online#5172] opened 2022-08-20 10:09 UTC
**Describe the bug**

**To Reproduce**
- use emoji (e.g. ✅❌) in a `.odt` document
- try different fonts
- find even EmojiOne Color to not display color, many other fonts not display the emoji at all

**Expected behavior**
have fonts lacking certain glyphs fall back on other fonts such that missing glyphs may still be displayed as well

**Actual behavior**
Emoji not displaying in many fonts, see screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/3059397/185740968-449099e3-4dff-409e-b5a8-31faea0e3bca.png)

**Desktop (please complete the following information)**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 103.0.2

**Comment by thebearon** [comment] 2022-10-10 01:30
I pasted the selection of examples from the emoji WikiPedia article, and they appeared perfectly fine in the document. The font selected doesn't matter, since emoji unicode characters aren't covered by normal fonts. I think the common emoji font would be Noto Color Emoji, it's also included with Collabora Online, no idea why it doesn't seem to be picked up in your case..

![emoji](https://user-images.githubusercontent.com/19438782/194788601-cb70c931-04eb-44aa-b7e0-15acea5129a4.png)

**Comment by Renari** [comment] 2023-04-20 13:28
![image](https://user-images.githubusercontent.com/1839179/233380851-22e0a0ff-e1e3-4144-a9d2-3dfeeb92a428.png)
I think this also effects other 4 unicode characters this is in an `.ods`, oddly enough it shows correctly at the top, but will not show correctly in the sheet with any font.

**Comment by timur-g** [comment] 2024-03-19 08:20
Since original report was not reproduced, I close this in favor of #7015 which, although seemed duplicate, now has another reproter with some details. @Renari please follow there.

**Closed by timur-g** 2024-03-19 08:20 UTC
Labels: bug, unconfirmed
