### ISSUE TITLE
No integrator theme (Nextcloud Skin) on Collabora 22.05

### ISSUE THREAD

**Issue by danir-de** [CollaboraOnline/online#5113] opened 2022-08-05 17:15 UTC
**Describe the bug**
Collabora Online 22.05 was released today. When updating Collabora from 21.11 to 22.05, the Nextcloud skin, including the logo set by Nextcloud are not displayed - Collabora loads in it's default skin.

**To Reproduce**
1. Upgrade to Collabora 22.05
2. Enable "use_integration_theme" in coolwsd config (or disable it, makes no difference)
3. Use user_interface mode "tabbed" (notebookbar is obsolete in 22.05)
4. Open any document.
5. Observe the vanilla Collabora skin

**Expected behavior**
The Nextcloud Collabora Skin should be applied, enabling you to open the document sidebar.

**Actual behavior**
The stock Collabora skin loads. You're not able to open the document sidebar by Nextcloud from within the editor, since the button is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/4672840/183127528-6a085ba0-fcb9-4285-ba27-7ad2c2b08196.png)

**Comment by danir-de** [comment] 2022-08-05 17:51
Crossposted on nextcloud/richdocuments/issues/2361  - unsure where it belongs. Please close here if not applicable.

**Comment by juliushaertl** [comment] 2022-08-09 05:21
What installation method did you use (docker, ubuntu/debian packages or others)?

For docker there seems to have been a follow up release at Aug 5, 2022 at 10:51 am where I cannot reproduce this, so maybe you can double check that with the latest release.

**Comment by juliushaertl** [comment] 2022-08-09 05:22
cc @gokaysatir

**Comment by danir-de** [comment] 2022-08-09 07:39
This was tested with the stable branch of 22.05 - debian packages. (Not CODE)

**Comment by thebearon** [comment] 2022-08-23 09:12
This has been clarified separately, thus let's close the issue.

**Closed by thebearon** 2022-08-23 09:12 UTC
Labels: bug, unconfirmed
