### ISSUE TITLE
Android: Dark mode it too dark

### ISSUE THREAD

**Issue by TheRealOne78** [CollaboraOnline/online#7259] opened 2023-09-14 21:23 UTC
### Describe the Bug

The latest (23.05.4.1) collabora office android build has a dark new theme which makes the page dark. Fonts are also black, so nothing is visible.

_Sepparate note_
As a feature request, having dark mode, but with white page would also be nice. (old behaviour, but as an option)

### Screenshots

White theme:
![Screenshot_20230915_001417_Collabora Office](https://github.com/CollaboraOnline/online/assets/53640879/b88a0456-b8ac-4680-92f9-82a95f96081c)

New dark theme:
![Screenshot_20230915_001452_Collabora Office](https://github.com/CollaboraOnline/online/assets/53640879/4203d91a-eace-43bf-94a5-d088594e26c5)

### Smartphone

(Please complete the following information)
 - **Device:** Samsung Galaxy A42 5G
 - **OS:** Android 12 (Samsung build)
 - **Version:** 23.05.4.1 F-Droid build

**Comment by TheRealOne78** [comment] 2023-09-14 21:28
One more somehow related note.

When you switch the theme in "Setting" > "Choose theme" and tap on "android <back>" the app freezes. As a workaround, I either closed the app and restared it, or "android tab" and tab again in the app to tap back.

There's also no "back" button in the app, which would be kind of nice to has as well as a feature request.

**Comment by sebastiaanveld** [comment] 2023-09-15 14:18
Think that the problem is that text you type default is using a "Black" font color. This should (or would) be better set to "Automatic" by default. If you select your text in non-dark mode and select as font color "Automatic", then switch to dark mode your text will be shown in white font color.

Agree that separate from this it would be good in Dark mode to have an option to make the sheet white as there may be a lot of existing documents that have the font color set to black instead of automatic.

**Comment by TheRealOne78** [comment] 2023-09-15 15:29
Ya, turns out automatic font color wasn't turned on by default.

Also, taping the document presents you with a white screen when it's loading, and only after that it's rendering with dark theme, which is probably not expected behaviour for a dark theme app.

> Agree that separate from this it would be good in Dark mode to have an option to make the sheet white as there may be a lot of existing documents that have the font color set to black instead of automatic.

Not only the font color issue, but I think it's also a good practice to have the sheet in white, since pretty much all paper sheets come in white, not black. For extreme dark theme lovers, I think they should also have the "all black" theme.

**Comment by timur-g** [comment] 2023-09-18 21:56
Menu-View has an option tu turn off dark mode. Also there is #6449 for separation. So I close this one.

**Closed** 2023-09-18 21:58 UTC
Labels: bug, android, unconfirmed, dark-mode
